import * as fs from 'fs';import * as path from 'path';import {Construct} from 'constructs';
import {Stack,StackProps,Duration,CfnOutput,RemovalPolicy,aws_s3 as s3,aws_sqs as sqs,aws_lambda as lambda,aws_lambda_event_sources as sources,aws_ec2 as ec2,aws_iam as iam,aws_batch as batch,aws_logs as logs,aws_events as events,aws_events_targets as targets} from 'aws-cdk-lib';
export class WeiqiFargateStack extends Stack{
 constructor(scope:Construct,id:string,props:StackProps & {libraryBucket:string;analysisQueueArn:string;dispatchEnabled?:boolean}){
  super(scope,id,props);const root=path.join(__dirname,'../..'),bucket=s3.Bucket.fromBucketName(this,'Library',props.libraryBucket);
  const vpc=new ec2.Vpc(this,'Network',{maxAzs:2,natGateways:0,subnetConfiguration:[{name:'Public',subnetType:ec2.SubnetType.PUBLIC}]});const security=new ec2.SecurityGroup(this,'Security',{vpc,allowAllOutbound:true});
  const compute=new batch.CfnComputeEnvironment(this,'Compute',{type:'MANAGED',state:'ENABLED',computeResources:{type:'FARGATE',maxvCpus:64,subnets:vpc.publicSubnets.map(s=>s.subnetId),securityGroupIds:[security.securityGroupId]}});
  const queue=new batch.CfnJobQueue(this,'Queue',{priority:100,state:'ENABLED',computeEnvironmentOrder:[{computeEnvironment:compute.ref,order:1}]});
  const deepCompute=new batch.CfnComputeEnvironment(this,'DeepCompute',{type:'MANAGED',state:'ENABLED',computeResources:{type:'FARGATE',maxvCpus:64,subnets:vpc.publicSubnets.map(s=>s.subnetId),securityGroupIds:[security.securityGroupId]}});
  const deepQueue=new batch.CfnJobQueue(this,'DeepQueue',{priority:1,state:'ENABLED',computeEnvironmentOrder:[{computeEnvironment:deepCompute.ref,order:1}]});
  const executionRole=new iam.Role(this,'ExecutionRole',{assumedBy:new iam.ServicePrincipal('ecs-tasks.amazonaws.com'),managedPolicies:[iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AmazonECSTaskExecutionRolePolicy')]});
  const taskRole=new iam.Role(this,'TaskRole',{assumedBy:new iam.ServicePrincipal('ecs-tasks.amazonaws.com')});bucket.grantRead(taskRole,'code/*');bucket.grantReadWrite(taskRole,'jobs/*');bucket.grantReadWrite(taskRole,'games/*');bucket.grantReadWrite(taskRole,'benchmarks/*');
  const log=new logs.LogGroup(this,'WorkerLogs',{retention:logs.RetentionDays.ONE_WEEK,removalPolicy:RemovalPolicy.DESTROY});
  const bootstrap="import os,sys,subprocess,urllib.request,time,json;start=time.time();os.environ['BOOT_STARTED_AT']=str(start);subprocess.run([sys.executable,'-m','pip','install','--quiet','boto3==1.40.0'],check=True);sdk=time.time();__import__('boto3').client('s3').download_file(os.environ['LIBRARY_BUCKET'],'code/fargate-worker.py','/tmp/worker.py');os.environ['BOOT_TIMINGS']=json.dumps({'installSdkMs':round((sdk-start)*1000),'downloadWorkerMs':round((time.time()-sdk)*1000)});subprocess.run([sys.executable,'/tmp/worker.py'],check=True)";
  const definition=new batch.CfnJobDefinition(this,'Job',{type:'container',platformCapabilities:['FARGATE'],retryStrategy:{attempts:1},timeout:{attemptDurationSeconds:14400},containerProperties:{image:'public.ecr.aws/docker/library/python:3.12-slim',executionRoleArn:executionRole.roleArn,jobRoleArn:taskRole.roleArn,command:['python','-c',bootstrap],resourceRequirements:[{type:'VCPU',value:'32'},{type:'MEMORY',value:'61440'}],networkConfiguration:{assignPublicIp:'ENABLED'},environment:[{name:'LIBRARY_BUCKET',value:bucket.bucketName},{name:'DOWNLOAD_ENGINE',value:'1'},{name:'KATAGO_BIN',value:'/tmp/engine/katago'},{name:'BACKEND',value:'fargate-cpu'},{name:'SEARCH_THREADS',value:'1'},{name:'ANALYSIS_THREADS',value:'32'},{name:'NN_THREADS',value:'32'},{name:'KATAGO_DOWNLOAD_URL',value:'https://github.com/lightvector/KataGo/releases/download/v1.18.1/katago-v1.18.1-eigenavx2-linux-x64.zip'},{name:'KATAGO_ZIP_SHA256',value:'33e79780dbe3bf6ee859e16f64952cdfc90f7210c8f71ad978ffcba85ad20d79'}],logConfiguration:{logDriver:'awslogs',options:{'awslogs-group':log.logGroupName,'awslogs-region':this.region,'awslogs-stream-prefix':'analysis'}}}});
  if(props.dispatchEnabled!==false){
  const shared=['src/engine.js','src/sgf.js','backend/library-service.js'].map(file=>fs.readFileSync(path.join(root,file),'utf8').replace(/^import .*;\n/gm,'').replace(/^export /gm,'')).join('\n');
  const modelResolver=fs.readFileSync(path.join(root,'backend/katago-model.cjs'),'utf8').replace(/^module.exports=.*;$/gm,'');
  const dispatcher=new lambda.Function(this,'Dispatcher',{runtime:lambda.Runtime.NODEJS_22_X,code:lambda.Code.fromInline(shared+'\n'+modelResolver+'\n'+fs.readFileSync(path.join(root,'backend/fargate-dispatcher.cjs'),'utf8')),handler:'index.handler',timeout:Duration.seconds(30),memorySize:256,environment:{LIBRARY_BUCKET:bucket.bucketName,JOB_QUEUE:queue.ref,DEEP_QUEUE:deepQueue.ref,JOB_DEFINITION:definition.ref},logRetention:logs.RetentionDays.ONE_WEEK});
  bucket.grantReadWrite(dispatcher,'games/*');bucket.grantWrite(dispatcher,'jobs/*');bucket.grantRead(dispatcher,'code/*');dispatcher.addToRolePolicy(new iam.PolicyStatement({actions:['batch:SubmitJob'],resources:[queue.ref,deepQueue.ref,definition.ref]}));
  const uploadQueue=sqs.Queue.fromQueueArn(this,'UploadQueue',props.analysisQueueArn);dispatcher.addEventSource(new sources.SqsEventSource(uploadQueue,{batchSize:1,maxConcurrency:2,reportBatchItemFailures:true}));
  new CfnOutput(this,'DispatcherName',{value:dispatcher.functionName});
  }
  const status=new lambda.Function(this,'FailureStatus',{runtime:lambda.Runtime.NODEJS_22_X,code:lambda.Code.fromInline(shared+'\n'+fs.readFileSync(path.join(root,'backend/fargate-status.cjs'),'utf8')),handler:'index.handler',timeout:Duration.seconds(15),environment:{LIBRARY_BUCKET:bucket.bucketName},logRetention:logs.RetentionDays.ONE_WEEK});bucket.grantReadWrite(status,'games/*');
  new events.Rule(this,'JobFailure',{eventPattern:{source:['aws.batch'],detailType:['Batch Job State Change'],detail:{status:['FAILED'],jobQueue:[queue.ref,deepQueue.ref]}},targets:[new targets.LambdaFunction(status)]});
  new CfnOutput(this,'JobQueue',{value:queue.ref});new CfnOutput(this,'JobDefinition',{value:definition.ref});new CfnOutput(this,'DeepJobQueue',{value:deepQueue.ref});new CfnOutput(this,'ComputeEnvironment',{value:compute.ref});
 }
}
