// Standalone photo analysis integration, 7 October 2026; AGPL-3.0-only.
import '../../src/site-shell.js';
import {language,t} from '../../src/i18n.js';
import {LocalPositionAI} from './local-ai.js';
import {positionRequest,cloudPosition} from './cloud-api.js';
import {readSgf,parseSgf} from '../vendor/dl/sgf.js';
import {play as playFlat} from '../vendor/dl/engine.js';
import {emptyBoard,coordinate,columns,invalidStones,rotateBoard,rotatePoint,defaultKomi,previewSequence,sequenceSgf} from './position.js';
const $=id=>document.getElementById(id),labels=[...document.querySelectorAll('[data-zh]')].map(el=>({el,en:el.textContent,zh:el.dataset.zh}));
let photo=null,board=emptyBoard(),undo=[],tool='black',editing=false,analysis=null,pinned=null,hovered=null,busy=false,generation=0,client=null,statusMessage=null;
let cloudAbort=null,workTimer=null,photoStarted=null,detectionMs=null,review=new Set();
let frames=[{board:board.slice(),turn:'black',move:null}],cursor=0,autoAnalyse=false;
const localKey='weiqi.local-analysis.v1';let restoring=true;
const finePointer=matchMedia('(hover:hover) and (pointer:fine)');
function message(zh,en,error=false){statusMessage={zh,en,error};$('status').textContent=t(zh,en);$('status').className=error?'error':'';}
function analysisMode(){return $('analysis-mode').value==='browser'?'browser':'cloud';}
function translate(){document.documentElement.lang=language==='zh'?'zh-CN':'en';document.title=t('快速 AI 分析','Quick AI analysis')+' · DL Weiqi';for(const item of labels)item.el.textContent=t(item.zh,item.en);if(statusMessage)$('status').textContent=t(statusMessage.zh,statusMessage.en);renderBoard();if(analysis)renderAnalysis();}
window.addEventListener('site-language-change',translate);
function setBusy(value){busy=value;$('cancel').hidden=!value;for(const el of document.querySelectorAll('#analysis-settings input,#analysis-settings select,#analysis-settings button,#stone-tools button,#edit-stones,#download'))el.disabled=value;$('analysis-mode').disabled=value;$('undo').disabled=value||!undo.length;}
function cancelWork(){generation++;cloudAbort?.abort();cloudAbort=null;clearTimeout(workTimer);workTimer=null;client?.dispose();client=null;setBusy(false);}
$('cancel').onclick=()=>{cancelWork();message('已取消。可调整后重试。','Cancelled. Adjust the position and try again.');};
async function openPhoto(file){
 if(!file)return;cancelWork();review=new Set();const token=generation;let url;photoStarted=performance.now();detectionMs=null;setBusy(true);message('正在上传并自动识别棋盘…','Uploading and automatically detecting the board…');
 try{
  if(file.size>25*1024*1024)throw Error('Use a photo smaller than 25 MB.');url=URL.createObjectURL(file);const image=new Image();image.src=url;await image.decode();if(token!==generation)return;
  if(image.naturalWidth*image.naturalHeight>18000000)throw Error('Use a photo no larger than 18 megapixels.');let edge=3072,blob;
  do{const factor=Math.min(1,edge/Math.max(image.naturalWidth,image.naturalHeight)),c=document.createElement('canvas');c.width=Math.round(image.naturalWidth*factor);c.height=Math.round(image.naturalHeight*factor);c.getContext('2d').drawImage(image,0,0,c.width,c.height);blob=await new Promise(resolve=>c.toBlob(resolve,'image/jpeg',.88));edge=Math.round(edge*.8);}while(blob&&blob.size>1050000&&edge>700);
  if(!blob||blob.size>1050000)throw Error('This photo is too large. Try a smaller image.');const bytes=new Uint8Array(await blob.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));
  cloudAbort=new AbortController();workTimer=setTimeout(()=>cloudAbort?.abort(),30000);const result=await positionRequest('recognize',{image:btoa(binary)},cloudAbort.signal);if(token!==generation)return;clearTimeout(workTimer);workTimer=null;
  board=result.board.split('').map(c=>c==='B'?'black':c==='W'?'white':null);review=new Set((result.review??[]).filter(i=>Number.isInteger(i)&&i>=0&&i<361));detectionMs=performance.now()-photoStarted;frames=[{board:board.slice(),turn:currentSide(),move:null}];cursor=0;undo=[];analysis=null;pinned=null;hovered=null;editing=true;autoAnalyse=false;
  $('board-panel').hidden=false;$('settings').hidden=false;$('photo-panel').hidden=true;$('analysis-panel').hidden=true;renderBoard();message('棋盘已识别，请检查棋子。','Board detected. Check the stones.');setBusy(false);
  if(typeof photo==='string')URL.revokeObjectURL(photo);photo=url;url=null;$('source-photo').src=photo;$('photo-preview').hidden=false;$('photo-preview').open=true;photoStarted=null;
  if(review.size)message('请对照原照片检查棋子，尤其是标出的 '+review.size+' 个点，修正后点击分析。','Compare the stones with the original photo, especially the '+review.size+' highlighted '+(review.size===1?'point':'points')+', correct any errors, then click Analyse position.');
  else message('请对照原照片检查棋子，修正后点击分析。','Compare the stones with the original photo, correct any errors, then click Analyse position.');
 }catch(e){if(token===generation){photoStarted=null;message('识别未完成：'+e.message,'Detection did not finish: '+e.message,true);}}
 finally{if(url)URL.revokeObjectURL(url);if(token===generation){clearTimeout(workTimer);workTimer=null;cloudAbort=null;setBusy(false);renderBoard();}}
}
for(const id of ['photo-file','camera-file'])$(id).onchange=e=>{void openPhoto(e.target.files[0]);e.target.value='';};
$('analysis-mode').value='cloud';$('analysis-mode').onchange=()=>{clearAnalysis();};
const boardElement=$('photo-board'),ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 190 190');svg.setAttribute('aria-hidden','true');for(let i=0;i<19;i++){for(const horizontal of [true,false]){const line=document.createElementNS(ns,'line');for(const [k,v]of Object.entries(horizontal?{x1:5,y1:5+i*10,x2:185,y2:5+i*10}:{x1:5+i*10,y1:5,x2:5+i*10,y2:185}))line.setAttribute(k,v);line.setAttribute('stroke','#65502c');line.setAttribute('stroke-width','.45');svg.append(line);}}for(const y of [3,9,15])for(const x of [3,9,15]){const star=document.createElementNS(ns,'circle');star.setAttribute('cx',5+x*10);star.setAttribute('cy',5+y*10);star.setAttribute('r','1.15');star.setAttribute('fill','#47361f');svg.append(star);}boardElement.append(svg);
const points=Array.from({length:361},(_,i)=>{const b=document.createElement('button');b.className='point';b.type='button';b.style.cssText='left:'+(i%19/19*100)+'%;top:'+(Math.floor(i/19)/19*100)+'%;width:'+100/19+'%;height:'+100/19+'%';b.tabIndex=i===180?0:-1;b.onclick=()=>{if(busy)return;if(editing){const value=tool==='empty'?null:tool;review.delete(i);if(board[i]===value){renderBoard();return;}undo.push(board.slice());if(undo.length>100)undo.shift();board[i]=value;frames=[{board:board.slice(),turn:currentSide(),move:null}];cursor=0;analysis=null;pinned=null;hovered=null;renderBoard();setBusy(false);}else playMove(i);};b.onkeydown=e=>{const d={ArrowLeft:-1,ArrowRight:1,ArrowUp:-19,ArrowDown:19}[e.key];if(!d)return;const target=i+d;if(target<0||target>=361||Math.abs(d)===1&&Math.floor(target/19)!==Math.floor(i/19))return;e.preventDefault();b.tabIndex=-1;points[target].tabIndex=0;points[target].focus();};boardElement.append(b);return b;});
function boardRows(flat){return Array.from({length:19},(_,y)=>flat.slice(y*19,y*19+19));}
function currentSide(){return $('next-player').value;}
function renderBoard(){
 const choice=hovered??pinned,result=choice!==null&&analysis?previewSequence(board,currentSide(),analysis.moves[choice]?.pv):{board,numbers:new Map()},bad=new Set(editing?invalidStones(board):[]);
 for(let i=0;i<361;i++){const b=points[i],colour=result.board[i];b.replaceChildren();b.classList.toggle('invalid',bad.has(i));b.classList.toggle('review',editing&&review.has(i));b.setAttribute('aria-label',coordinate(i)+' · '+(colour==='black'?t('黑子','Black stone'):colour==='white'?t('白子','White stone'):t('空点','Empty intersection'))+(editing&&review.has(i)?' · '+t('请检查','check this point'):''));if(colour){const stone=document.createElement('span');stone.className='stone '+colour;stone.textContent=result.numbers.has(i)?String(result.numbers.get(i)):'';b.append(stone);}else if(analysis&&choice===null){const rank=analysis.moves.findIndex(m=>m.x>=0&&m.y*19+m.x===i);if(rank>=0){const hint=document.createElement('span');hint.className='hint'+(rank?' good':'');hint.textContent=String.fromCharCode(65+rank);b.append(hint);}}}
 $('history-note').hidden=!frames[0].board.some(Boolean)||!['japanese','korean'].includes($('rules').value);$('stone-count').textContent=t('黑子 ','Black ')+board.filter(s=>s==='black').length+' · '+t('白子 ','White ')+board.filter(s=>s==='white').length;
 $('sequence-controls').hidden=editing;$('sequence-previous').disabled=busy||cursor===0;$('sequence-next').disabled=busy||cursor===frames.length-1;$('sequence-pass').disabled=busy;$('sequence-position').textContent=t('第 '+cursor+' 手','Move '+cursor)+' / '+(frames.length-1);$('sequence-pass').textContent=currentSide()==='black'?t('黑方停一手','Black passes'):t('白方停一手','White passes');$('stone-tools').hidden=!editing;$('check-note').hidden=!editing;$('edit-stones').hidden=editing;$('board-title').textContent=editing?t('检查棋子','Check the stones'):t('当前局面','Current position');$('clear-preview').hidden=choice===null;$('play-preview').hidden=choice===null;$('undo').disabled=busy||!undo.length;
 for(const colour of ['black','white','empty'])$('tool-'+colour).setAttribute('aria-pressed',String(tool===colour));
 for(const [i,row] of [...$('suggestions').children].entries())row.classList.toggle('selected',i===choice);
 if(!restoring)saveLocal();
}
for(const colour of ['black','white','empty'])$('tool-'+colour).onclick=()=>{tool=colour;renderBoard();};
$('undo').onclick=()=>{if(busy||!undo.length)return;board=undo.pop();frames=[{board:board.slice(),turn:currentSide(),move:null}];cursor=0;renderBoard();};
$('rotate').onclick=()=>{if(busy)return;undo.push(board.slice());board=rotateBoard(board);review=new Set([...review].map(rotatePoint));frames=[{board:board.slice(),turn:currentSide(),move:null}];cursor=0;renderBoard();};
function clearAnalysis(enterEdit=false){cancelWork();analysis=null;pinned=null;hovered=null;$('analysis-panel').hidden=true;if(enterEdit){editing=true;autoAnalyse=false;frames=[{board:board.slice(),turn:currentSide(),move:null}];cursor=0;undo=[];message('修改后将从此局面开始新的单线棋谱。','Corrections start a new sequence from this position.');}else message('局面设置已更新。','Position settings updated.');renderBoard();}
$('edit-stones').onclick=()=>clearAnalysis(true);
$('new-photo').onclick=()=>{$('photo-panel').hidden=false;$('photo-panel').scrollIntoView({behavior:'smooth'});};
$('rules').onchange=()=>{$('komi').value=String(defaultKomi($('rules').value));clearAnalysis();};
$('next-player').onchange=()=>{frames=frames.slice(0,cursor+1);frames[cursor].turn=currentSide();clearAnalysis();};
$('komi').onchange=()=>clearAnalysis();
function playMove(index){if(busy||editing)return;const wasAuto=autoAnalyse;try{const side=currentSide();let next=board.slice();if(index!==null){const flat=b=>b.map(s=>s==='black'?'B':s==='white'?'W':'.').join('');next=playFlat(flat(board),index,side,19,frames.slice(0,cursor+1).map(f=>flat(f.board))).board.split('').map(s=>s==='B'?'black':s==='W'?'white':null);}clearAnalysis();editing=false;const turn=side==='black'?'white':'black';frames=frames.slice(0,cursor+1);frames.push({board:next,turn,move:{side,index}});cursor++;board=next.slice();$('next-player').value=turn;message('棋步仅保存在本地。','Moves stay local.');renderBoard();if(wasAuto)$('analysis-settings').requestSubmit();}catch(e){message('此处不能落子。请选择空点，并确保落子有气。','This move is illegal. Choose an empty point and ensure the stone has liberties.',true);}}
function navigate(offset){if(busy||editing)return;const next=Math.max(0,Math.min(frames.length-1,cursor+offset));if(next===cursor)return;const wasAuto=autoAnalyse;clearAnalysis();cursor=next;board=frames[cursor].board.slice();$('next-player').value=frames[cursor].turn;renderBoard();if(wasAuto)$('analysis-settings').requestSubmit();}
$('sequence-previous').onclick=()=>navigate(-1);$('sequence-next').onclick=()=>navigate(1);$('sequence-pass').onclick=()=>playMove(null);
$('play-preview').onclick=()=>{const i=hovered??pinned,m=analysis?.moves[i];if(m)playMove(m.x<0?null:m.y*19+m.x);};
$('sgf-file').onchange=async event=>{const file=event.target.files[0];event.target.value='';if(!file)return;cancelWork();review=new Set();const token=generation;try{if(file.size>256*1024)throw Error('Use an SGF no larger than 256 KB.');const text=new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer()),record=readSgf(text),root=parseSgf(text).nodes[0];if(record.size!==19)throw Error('Use a 19 × 19 SGF.');photoStarted=null;detectionMs=null;if(token!==generation)return;frames=record.mainLine.map(id=>{const n=record.nodes[id];return {board:n.board.split('').map(s=>s==='B'?'black':s==='W'?'white':null),turn:n.turn==='B'?'black':'white',move:n.move?{side:n.move.side==='B'?'black':'white',index:n.move.index}:null};});cursor=frames.length-1;board=frames[cursor].board.slice();$('next-player').value=frames[cursor].turn;const name=record.rules.toLowerCase(),rule=['chinese','aga','korean','japanese'].find(r=>name.includes(r))||'japanese';$('rules').value=rule;$('komi').value=String(root.KM?record.komi:defaultKomi(rule));editing=false;autoAnalyse=false;analysis=null;pinned=null;hovered=null;undo=[];$('board-panel').hidden=false;$('settings').hidden=false;$('analysis-panel').hidden=true;$('photo-panel').hidden=true;if(typeof photo==='string')URL.revokeObjectURL(photo);photo=null;$('photo-preview').hidden=true;$('source-photo').removeAttribute('src');message('已打开本地 SGF，保留其主线。','Local SGF opened; only its main sequence is kept.');renderBoard();}catch(e){if(token===generation)message('无法打开 SGF：'+e.message,'Cannot open SGF: '+e.message,true);}};
$('download').onclick=()=>{const url=URL.createObjectURL(new Blob([sequenceSgf(frames,{rules:$('rules').value,komi:Number($('komi').value)})],{type:'application/x-go-sgf'}));const a=document.createElement('a');a.href=url;a.download='local-analysis.sgf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('analysis-settings').onsubmit=async event=>{event.preventDefault();if(busy||!$('analysis-settings').reportValidity())return;const bad=invalidStones(board);if(bad.length){message('这些棋子没有气，请先修正：'+bad.map(coordinate).join(', '),'These stones have no liberties. Correct them first: '+bad.map(coordinate).join(', '),true);renderBoard();return;}
 const token=++generation,started=performance.now(),mode=analysisMode();setBusy(true);message(mode==='cloud'?'正在云端分析当前局面…':'正在加载并运行浏览器 AI…',mode==='cloud'?'Analysing the position in the cloud…':'Loading and running browser AI…');
 workTimer=setTimeout(()=>{if(token===generation){cancelWork();message('分析超时，请重试或切换模式。','Analysis timed out. Try again or switch modes.',true);}},Math.max(1000,120000-(photoStarted===null?0:performance.now()-photoStarted)));
 try{let result;if(mode==='cloud'){cloudAbort=new AbortController();result=await positionRequest('analyze',cloudPosition(frames,cursor,currentSide(),$('rules').value,Number($('komi').value)),cloudAbort.signal);}else{client??=new LocalPositionAI();result=await client.analyze({frames,cursor,side:currentSide(),komi:Number($('komi').value),rules:$('rules').value});}
  if(token!==generation)return;analysis={...result,elapsedMs:performance.now()-started,mode,detectionMs,totalMs:photoStarted===null?null:performance.now()-photoStarted};photoStarted=null;autoAnalyse=true;editing=false;pinned=null;hovered=null;$('analysis-panel').hidden=false;message('分析完成。选择推荐着法查看后续变化。','Analysis complete. Select a suggested move to see its continuation.');renderAnalysis();renderBoard();$('analysis-panel').scrollIntoView({behavior:'smooth',block:'start'});
 }catch(e){if(token===generation){client?.dispose();client=null;photoStarted=null;message('分析未完成，可重试：'+e.message,'Analysis did not finish. You can retry: '+e.message,true);}}
 finally{if(token===generation){clearTimeout(workTimer);workTimer=null;cloudAbort=null;setBusy(false);renderBoard();}}
};
function badge(value,colour){const span=document.createElement('span');span.className='badge '+colour;span.textContent=value;return span;}
function leadBadge(value){return badge(Math.abs(value).toFixed(1),value>=0?'black':'white');}
function winBadges(black){const wrap=document.createElement('span');wrap.className='wins';const value=Math.max(0,Math.min(1,black));const b=badge((value*100).toFixed(1),'black'),w=badge(((1-value)*100).toFixed(1),'white');b.setAttribute('aria-label',t('黑方胜率 ','Black win ')+b.textContent+'%');w.setAttribute('aria-label',t('白方胜率 ','White win ')+w.textContent+'%');wrap.append(b,w);return wrap;}
function togglePreview(i){hovered=null;pinned=pinned===i?null:i;renderBoard();}
function renderAnalysis(){if(!analysis)return;
 const lead=analysis.rootScoreLead;$('lead').replaceChildren(document.createTextNode(t(lead>=0?'黑方约领先 ':'白方约领先 ',lead>=0?'Black leads by ≈ ':'White leads by ≈ ')),leadBadge(lead),document.createTextNode(t(' 目',' points')));$('probabilities').replaceChildren(document.createTextNode(t('黑方 / 白方胜率','Black / White win probability')),winBadges(analysis.rootWinRate));$('analysis-time').textContent=t('粗略分析 · ','Rough analysis · ')+(analysis.elapsedMs/1000).toFixed(2)+' s · '+analysis.rootVisits+t(' 次访问',' visits')+' · '+(analysis.mode==='cloud'?t('云端 AI','Cloud AI'):t('浏览器 AI','Browser AI'))+(analysis.totalMs===null?'':t(' · 照片至结果 ',' · Photo to result ')+(analysis.totalMs/1000).toFixed(2)+' s');$('suggestions').replaceChildren();analysis.moves.forEach((m,i)=>{const row=document.createElement('tr'),moveCell=document.createElement('td'),button=document.createElement('button');button.className='pick';const move=m.x<0?t('停一手','Pass'):columns[m.x]+(19-m.y);button.textContent=String.fromCharCode(65+i)+' · '+move;button.onclick=()=>togglePreview(i);button.onfocus=()=>{hovered=i;renderBoard();};button.onblur=()=>{hovered=null;renderBoard();};moveCell.append(button);const evaluation=document.createElement('td'),loss=m.relativePointsLost??m.pointsLost;let label=i===0?t('最佳着法','Best move'):loss<.5?t('好棋','Good'):loss<2?t('不精确','Inaccuracy'):loss<5?t('失误','Mistake'):t('严重失误','Blunder');evaluation.textContent=label;evaluation.className='evaluation';const score=document.createElement('td'),wins=document.createElement('td');score.append(leadBadge(m.scoreLead));wins.append(winBadges(m.winRate));row.append(moveCell,evaluation,score,wins);row.onpointerenter=e=>{if(finePointer.matches&&e.pointerType==='mouse'){hovered=i;renderBoard();}};row.onpointerleave=()=>{hovered=null;renderBoard();};row.onclick=e=>{if(!e.target.closest('button'))togglePreview(i);};$('suggestions').append(row);});
}
$('clear-preview').onclick=()=>{pinned=null;hovered=null;renderBoard();};
function saveLocal(){try{localStorage.setItem(localKey,JSON.stringify({sgf:sequenceSgf(frames,{rules:$('rules').value,komi:Number($('komi').value)}),cursor,side:currentSide(),editing}));$('local-save').textContent=t('仅保存在此浏览器中，刷新后可恢复。','Saved only in this browser; restored after refresh.');}catch{$('local-save').textContent=t('无法在浏览器中保存，请下载 SGF 保留棋谱。','Browser storage is unavailable. Download SGF to keep this game.');}}
function restoreLocal(){try{const saved=JSON.parse(localStorage.getItem(localKey)||'null');if(!saved)return;const record=readSgf(saved.sgf);frames=record.mainLine.map(id=>{const n=record.nodes[id];return {board:n.board.split('').map(s=>s==='B'?'black':s==='W'?'white':null),turn:n.turn==='B'?'black':'white',move:n.move?{side:n.move.side==='B'?'black':'white',index:n.move.index}:null};});cursor=Math.max(0,Math.min(frames.length-1,Number.isInteger(saved.cursor)?saved.cursor:frames.length-1));board=frames[cursor].board.slice();$('next-player').value=['black','white'].includes(saved.side)?saved.side:frames[cursor].turn;frames[cursor].turn=currentSide();$('rules').value=['japanese','chinese','korean','aga'].includes(record.rules)?record.rules:'japanese';$('komi').value=String(record.komi);editing=Boolean(saved.editing);message('已恢复此浏览器中的本地棋谱。','Restored the local game saved in this browser.');}catch{message('无法恢复本地棋谱，请重新打开 SGF 或照片。','Could not restore the local game. Open an SGF or photo again.',true);}}
window.addEventListener('pagehide',()=>{cancelWork();if(typeof photo==='string')URL.revokeObjectURL(photo);});restoreLocal();restoring=false;translate();
