import {gamePrefix} from '../backend/library-service.js';
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import {createHash,randomUUID} from 'node:crypto';
function harness(){const id='2026100601',files=new Map([[gamePrefix(id)+'/metadata.json',JSON.stringify({id,moves:2,analysis:{status:'queued'}})],[gamePrefix(id)+'/original.sgf','(;SZ[19];B[dd];W[pp])']]),submitted=[],messages=[],cancelled=[];let failModel=false,lostResponse=false,startDuringCancel=false,slowCancel=false,listMisses=0;const statuses=new Map();let etag=1;
 class GetObjectCommand{constructor(input){this.input=input;}}class PutObjectCommand{constructor(input){this.input=input;}}class SubmitJobCommand{constructor(input){this.input=input;}}class DescribeJobsCommand{constructor(input){this.input=input;}}class ListJobsCommand{constructor(input){this.input=input;}}class CancelJobCommand{constructor(input){this.input=input;}}class SendMessageCommand{constructor(input){this.input=input;}}
 class S3Client{async send(c){if(c instanceof GetObjectCommand){if(!files.has(c.input.Key))throw Object.assign(Error(),{name:'NoSuchKey'});return {ETag:String(etag),Body:{transformToString:async()=>files.get(c.input.Key)}};}assert.equal(c.input.IfMatch===undefined||c.input.IfMatch===String(etag),true);etag++;files.set(c.input.Key,c.input.Body);return {};}}
 class BatchClient{async send(c){if(c instanceof DescribeJobsCommand)return {jobs:c.input.jobs.map(jobId=>({jobId,status:statuses.get(jobId)||'RUNNABLE'}))};if(c instanceof ListJobsCommand){if(listMisses>0){listMisses--;return {jobSummaryList:[]};}return {jobSummaryList:submitted.filter(j=>j.jobName===c.input.filters[0].values[0])};}if(c instanceof CancelJobCommand){cancelled.push(c.input.jobId);if(!slowCancel)statuses.set(c.input.jobId,startDuringCancel?'RUNNING':'FAILED');return {};}const job={...c.input,jobId:'job-'+(submitted.length+1)};submitted.push(job);if(lostResponse&&new RegExp('-'+lostResponse+'\\d+-').test(job.jobName)){lostResponse=false;throw Error('Lost HTTP reply');}return {jobId:job.jobId};}}
 class SQSClient{async send(c){messages.push(c.input);return {};}}
 const exports={},source=['src/engine.js','src/sgf.js','backend/library-service.js','backend/gpu-production.cjs'].map(f=>readFileSync(new URL('../'+f,import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace(/^export /gm,'')).join('\n');
 vm.runInNewContext(source,{exports,TextEncoder,Date,require:n=>n.includes('client-s3')?{S3Client,GetObjectCommand,PutObjectCommand}:n.includes('client-batch')?{BatchClient,SubmitJobCommand,DescribeJobsCommand,ListJobsCommand,CancelJobCommand}:n.includes('client-sqs')?{SQSClient,SendMessageCommand}:{createHash,randomUUID},process:{env:{LIBRARY_BUCKET:'library',AI_CONTROL_KEY:'control/ai-spending.json',JOB_QUEUE:'a10',FALLBACK_GPU_QUEUE:'t4-demand',JOB_DEFINITION:'gpu-only',CONTROL_QUEUE:'control',DEEP_VISITS:'3000'}},console:{error(){}},resolveAnalysisModel:async()=>{if(failModel)throw Error('Offline');return {key:'models/latest.bin.gz',url:'https://media.katagotraining.org/uploaded/networks/models/kata1/latest.bin.gz'};}});
 const state=()=>JSON.parse(files.get(gamePrefix(id)+'/metadata.json')).analysis,set=fn=>{const m=JSON.parse(files.get(gamePrefix(id)+'/metadata.json'));fn(m.analysis);files.set(gamePrefix(id)+'/metadata.json',JSON.stringify(m));};
 const main=()=>submitted.filter(j=>/-a\d+-/.test(j.jobName)),quick=()=>submitted.filter(j=>/-q\d+-/.test(j.jobName)),request=token=>JSON.parse(files.get('jobs/'+id+'/'+token+'-request.json')),fail=job=>exports.handler({detail:{status:'FAILED',jobName:job.jobName,jobId:job.jobId}});
 return {id,files,state,set,submitted,main,quick,request,messages,cancelled,statuses,modelFailure:()=>failModel=true,loseReply:(kind='a')=>lostResponse=kind,cancelRace:()=>startDuringCancel=true,slowCancel:()=>slowCancel=true,listMiss:n=>listMisses=n,call:b=>exports.handler({Records:[{messageId:randomUUID(),body:JSON.stringify({id,...b}),attributes:{ApproximateReceiveCount:'1'}}]}),fail,failed:()=>fail(main().at(-1))};
}
test('quick starts at once on its own T4 On-Demand worker, deep on A10G, and duplicate messages launch no paid duplicates',async()=>{const h=harness();await h.call({});await h.call({});assert.equal(h.submitted.length,2);assert.equal(h.quick().length,1);assert.equal(h.quick()[0].jobQueue,'t4-demand');assert.equal(h.main()[0].jobQueue,'a10');const s=h.state(),q=h.request(s.quickJob.token),req=h.request(s.token);assert.equal(q.role,'quick');assert.deepEqual(Object.keys(q.phases),['quick']);assert.equal(q.phases.quick.visits,32);assert.equal(q.compute.gpu,'NVIDIA T4');assert.equal(q.compute.purchaseOption,'On-Demand');assert.equal(req.pipeline,true);assert.equal(req.role,undefined);assert.equal(req.phases.quick.visits,32);assert.equal(req.phases.deep.visits,3000);assert.equal(req.compute.gpu,'NVIDIA A10G');assert.equal(req.phases.deep.estimatedSeconds,Math.ceil(20+3*3000/1000));assert.equal(h.state().deep.visits,3000);assert.deepEqual(h.messages.map(m=>[JSON.parse(m.MessageBody).kind,m.DelaySeconds]),[['quick-watch',60],['watch',180]]);});
test('a quick-only game (deep limit reached) runs one T4 quick job, keeps deep limited on retries and failure',async()=>{const h=harness();h.set(a=>a.deep={status:'limited',dailyLimit:10});await h.call({});await h.call({});assert.equal(h.submitted.length,1);assert.equal(h.quick().length,0);assert.equal(h.main()[0].jobQueue,'t4-demand');const s=h.state(),req=h.request(s.token);assert.deepEqual(Object.keys(req.phases),['quick']);assert.equal(req.compute.gpu,'NVIDIA T4');assert.equal(s.quickJob,undefined);assert.deepEqual(s.deep,{status:'limited',dailyLimit:10});assert.equal(s.quick.status,'queued');
 for(let attempt=1;attempt<=3;attempt++){await h.failed();await h.failed();assert.equal(h.state().deep.status,'limited');if(attempt<3){h.set(a=>a.retryAt='2000-01-01T00:00:00Z');await h.call({kind:'retry',attempt});assert.equal(h.main().at(-1).jobQueue,'t4-demand');assert.deepEqual(Object.keys(h.request(h.state().token).phases),['quick']);}}
 assert.equal(h.state().status,'failed');assert.equal(h.state().quick.status,'failed');assert.equal(h.quick().length,0);});
test('failures schedule exactly two later attempts on alternating On-Demand GPUs and preserve quick results and the original timing origin',async()=>{const h=harness();await h.call({});const origin=h.state().enqueuedAt;h.set(s=>{s.quick.status='ready';s.available='quick';});for(let attempt=1;attempt<=3;attempt++){await h.failed();await h.failed();assert.equal(h.state().attempt,attempt);if(attempt<3){assert.equal(h.state().status,'retry_wait');const delay=h.messages.at(-1).DelaySeconds;assert.ok(Math.abs(delay-[300,900][attempt-1])<=1);h.set(s=>s.retryAt='2000-01-01T00:00:00Z');await h.call({kind:'retry',attempt});await h.call({kind:'retry',attempt});assert.equal(h.main().length,attempt+1);assert.equal(h.main().at(-1).jobQueue,attempt===1?'t4-demand':'a10');assert.equal(h.quick().length,1);assert.equal(h.state().quick.status,'ready');}else{assert.equal(h.state().status,'failed');assert.equal(h.state().retryAt,undefined);}}assert.equal(h.state().enqueuedAt,origin);assert.equal(h.state().retriesUsed,2);assert.equal(h.files.get(gamePrefix(h.id)+'/original.sgf'),'(;SZ[19];B[dd];W[pp])');assert.ok(h.submitted.every(j=>j.jobQueue!=='spot'));});
test('capacity fallback confirms cancellation, moves deep to T4 On-Demand and then bounds prolonged queue failure',async()=>{const h=harness();await h.call({});const s=h.state();await h.call({kind:'watch',token:s.token,jobId:s.jobId});assert.deepEqual(h.cancelled,[s.jobId]);assert.equal(h.main().length,2);assert.equal(h.main()[1].jobQueue,'t4-demand');assert.equal(h.state().capacityFallback,true);assert.equal(h.state().attempt,1);const t4=h.request(h.state().token);assert.equal(t4.compute.gpu,'NVIDIA T4');assert.equal(t4.compute.purchaseOption,'On-Demand');assert.equal(t4.phases.deep.visits,3000);assert.equal(t4.phases.deep.estimatedSeconds,Math.ceil(20+3*3*3000/1000));await h.call({kind:'watch',token:s.token,jobId:s.jobId});assert.equal(h.main().length,2);h.set(a=>a.submitAt='2000-01-01T00:00:00Z');const late=h.state();await h.call({kind:'watch',token:late.token,jobId:late.jobId});assert.equal(h.state().status,'retry_wait');assert.match(h.state().error,/capacity/);assert.equal(h.main().length,2);assert.equal(h.messages.at(-1).DelaySeconds,300);});
test('a running quick worker does not block the deep capacity fallback and keeps its claim',async()=>{const h=harness();await h.call({});h.set(a=>{a.quick={...a.quick,status:'running',owner:a.quickJob.token};a.status='running';});const s=h.state();await h.call({kind:'watch',token:s.token,jobId:s.jobId});assert.equal(h.main().length,2);assert.equal(h.main()[1].jobQueue,'t4-demand');assert.equal(h.state().quick.status,'running');assert.equal(h.state().quick.owner,s.quickJob.token);assert.equal(h.state().status,'running');});
test('a deep worker that claimed a phase is never replaced by capacity fallback',async()=>{const h=harness();await h.call({});h.set(a=>{a.quick={...a.quick,status:'running',owner:a.token};a.status='running';});const s=h.state();await h.call({kind:'watch',token:s.token,jobId:s.jobId});assert.equal(h.main().length,1);assert.equal(h.cancelled.length,0);});
test('a GPU worker starting during cancellation is retained without a second job',async()=>{const h=harness();h.cancelRace();await h.call({});const s=h.state();await h.call({kind:'watch',token:s.token,jobId:s.jobId});assert.equal(h.main().length,1);await h.call({kind:'watch',token:s.token,jobId:s.jobId});assert.equal(h.main().length,1);});
test('lost SubmitJob reply recovers the same job by name instead of submitting twice',async()=>{const h=harness();h.loseReply('a');assert.equal((await h.call({})).batchItemFailures.length,1);await h.call({});assert.equal(h.main().length,1);assert.equal(h.quick().length,1);assert.equal(h.state().jobId,h.main()[0].jobId);const q=harness();q.loseReply('q');assert.equal((await q.call({})).batchItemFailures.length,0);assert.equal(q.main().length,1);await q.call({});assert.equal(q.quick().length,1);assert.equal(q.state().quickJob.jobId,q.quick()[0].jobId);});
test('latest-model lookup failure is visible, schedules a retry and never uses a cached model',async()=>{const h=harness();h.modelFailure();await h.call({});assert.equal(h.state().status,'retry_wait');assert.ok(h.state().error);assert.ok(h.state().retryAt);assert.equal(h.submitted.length,0);assert.equal(h.state().model,undefined);});
test('a queued quick job keeps waiting while useful, then is cancelled once deep claims quick or after 15 minutes',async()=>{
 const h=harness();await h.call({});let s=h.state();await h.call({kind:'quick-watch',token:s.quickJob.token,jobId:s.quickJob.jobId});assert.equal(h.cancelled.length,0);assert.equal(JSON.parse(h.messages.at(-1).MessageBody).kind,'quick-watch');
 h.set(a=>{a.quick={...a.quick,status:'running',owner:a.token};});await h.call({kind:'quick-watch',token:s.quickJob.token,jobId:s.quickJob.jobId});assert.deepEqual(h.cancelled,[s.quickJob.jobId]);
 const late=harness();await late.call({});late.set(a=>a.quickJob.submitAt='2000-01-01T00:00:00Z');s=late.state();await late.call({kind:'quick-watch',token:s.quickJob.token,jobId:s.quickJob.jobId});assert.deepEqual(late.cancelled,[s.quickJob.jobId]);await late.fail(late.quick()[0]);assert.equal(late.state().status,'queued');assert.equal(late.state().attempt,1);
 const started=harness();await started.call({});s=started.state();started.statuses.set(s.quickJob.jobId,'RUNNING');const before=started.messages.length;await started.call({kind:'quick-watch',token:s.quickJob.token,jobId:s.quickJob.jobId});assert.equal(started.cancelled.length,0);assert.equal(started.messages.length,before);
});
test('a failed quick worker releases its claim and never fails or retries the game',async()=>{const h=harness();await h.call({});h.set(a=>{a.quick={...a.quick,status:'running',owner:a.quickJob.token};a.status='running';});await h.fail(h.quick()[0]);const s=h.state();assert.equal(s.quick.status,'queued');assert.equal(s.quick.owner,null);assert.equal(s.status,'queued');assert.equal(s.attempt,1);assert.equal(s.error,undefined);assert.equal(h.main().length,1);});
test('a retry submits a fresh quick job when quick is not ready and the old one loses ownership',async()=>{const h=harness();await h.call({});const old=h.state().quickJob;await h.failed();assert.equal(h.state().status,'retry_wait');await h.call({kind:'quick-watch',token:old.token,jobId:old.jobId});assert.deepEqual(h.cancelled,[old.jobId]);h.set(s=>s.retryAt='2000-01-01T00:00:00Z');await h.call({kind:'retry',attempt:1});assert.equal(h.quick().length,2);assert.match(h.quick()[1].jobName,/-q2-/);assert.notEqual(h.state().quickJob.token,old.token);assert.equal(h.state().quick.status,'queued');});
test('a cancellation confirmed on a later check still moves deep to T4 and does not use a retry',async()=>{
 const h=harness();h.slowCancel();await h.call({});const s=h.state();await h.call({kind:'watch',token:s.token,jobId:s.jobId});assert.deepEqual(h.cancelled,[s.jobId]);assert.equal(h.main().length,1);
 h.statuses.set(s.jobId,'FAILED');await h.fail(h.main()[0]);assert.equal(h.state().status,'queued');assert.equal(h.main().length,2);assert.equal(h.main()[1].jobQueue,'t4-demand');assert.equal(h.state().attempt,1);assert.equal(h.state().error,undefined);
 await h.call({kind:'watch',token:s.token,jobId:s.jobId});assert.equal(h.main().length,2);
 const late=harness();late.slowCancel();await late.call({});let a=late.state();await late.call({kind:'watch',token:a.token,jobId:a.jobId});late.statuses.set(a.jobId,'FAILED');await late.call({kind:'watch',token:a.token,jobId:a.jobId});assert.equal(late.main().length,2);a=late.state();assert.equal(a.backend,'fallback-demand');
 late.set(x=>x.submitAt='2000-01-01T00:00:00Z');await late.call({kind:'watch',token:a.token,jobId:a.jobId});assert.equal(late.state().status,'queued');late.statuses.set(a.jobId,'FAILED');await late.call({kind:'watch',token:a.token,jobId:a.jobId});assert.equal(late.state().status,'retry_wait');assert.match(late.state().error,/capacity/);
 const ran=harness();ran.slowCancel();await ran.call({});a=ran.state();await ran.call({kind:'watch',token:a.token,jobId:a.jobId});ran.set(x=>{x.deep={...x.deep,status:'running',owner:x.token};x.status='running';});ran.statuses.set(a.jobId,'FAILED');await ran.fail(ran.main()[0]);assert.equal(ran.state().status,'retry_wait');assert.equal(ran.main().length,1);assert.doesNotMatch(ran.state().error,/capacity/);
});
test('a quick job whose submission reply and lookup are both lost is still found by name and cancelled when unneeded',async()=>{
 const h=harness();h.loseReply('q');h.listMiss(1);await h.call({});assert.equal(h.quick().length,1);assert.equal(h.state().quickJob.jobId,undefined);
 const watch=h.messages.map(m=>JSON.parse(m.MessageBody)).find(b=>b.kind==='quick-watch');assert.equal(watch.jobId,undefined);assert.equal(watch.jobName,h.quick()[0].jobName);
 h.set(a=>{a.quick={...a.quick,status:'running',owner:a.token};});await h.call(watch);assert.equal(h.state().quickJob.jobId,h.quick()[0].jobId);assert.deepEqual(h.cancelled,[h.quick()[0].jobId]);
});
test('a legacy completed record cannot be reanalysed by an old delayed message',async()=>{const h=harness();h.set(s=>s.status='ready');await h.call({});assert.equal(h.submitted.length,0);});
test('a monthly budget pause blocks initial dispatch, failure retries and delayed capacity messages',async()=>{
 const h=harness();h.files.set('control/ai-spending.json',JSON.stringify({paused:true}));await h.call({});assert.equal(h.submitted.length,0);assert.equal(h.messages.length,0);assert.equal(h.state().status,'paused');
 const running=harness();await running.call({});const s=running.state();running.set(a=>{a.quick.status='ready';a.available='quick';});running.files.set('control/ai-spending.json',JSON.stringify({paused:true}));await running.failed();await running.call({kind:'watch',token:s.token,jobId:s.jobId});assert.equal(running.submitted.length,2);assert.equal(running.messages.length,2);assert.equal(running.state().status,'paused');assert.equal(running.state().quick.status,'ready');running.files.set('control/ai-spending.json',JSON.stringify({paused:false}));await running.call({});await running.failed();await running.call({kind:'watch',token:s.token,jobId:s.jobId});assert.equal(running.submitted.length,2);assert.equal(running.messages.length,2);
});

test('long games reduce deep visits to stay within the measured full-game processing envelope',async()=>{
 const h=harness();h.files.set(gamePrefix(h.id)+'/original.sgf','(;SZ[19]'+Array.from({length:1999},(_,n)=>';'+(n%2?'W':'B')+'[]').join('')+')');await h.call({});const req=h.request(h.state().token);assert.equal(req.phases.deep.visits,483);assert.ok(req.phases.deep.estimatedSeconds<=4000);assert.equal(req.phases.quick.visits,32);const s=h.state();await h.call({kind:'watch',token:s.token,jobId:s.jobId});const t4=h.request(h.state().token);assert.equal(t4.phases.deep.visits,483);assert.ok(t4.phases.deep.estimatedSeconds<=5000);
});
