import {gamePrefix} from '../backend/library-service.js';
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import {createHash,randomUUID} from 'node:crypto';
function harness(){const id='2026100601',files=new Map([[gamePrefix(id)+'/metadata.json',JSON.stringify({id,moves:2,analysis:{status:'queued'}})],[gamePrefix(id)+'/original.sgf','(;SZ[19];B[dd];W[pp])']]),submitted=[],messages=[],cancelled=[];let failModel=false,lostResponse=false,startDuringCancel=false;const statuses=new Map();let etag=1;
 class GetObjectCommand{constructor(input){this.input=input;}}class PutObjectCommand{constructor(input){this.input=input;}}class SubmitJobCommand{constructor(input){this.input=input;}}class DescribeJobsCommand{constructor(input){this.input=input;}}class ListJobsCommand{constructor(input){this.input=input;}}class CancelJobCommand{constructor(input){this.input=input;}}class SendMessageCommand{constructor(input){this.input=input;}}
 class S3Client{async send(c){if(c instanceof GetObjectCommand){if(!files.has(c.input.Key))throw Object.assign(Error(),{name:'NoSuchKey'});return {ETag:String(etag),Body:{transformToString:async()=>files.get(c.input.Key)}};}assert.equal(c.input.IfMatch===undefined||c.input.IfMatch===String(etag),true);etag++;files.set(c.input.Key,c.input.Body);return {};}}
 class BatchClient{async send(c){if(c instanceof DescribeJobsCommand)return {jobs:c.input.jobs.map(jobId=>({jobId,status:statuses.get(jobId)||'RUNNABLE'}))};if(c instanceof ListJobsCommand)return {jobSummaryList:submitted.filter(j=>j.jobName===c.input.filters[0].values[0])};if(c instanceof CancelJobCommand){cancelled.push(c.input.jobId);statuses.set(c.input.jobId,startDuringCancel?'RUNNING':'FAILED');return {};}const job={...c.input,jobId:'job-'+(submitted.length+1)};submitted.push(job);if(lostResponse){lostResponse=false;throw Error('Lost HTTP reply');}return {jobId:job.jobId};}}
 class SQSClient{async send(c){messages.push(c.input);return {};}}
 const exports={},source=['src/engine.js','src/sgf.js','backend/library-service.js','backend/gpu-production.cjs'].map(f=>readFileSync(new URL('../'+f,import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace(/^export /gm,'')).join('\n');
 vm.runInNewContext(source,{exports,TextEncoder,Date,require:n=>n.includes('client-s3')?{S3Client,GetObjectCommand,PutObjectCommand}:n.includes('client-batch')?{BatchClient,SubmitJobCommand,DescribeJobsCommand,ListJobsCommand,CancelJobCommand}:n.includes('client-sqs')?{SQSClient,SendMessageCommand}:{createHash,randomUUID},process:{env:{LIBRARY_BUCKET:'library',AI_CONTROL_KEY:'control/ai-spending.json',JOB_QUEUE:'a10',FALLBACK_GPU_QUEUE:'t4-demand',FALLBACK_SPOT_QUEUE:'spot',JOB_DEFINITION:'gpu-only',CONTROL_QUEUE:'control',DEEP_VISITS:'3000'}},console:{error(){}},resolveAnalysisModel:async()=>{if(failModel)throw Error('Offline');return {key:'models/latest.bin.gz',url:'https://media.katagotraining.org/uploaded/networks/models/kata1/latest.bin.gz'};}});
 const state=()=>JSON.parse(files.get(gamePrefix(id)+'/metadata.json')).analysis,set=fn=>{const m=JSON.parse(files.get(gamePrefix(id)+'/metadata.json'));fn(m.analysis);files.set(gamePrefix(id)+'/metadata.json',JSON.stringify(m));};
 return {id,files,state,set,submitted,messages,cancelled,statuses,modelFailure:()=>failModel=true,loseReply:()=>lostResponse=true,cancelRace:()=>startDuringCancel=true,call:b=>exports.handler({Records:[{messageId:randomUUID(),body:JSON.stringify({id,...b}),attributes:{ApproximateReceiveCount:'1'}}]}),failed:()=>exports.handler({detail:{status:'FAILED',jobName:submitted.at(-1).jobName,jobId:submitted.at(-1).jobId}})};
}
test('one GPU job contains both passes and duplicate upload messages do not launch paid duplicates',async()=>{const h=harness();await h.call({});await h.call({});assert.equal(h.submitted.length,1);assert.equal(h.submitted[0].jobQueue,'a10');const req=JSON.parse([...h.files].find(([k])=>k.startsWith('jobs/'))[1]);assert.equal(req.pipeline,true);assert.equal(req.phases.quick.visits,32);assert.equal(req.phases.deep.visits,3000);assert.equal(req.compute.backend,'gpu');assert.equal(req.compute.gpu,'NVIDIA A10G');assert.equal(req.phases.deep.estimatedSeconds,Math.ceil(20+3*3000/1000));assert.equal(h.state().deep.visits,3000);assert.equal(h.messages.length,1);});
test('failures schedule exactly two later attempts and preserve quick results and the original timing origin',async()=>{const h=harness();await h.call({});const origin=h.state().enqueuedAt;h.set(s=>{s.quick.status='ready';s.available='quick';});for(let attempt=1;attempt<=3;attempt++){await h.failed();await h.failed();assert.equal(h.state().attempt,attempt);if(attempt<3){assert.equal(h.state().status,'retry_wait');const delay=h.messages.at(-1).DelaySeconds;assert.ok(Math.abs(delay-[300,900][attempt-1])<=1);h.set(s=>s.retryAt='2000-01-01T00:00:00Z');await h.call({kind:'retry',attempt});await h.call({kind:'retry',attempt});assert.equal(h.submitted.length,attempt+1);assert.equal(h.submitted.at(-1).jobQueue,attempt===1?'spot':'a10');assert.equal(h.state().quick.status,'ready');}else{assert.equal(h.state().status,'failed');assert.equal(h.state().retryAt,undefined);}}assert.equal(h.state().enqueuedAt,origin);assert.equal(h.state().retriesUsed,2);assert.equal(h.files.get(gamePrefix(h.id)+'/original.sgf'),'(;SZ[19];B[dd];W[pp])');});
test('capacity fallback confirms cancellation and uses only the independent T4/A10G Spot GPU pool',async()=>{const h=harness();await h.call({});const s=h.state();await h.call({kind:'watch',token:s.token,jobId:s.jobId});assert.equal(h.cancelled.length,1);assert.equal(h.submitted.length,2);assert.equal(h.submitted[1].jobQueue,'spot');assert.equal(h.state().capacityFallback,true);assert.equal(h.state().attempt,1);const req=JSON.parse([...h.files].filter(([k])=>k.startsWith('jobs/')).at(-1)[1]);assert.equal(req.phases.deep.visits,3000);assert.equal(req.compute.gpu,'T4 / A10G capacity pool');await h.call({kind:'watch',token:s.token,jobId:s.jobId});assert.equal(h.submitted.length,2);});
test('a GPU worker starting during cancellation is retained without a second job',async()=>{const h=harness();h.cancelRace();await h.call({});const s=h.state();await h.call({kind:'watch',token:s.token,jobId:s.jobId});assert.equal(h.submitted.length,1);await h.call({kind:'watch',token:s.token,jobId:s.jobId});assert.equal(h.submitted.length,1);});
test('lost SubmitJob reply recovers the same job by name instead of submitting twice',async()=>{const h=harness();h.loseReply();assert.equal((await h.call({})).batchItemFailures.length,1);await h.call({});assert.equal(h.submitted.length,1);assert.equal(h.state().jobId,'job-1');});
test('latest-model lookup failure is visible, schedules a retry and never uses a cached model',async()=>{const h=harness();h.modelFailure();await h.call({});assert.equal(h.state().status,'retry_wait');assert.ok(h.state().error);assert.ok(h.state().retryAt);assert.equal(h.submitted.length,0);assert.equal(h.state().model,undefined);});

test('Spot capacity fallback switches to T4 On-Demand, then bounds prolonged queue failure',async()=>{const h=harness();await h.call({});const first=h.state();await h.call({kind:'watch',token:first.token,jobId:first.jobId});const spot=h.state();await h.call({kind:'watch',token:spot.token,jobId:spot.jobId});assert.equal(h.submitted.length,3);assert.equal(h.submitted[2].jobQueue,'t4-demand');const t4=JSON.parse([...h.files].filter(([k])=>k.startsWith('jobs/')).at(-1)[1]);assert.equal(t4.compute.gpu,'NVIDIA T4');assert.equal(t4.phases.deep.visits,3000);assert.equal(t4.phases.deep.estimatedSeconds,Math.ceil(20+3*3*3000/1000));h.set(s=>s.submitAt='2000-01-01T00:00:00Z');const s=h.state();await h.call({kind:'watch',token:s.token,jobId:s.jobId});assert.equal(h.state().status,'retry_wait');assert.match(h.state().error,/capacity/);assert.equal(h.submitted.length,3);assert.equal(h.messages.at(-1).DelaySeconds,300);});
test('a legacy completed record cannot be reanalysed by an old delayed message',async()=>{const h=harness();h.set(s=>s.status='ready');await h.call({});assert.equal(h.submitted.length,0);});
test('a monthly budget pause blocks initial dispatch, failure retries and delayed capacity messages',async()=>{
 const h=harness();h.files.set('control/ai-spending.json',JSON.stringify({paused:true}));await h.call({});assert.equal(h.submitted.length,0);assert.equal(h.messages.length,0);assert.equal(h.state().status,'paused');
 const running=harness();await running.call({});const s=running.state();running.set(a=>{a.quick.status='ready';a.available='quick';});running.files.set('control/ai-spending.json',JSON.stringify({paused:true}));await running.failed();await running.call({kind:'watch',token:s.token,jobId:s.jobId});assert.equal(running.submitted.length,1);assert.equal(running.messages.length,1);assert.equal(running.state().status,'paused');assert.equal(running.state().quick.status,'ready');running.files.set('control/ai-spending.json',JSON.stringify({paused:false}));await running.call({});await running.failed();await running.call({kind:'watch',token:s.token,jobId:s.jobId});assert.equal(running.submitted.length,1);assert.equal(running.messages.length,1);
});

test('long games reduce deep visits to stay within the measured full-game processing envelope',async()=>{
 const h=harness();h.files.set(gamePrefix(h.id)+'/original.sgf','(;SZ[19]'+Array.from({length:1999},(_,n)=>';'+(n%2?'W':'B')+'[]').join('')+')');await h.call({});const req=JSON.parse([...h.files].find(([key])=>key.startsWith('jobs/'))[1]);assert.equal(req.phases.deep.visits,483);assert.ok(req.phases.deep.estimatedSeconds<=4000);assert.equal(req.phases.quick.visits,32);const s=h.state();await h.call({kind:'watch',token:s.token,jobId:s.jobId});const spot=JSON.parse([...h.files].filter(([key])=>key.startsWith('jobs/')).at(-1)[1]);assert.equal(spot.phases.deep.visits,483);assert.ok(spot.phases.deep.estimatedSeconds<=5000);
});
