import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import {createHash,randomUUID} from 'node:crypto';
import {cloudPosition} from '../photo-analysis/src/cloud-api.js';
function harness({paused=false,cap=3000000,hold=false}={}){
 const data=new Map(),calls=[],waiting=[];const command=name=>class{constructor(input){this.input=input;this.name=name;}};
 const update=command('update'),invoke=command('invoke'),transaction=command('transaction');
 const db={async send(c){const q=c.input;if(c.name==='transaction'){const [p,u]=q.TransactItems,req=p.Put.Item.id.S,day=u.Update.Key.id.S,v=u.Update.ExpressionAttributeValues;if(data.has(req)||(data.get(day)||0)>Number(v[':available'].N))throw Object.assign(Error(),{name:'TransactionCanceledException'});data.set(req,true);data.set(day,(data.get(day)||0)+Number(v[':units'].N));return {};}
  const key=q.Key.id.S,v=q.ExpressionAttributeValues,old=data.get(key);if(v[':now']){if(old&&old.expires>=Number(v[':now'].N))throw Object.assign(Error(),{name:'ConditionalCheckFailedException'});data.set(key,{owner:v[':owner'].S,expires:Number(v[':expires'].N)});}else{assert.equal(old.owner,v[':owner'].S);old.expires=0;}return {};}};
 class Client{async send(c){calls.push(c.input);const result={Payload:Buffer.from(JSON.stringify({rootScoreLead:1,moves:[]}))};if(hold)return new Promise(resolve=>waiting.push(()=>resolve(result)));return result;}}
 const ctx=vm.createContext({Buffer,Date,db,TransactWriteItemsCommand:transaction,libraryStore:{analysisPaused:async()=>paused},process:{env:{POSITION_USAGE_TABLE:'usage',POSITION_RECOGNIZER:'recognizer',POSITION_ENGINE:'engine',POSITION_DAILY_MICROS:String(cap),POSITION_REQUEST_MICROS:'3000'}},response:(statusCode,body)=>({statusCode,body}),require:n=>n.includes('client-lambda')?{LambdaClient:Client,InvokeCommand:invoke}:n.includes('client-dynamodb')?{UpdateItemCommand:update}:{createHash}});
 vm.runInContext(readFileSync(new URL('../backend/position-handler.cjs',import.meta.url),'utf8')+'\nthis.call=positionHandler;',ctx);
 return {data,calls,waiting,call:(body,path='recognize')=>ctx.call({rawPath:'/api/position/'+path,requestContext:{http:{method:'POST'}},body:JSON.stringify(body)})};
}
const photo=()=>({requestId:randomUUID(),image:'YWJj'});
test('paused spending safeguard and malformed input never invoke costly workers',async()=>{const h=harness({paused:true});assert.equal((await h.call(photo())).statusCode,503);assert.equal(h.calls.length,0);const a=harness();assert.equal((await a.call({...photo(),image:'http://private.example'})).statusCode,400);assert.equal(a.data.size,0);});
test('global daily allowance is atomic and reused request IDs cannot trigger a second worker call',async()=>{const h=harness({cap:6000}),p=photo();assert.equal((await h.call(p)).statusCode,200);assert.equal((await h.call(p)).statusCode,429);assert.equal((await h.call({...p,image:'eHl6'})).statusCode,429);assert.equal((await h.call(photo())).statusCode,200);assert.equal((await h.call(photo())).statusCode,429);assert.equal(h.calls.length,2);});
test('only two in-flight positions are permitted and leases release after completion',async()=>{const h=harness({hold:true}),a=h.call(photo()),b=h.call(photo());await new Promise(setImmediate);assert.equal(h.waiting.length,2);assert.equal((await h.call(photo())).statusCode,429);for(const done of h.waiting)done();assert.equal((await a).statusCode,200);assert.equal((await b).statusCode,200);assert.equal([...h.data.entries()].filter(([k,v])=>k.startsWith('lease#')&&v.expires!==0).length,0);});
test('cloud position preserves SGF history, but an overridden side uses the selected board as a new setup',()=>{const blank=Array(361).fill(null),next=blank.slice();next[60]='black';const frames=[{board:blank,turn:'black',move:null},{board:next,turn:'white',move:{side:'black',index:60}}];const normal=cloudPosition(frames,1,'white','japanese',6.5);assert.deepEqual(normal.moves,[{side:'B',index:60}]);const override=cloudPosition(frames,1,'black','japanese',6.5);assert.equal(override.moves.length,0);assert.equal(override.initialBoard[60],'B');assert.equal(override.initialSide,'B');});
test('public position transport signs the exact request body for the IAM-protected CloudFront origin',async()=>{
 const {positionRequest}=await import('../photo-analysis/src/cloud-api.js');const original=globalThis.fetch;let options;globalThis.fetch=async(url,value)=>{assert.equal(url,'/api/position/analyze');options=value;return {ok:true,json:async()=>({rootScoreLead:1})};};try{await positionRequest('analyze',{moves:[],side:'B'});assert.equal(options.headers['x-amz-content-sha256'],createHash('sha256').update(options.body).digest('hex'));assert.match(JSON.parse(options.body).requestId,/^[a-f0-9-]{36}$/);}finally{globalThis.fetch=original;}
});
