import {t,setLanguage} from './i18n.js';
const sections=[
 ['计时标准与速度目标','Timing and response targets','正式棋局从分析进入 SQS 开始计时，包含排队、等待计算资源、实例和容器启动、模型下载、分析及结果保存。复盘页显示总计已等待时间；完成后显示总耗时和引擎分析耗时。快速结果目标为 5 分钟内；深度结果目标为 1 小时内，最多 2 小时。云端容量和同时上传数量会影响这些目标，基准页分别显示总时间与处理时间。','Production timing starts when analysis enters SQS and includes queueing, capacity waiting, instance/container startup, model download, analysis and saving results. Replay shows total elapsed waiting; completed results show total duration separately from engine time. Quick results should arrive within 5 minutes; deep results target 1 hour, with a maximum wait expectation of 2 hours. Cloud capacity and simultaneous uploads affect these targets. The benchmark page shows both total and processing time.'],
 ['网页与 API','Website and API','网页文件保存在私有 S3 存储桶，通过 CloudFront 提供。/record/棋局ID 由 CloudFront 路由至复盘页。浏览器通过 Lambda API 上传 SGF、读取棋谱和检查分析状态。上传成功后立即返回固定链接，不等待 AI 完成。','Website files are stored in a private S3 bucket and served through CloudFront. CloudFront routes /record/game-ID to the replay page. A Lambda API accepts SGF uploads, reads records and returns analysis status. Uploads return a permanent link immediately, without waiting for AI.'],
 ['可迁移的 S3 棋谱库','Portable records in S3','每个棋局在 games/棋局ID/ 下保存 original.sgf（原始棋谱）、metadata.json（棋局信息及状态）和 analysis-quick.json（临时快速评估）和 analysis.json（深度逐手评估及引擎配置）。原始棋谱保留注释和分支。棋局 ID 不依赖存储桶名称；迁移时复制棋谱文件，并保留 uploads/ 和 reservations/ 的上传映射及 ID 分配记录，以及 daily-analysis/ 的每日额度记录。','Each game lives under games/game-ID/: original.sgf contains the original record, metadata.json contains game details and status, analysis-quick.json contains preliminary quick evaluations, and analysis.json contains the deeper per-position evaluations and engine settings. Original comments and variations are preserved. IDs are independent of the bucket name. To migrate the library, copy these files and retain uploads/, reservations/ and daily-analysis/ for upload mappings, ID allocation and daily allowances.'],
 ["后台分析流程", "Background analysis flow", "上传 API 把分析任务放入 SQS。短时 Lambda 为每个棋局查询最新官方神经网络，并向 AWS Batch 提交两个作业：Fargate CPU 快速分析和 T4 GPU 深度分析，然后退出，不等待分析完成。两个作业使用同一模型，分别从官方来源重新下载模型，不缓存神经网络文件。GPU 容器已包含 KataGo；CPU 作业启动时下载并校验引擎。工作程序把分析结果及状态写回 S3。等待快速结果时浏览器每 15 秒检查一次；后台标签页暂停检查。深度结果只在用户刷新页面时检查。", "The upload API sends an SQS message. A short-lived Lambda selects the latest official neural network once per game and submits two AWS Batch jobs: quick analysis on Fargate CPU and deep analysis on a T4 GPU. It returns without waiting. Both jobs use that model and independently download it fresh from the official source; neural-network files are never cached. GPU containers include KataGo; CPU jobs download and verify the engine at startup. Workers save results and status in S3. The browser checks for quick results every 15 seconds, pausing in hidden tabs. Deep results are checked only when the user refreshes the page."],
 ["运行配置与自动停止", "Configuration and automatic shutdown", "快速分析使用 32 vCPU、60 GB 的 Fargate 作业，每个局面 8 次访问。深度分析使用 NVIDIA T4（g4dn.xlarge，4 vCPU、16 GB 内存、16 GB 显存），每个局面 1,000 次访问，16 个分析线程，批量大小 32。GPU 任务排队超过 20 分钟且尚未启动时，取消该任务并改用 32 vCPU、60 GB、96 次访问的 CPU 分析；界面显示实际配置。模型名称、下载地址、SHA-256、引擎版本和配置保存在分析结果中。只分析 19 路棋谱主线和初始局面；SGF 未注明规则时采用日本规则。保存结果后容器退出，GPU 计算环境最小容量为零，没有人为保留空闲实例。另设四小时故障保护，不把性能目标当作任务超时。", "Quick analysis uses a 32-vCPU / 60-GB Fargate job at 8 visits per position. Deep analysis uses NVIDIA T4 (g4dn.xlarge, 4 vCPUs, 16 GB RAM and 16 GB GPU memory) at 1,000 visits, with 16 analysis threads and NN batch size 32. If a GPU job is still queued after twenty minutes, it is cancelled before starting a 32-vCPU / 60-GB CPU fallback at 96 visits. The interface shows the configuration actually used. Results retain the model name, download URL, SHA-256, engine version and settings. Only 19 × 19 main lines and the initial position are analysed; omitted SGF rules default to Japanese. Containers exit after saving results. GPU minimum capacity is zero, with no deliberate idle-instance retention. A separate four-hour safety timeout handles stuck jobs; performance targets are not job timeouts."],
 ["按用量计费与限制", "Usage-based billing and limits", "所有应用计算资源位于爱尔兰 eu-west-1，并通过 CloudFormation 配置；AWS Batch 管理临时 GPU 实例。Fargate 任务和 GPU 实例按实际运行计费，GPU 启动、空闲到自动释放的时间也有费用。没有常驻 AI 服务器、NAT 网关或容量预留。S3 文件、CloudFront、API、队列、日志和公共 IP 按用量计费。每天前 20 个上传棋谱可启动分析；重复查看棋谱不会重新启动分析。当前爱尔兰 GPU 额度允许最多两个深度作业同时运行，CPU 快速队列与深度后备队列各配置最多 64 vCPU，但仍受账户的区域额度约束。同时上传会增加排队时间。每盘两次分析的费用目标低于 1 美元。", "Application compute runs in Ireland (eu-west-1) and is provisioned through CloudFormation; AWS Batch manages temporary GPU instances. Fargate tasks and GPU instances are billed while running, including GPU setup and idle time until automatic release. There is no continuously running AI server, NAT gateway or capacity reservation. S3 files, CloudFront, API calls, queues, logs and public IPs are billed by usage. The first 20 uploads per day may start analysis; viewing a record does not start another job. The approved Ireland GPU quota allows up to two deep jobs at a time. CPU quick and deep-fallback queues each allow up to 64 vCPUs, subject to the regional account quota. Simultaneous uploads can increase waiting. The cost target for both passes is below US$1 per game."],
 ["直接对弈与性能记录", "Live play and performance records", "主页的当前棋局和历史对局继续保存在按需计费的 DynamoDB 中，与 S3 上传棋谱库分开。工作程序记录下载、引擎分析和保存的分段时间；AWS Batch 记录排队和容器启动时间。基准实验页面显示已完成实验和正在运行的实验，包括以前的 CPU 配置及 GPU 比较。失败或已停止的实验不显示。总时间包含排队、等待容量和准备；另列不含排队的处理时间。", "The current shared game and archived live games remain in on-demand DynamoDB, separate from uploaded SGFs in S3. Workers record download, engine and saving times; AWS Batch records queue and container startup times. The benchmark page lists completed and ongoing experiments, including earlier CPU configurations and GPU comparisons. Failed or stopped experiments are omitted. Total time includes queueing, capacity waits and setup; processing time excluding queueing is listed separately."]
];
function render(){document.title=t('关于 · DL','About · DL');document.getElementById('about-title').textContent=t('技术架构','Technical architecture');const fragment=document.createDocumentFragment();const link=document.createElement('a');link.href='benchmarks.html';link.className='benchmark-link';link.textContent=t('查看 CPU / GPU 基准实验与费用','View CPU / GPU benchmark experiments and costs');fragment.append(link,architectureDiagram());for(const [zh,en,bodyZh,bodyEn] of sections){const article=document.createElement('article'),h=document.createElement('h2'),p=document.createElement('p');h.textContent=t(zh,en);p.textContent=t(bodyZh,bodyEn);article.append(h,p);fragment.append(article);}document.getElementById('about-content').replaceChildren(fragment);}
document.querySelectorAll('[data-language]').forEach(b=>b.onclick=()=>{setLanguage(b.dataset.language);render();});render();

function architectureDiagram(){
 const figure=document.createElement('figure');figure.className='architecture-diagram';
 const caption=document.createElement('figcaption');caption.textContent=t('上传、后台分析与结果显示','Upload, background analysis and results');figure.append(caption);
 const rows=[
  [[t('浏览器','Browser'),t('上传 19 路 SGF','Upload a 19 × 19 SGF')],[t('上传 API · Lambda','Upload API · Lambda'),t('保存棋谱并发送 SQS 消息','Save the record and send an SQS message')],[t('S3 棋谱库','S3 record library'),t('原始 SGF + 棋局信息 · 立即获得链接','Original SGF + metadata · game link available immediately')]],
  [['SQS',t('付费分析任务队列','Analysis request queue')],[t('调度 Lambda','Dispatcher Lambda'),t('查询最新官方模型，向 AWS Batch 提交两个作业','Look up the latest official model; submit two jobs to AWS Batch')],[t('CPU 快速 + GPU 深度','CPU quick + GPU deep'),t('快速：32 vCPU、60 GB · 深度：T4 GPU · 排队 20 分钟后 CPU 后备','Quick: 32 vCPUs / 60 GB · deep: T4 GPU · CPU fallback after 20 min queued')]],
  [[t('Batch 工作程序 · 下载与分析','Batch workers · download and analyse'),t('每个作业从官方来源下载最新模型，不缓存模型；结果记录实际配置','Each job freshly downloads its selected official model; no model cache. Results record the actual settings')],[t('S3 分析文件','S3 analysis files'),t('逐手评估、状态、模型配置、校验值及运行时间','Per-move evaluations, status, model configuration, checksum and runtime')],[t('浏览器复盘页','Browser replay'),t('快速结果每 15 秒检查并显示 · 深度结果需刷新页面查看','Quick: check every 15 seconds and display results · deep: refresh the page to check')]]
 ];
 for(let i=0;i<rows.length;i++){
  const row=document.createElement('div');row.className='architecture-flow';
  for(const [title,body] of rows[i]){const box=document.createElement('div');box.className='architecture-node';const h=document.createElement('strong'),p=document.createElement('p');h.textContent=title;p.textContent=body;box.append(h,p);row.append(box);}
  figure.append(row);if(i<rows.length-1){const connector=document.createElement('div');connector.className='architecture-down';connector.setAttribute('aria-hidden','true');connector.textContent='↓';figure.append(connector);}
 }
 const note=document.createElement('p');note.className='architecture-note';note.textContent=t('Lambda 不等待分析。每个作业保存结果后退出，容器停止，空闲 GPU 实例自动释放；没有常驻 AI 服务器。','Lambda returns without waiting. Workers save results and exit; containers stop and idle GPU instances are released automatically. No AI server stays running.');figure.append(note);return figure;
}
