import {t,setLanguage} from './i18n.js';
const sections=[
 ['网页与 API','Website and API','网页文件保存在私有 S3 存储桶，通过 CloudFront 提供。/record/棋局ID 由 CloudFront 路由至复盘页。浏览器通过 Lambda API 上传 SGF、读取棋谱和检查分析状态。上传成功后立即返回固定链接，不等待 AI 完成。','Website files are stored in a private S3 bucket and served through CloudFront. CloudFront routes /record/game-ID to the replay page. A Lambda API accepts SGF uploads, reads records and returns analysis status. Uploads return a permanent link immediately, without waiting for AI.'],
 ['可迁移的 S3 棋谱库','Portable records in S3','每个棋局在 games/棋局ID/ 下保存 original.sgf（原始棋谱）、metadata.json（棋局信息及状态）和 analysis-quick.json（临时快速评估）和 analysis.json（深度逐手评估及引擎配置）。原始棋谱保留注释和分支。棋局 ID 不依赖存储桶名称；迁移时复制棋谱文件，并保留 uploads/ 和 reservations/ 的上传映射及 ID 分配记录，以及 daily-analysis/ 的每日额度记录。','Each game lives under games/game-ID/: original.sgf contains the original record, metadata.json contains game details and status, analysis-quick.json contains preliminary quick evaluations, and analysis.json contains the deeper per-position evaluations and engine settings. Original comments and variations are preserved. IDs are independent of the bucket name. To migrate the library, copy these files and retain uploads/, reservations/ and daily-analysis/ for upload mappings, ID allocation and daily allowances.'],
 ['后台分析流程','Background analysis flow','上传 API 把分析任务放入 SQS。一个短时 Lambda 读取任务，准备指令并向 AWS Batch 提交快速和深度两个 Fargate CPU 作业，然后退出；它不下载 KataGo，也不等待分析结束。调度 Lambda 为每个棋局查询最新的官方神经网络，让快速和深度作业使用同一模型。Fargate 从官方来源分别下载引擎和模型，不缓存神经网络文件。每个作业运行分析，再把结果及完成状态写回 S3。浏览器等待快速分析时每 15 秒检查一次并自动显示结果；后台标签页暂停检查。深度分析不自动检查，用户刷新页面后显示已完成的深度结果。','The upload API queues analysis in SQS. A short-lived Lambda prepares the request and submits two AWS Batch jobs on Fargate CPU: quick and deep, then returns. It does not download KataGo or wait for analysis. The dispatcher checks the latest official neural network for each game and selects the same model for both jobs. Each Fargate job downloads its engine and model from official sources, without caching the model file, then writes analysis and status back to S3. While waiting for quick analysis, the browser checks every 15 seconds and displays quick results automatically. Checks pause in hidden tabs. Deep analysis is checked only when the user refreshes the page.'],
 ['运行配置与自动停止','Configuration and automatic shutdown','快速和深度作业均使用 32 个 vCPU、60 GB 内存和最新官方神经网络，快速分析每个局面搜索 10 次，深度分析搜索 128 次。在一盘 321 手棋谱上，实测约 3 分 54 秒与 36 分 55 秒，不含排队；未来模型及更长棋谱可能耗时更多。实际引擎版本、模型名称、下载地址、SHA-256 校验值及分析配置保存在结果文件中。仅分析 19 路棋谱的主线，包含初始局面。规则和贴目来自 SGF，未注明规则时使用日本规则。工作程序保存结果并退出后，容器自动停止；每个作业另设四小时的故障保护上限，分析速度目标不作为作业超时。失败事件会更新棋局状态。','Quick and deep jobs each use 32 vCPUs, 60 GB memory and the latest official neural network, with 10 visits per position for quick analysis and 128 for deep analysis. A 321-move test took about 3m 54s and 36m 55s, excluding queue time. Future models and longer games may take more time. Results record the actual engine version, model name, download URL, SHA-256 checksum and analysis settings. Only 19 × 19 main lines are analysed, including the initial position. Rules and komi come from SGF; omitted rules default to Japanese. After saving results, the worker exits and its container stops. A separate four-hour safety timeout handles stuck jobs; performance targets are not job timeouts. Failure events update the game’s status.'],
 ['按用量计费与限制','Usage-based billing and limits','Fargate 仅在任务运行时提供计算资源，无常驻分析服务器；网络使用公共 IP，没有 NAT 网关。S3 存储、CloudFront 流量、API、队列、日志和运行期间的公共 IP 按用量计费，保存的文件仍有存储费用。每天前 20 个上传棋谱可启动付费分析，快速和深度队列各允许最多同时运行一个 32 vCPU 作业，使用独立的计算资源，深度作业不会占用快速作业的资源。重复打开棋谱会复用已有结果，不会启动新的付费分析。','Fargate provides compute only for running jobs; there is no continuously running analysis server. Tasks use public IP addresses without a NAT gateway. S3 storage, CloudFront traffic, API calls, queue requests, logs and public IP usage are billed by usage. Retained files continue to incur storage charges. The first 20 uploads per day can start paid analysis, with at most one 32-vCPU quick job and one 32-vCPU deep job running together on separate compute capacity. Viewing a saved game reuses its results and does not launch another paid analysis.'],
 ['直接对弈与性能记录','Live play and performance records','主页的当前棋局和历史对局继续存储在按需计费的 DynamoDB 中，与 S3 上传棋谱库分开。分析工作程序记录下载、引擎分析和保存结果各阶段的耗时；AWS Batch 记录任务启动和停止时间。CPU 云端流程已测试，GPU 尚未启用。','The current shared game and archived live games remain in on-demand DynamoDB, separate from uploaded records in S3. Analysis workers record download, engine analysis and result-saving timings; AWS Batch records job start and stop times. The cloud CPU workflow has been tested. GPU analysis is not enabled.']
];
function render(){document.title=t('关于 · DL','About · DL');document.getElementById('about-title').textContent=t('技术架构','Technical architecture');const fragment=document.createDocumentFragment();const link=document.createElement('a');link.href='benchmarks.html';link.className='benchmark-link';link.textContent=t('查看 CPU / GPU 基准实验与费用','View CPU / GPU benchmark experiments and costs');fragment.append(link,architectureDiagram());for(const [zh,en,bodyZh,bodyEn] of sections){const article=document.createElement('article'),h=document.createElement('h2'),p=document.createElement('p');h.textContent=t(zh,en);p.textContent=t(bodyZh,bodyEn);article.append(h,p);fragment.append(article);}document.getElementById('about-content').replaceChildren(fragment);}
document.querySelectorAll('[data-language]').forEach(b=>b.onclick=()=>{setLanguage(b.dataset.language);render();});render();

function architectureDiagram(){
 const figure=document.createElement('figure');figure.className='architecture-diagram';
 const caption=document.createElement('figcaption');caption.textContent=t('上传、后台分析与结果显示','Upload, background analysis and results');figure.append(caption);
 const rows=[
  [[t('浏览器','Browser'),t('上传 19 路 SGF','Upload a 19 × 19 SGF')],[t('上传 API · Lambda','Upload API · Lambda'),t('保存棋谱并发送 SQS 消息','Save the record and send an SQS message')],[t('S3 棋谱库','S3 record library'),t('原始 SGF + 棋局信息 · 立即获得链接','Original SGF + metadata · game link available immediately')]],
  [['SQS',t('付费分析任务队列','Analysis request queue')],[t('调度 Lambda','Dispatcher Lambda'),t('查询最新官方模型，向 AWS Batch 提交两个作业','Look up the latest official model; submit two jobs to AWS Batch')],[t('Fargate · 并行作业','Fargate · parallel jobs'),t('快速 / 深度 · 每个作业 32 vCPU、60 GB','Quick / deep · 32 vCPU, 60 GB per job')]],
  [[t('Fargate · 下载与分析','Fargate · download and analyse'),t('从官方来源下载引擎和模型，每个作业独立下载，不缓存模型','Download the engine and model from official sources separately for each job; no model cache')],[t('S3 分析文件','S3 analysis files'),t('逐手评估、状态、模型配置、校验值及运行时间','Per-move evaluations, status, model configuration, checksum and runtime')],[t('浏览器复盘页','Browser replay'),t('快速结果每 15 秒检查并显示 · 深度结果需刷新页面查看','Quick: check every 15 seconds and display results · deep: refresh the page to check')]]
 ];
 for(let i=0;i<rows.length;i++){
  const row=document.createElement('div');row.className='architecture-flow';
  for(const [title,body] of rows[i]){const box=document.createElement('div');box.className='architecture-node';const h=document.createElement('strong'),p=document.createElement('p');h.textContent=title;p.textContent=body;box.append(h,p);row.append(box);}
  figure.append(row);if(i<rows.length-1){const connector=document.createElement('div');connector.className='architecture-down';connector.setAttribute('aria-hidden','true');connector.textContent='↓';figure.append(connector);}
 }
 const note=document.createElement('p');note.className='architecture-note';note.textContent=t('Lambda 不等待分析。每个 Fargate 作业保存结果后退出，容器自动停止；没有常驻 AI 服务器。','Lambda returns without waiting for analysis. Each Fargate job saves its result and exits; its container stops automatically. No AI server stays running.');figure.append(note);return figure;
}
