import './site-shell.js';
import {localTimestamp} from './site-time.js';
import {t,setLanguage} from './i18n.js';
import {flow,tiers,stats,more as details} from './flow-diagram.js';
const sections=[
 ['计时标准与速度目标','Timing and response targets','正式棋局从分析进入 SQS 开始计时，包含排队、等待计算资源、实例和容器启动、模型下载、分析及结果保存。复盘页显示总计已等待时间；完成后显示总耗时和引擎分析耗时。排队估计使用只读 Batch 状态、前面作业的剩余快速与深度分析及当前队列的工作容量，显示保守的单一预计开始与完成时间，精确到分钟；API 状态缓存 15 秒。GPU 容量等待无法可靠预测，超过预计时段后不再推迟时间，而是明确提示开始时间未知。快速分析目标为 5 分钟内；深度分析目标为 1 小时内，最多 2 小时。云端容量和同时上传数量会影响这些目标，基准页分别显示总时间与处理时间。','Production timing starts when analysis enters SQS and includes queueing, capacity waiting, instance/container startup, model download, analysis and saving results. Replay shows total elapsed waiting; completed results show total duration separately from engine time. Read-only Batch status, earlier jobs’ remaining quick and deep work, and the queue’s configured worker capacity provide conservative single start and finish timestamps rounded up to the minute, with API snapshots cached for 15 seconds. GPU capacity waits cannot be reliably predicted; an expired forecast becomes an explicit unknown start time instead of a continually postponed deadline. Quick analysis should arrive within 5 minutes; deep analysis target 1 hour, with a maximum wait expectation of 2 hours. Cloud capacity and simultaneous uploads affect these targets. The benchmark page shows both total and processing time.'],
 ['已生成的 AI 报告与 PDF','Prepared AI reports and PDFs','深度分析完成后，Batch 事件通知原有 Lambda，验证作业与棋谱并保存报告 JSON 到受保护的 WeiqiStorage。随后消息进入 FIFO 报告队列，另一个按使用计费的 Lambda 顺序准备中英文 HTML 与固定 A4 PDF，保存到现有私有网站 S3 桶，由 CloudFront 分发。只有两个语言的所有文件保存完成后才标记就绪；失败最多重试两次。无需新的 GPU 作业，也没有常驻报告服务器。报告先展示带手数的总谱，再展示全局点数与胜率走势，六张图说明着法质量、典型损失、手数区间与关键时刻。双方各五手失误列成表，前三手链接到后面的棋盘详解；图下先用例子解释，再给出计算细节。报告包含棋局链接与元数据封面、目录、页眉页脚和书签。打开报告、切换语言和保存 PDF 只读取已生成文件，不触发新的报告或 PDF 计算；没有用户配置选项。','After deep analysis, the Batch completion event asks the existing Lambda to validate the job and SGF, then save report JSON in protected WeiqiStorage. A FIFO report queue sends preparation to a separate usage-billed Lambda, which creates both English and Chinese HTML views and fixed A4 PDFs. Finished files are saved in the existing private site S3 bucket and delivered through CloudFront. Readiness is published only after every file is saved; failures are retried twice. No new GPU job or always-running report server is needed. Reports start with the numbered full game record, then the game-wide score and winning chances. Six graphs explain move quality, typical loss, move ranges and key moments, with expanded plain-language examples before calculation details. Each side’s five worst moves appear in tables; the first three link to detailed board reviews. They include a metadata-rich title page, game link, contents, headers/footers and bookmarks. Opening, switching languages and saving retrieve prepared files without triggering report or PDF generation. There are no configuration options.'],
 ['棋步点评与推荐变化','Move review and suggested variations','分析文件同时保存 KataGo 排名最高的最多 8 个候选着法（如有必要另保留实战着法），以及每个着法最多 12 手的主要变化。棋盘标记和推荐按钮使用当前显示局面的分析，为当前行棋方推荐下一手；点击后从当前棋盘继续回放。上一手的点评则从落子前局面比较候选分数，按实战棋手的视角计算点数损失；实战着法搜索不足时使用落子后的局面评分，并标注估计。最佳表示引擎首选。好棋、不精确、失误和严重失误采用 0.5、2、5 点阈值，这些是应用的点评规则。变化由浏览器复现，保存在原有 S3 分析文件中；显示或切换变化无需额外分析作业。','Analysis files also retain up to eight leading KataGo candidates (plus the played move when needed), with up to twelve moves of principal variation each. Board markers and recommendation buttons use the displayed position’s analysis to suggest the next move for its player to move; their continuations start from that board. The separate last-move rating compares candidate scores before the played move and computes point loss from that player’s perspective. When the played candidate has insufficient search, it uses the following position’s score and labels the estimate. Best means the engine’s top choice. Good, Inaccuracy, Mistake and Blunder use app-defined thresholds of 0.5, 2 and 5 points. Variations are replayed in the browser from the existing S3 analysis file. Viewing or toggling them requires no extra analysis job.'],
 ['公共工作区与保存','Public workspaces and saving','/play 的现场对弈及 /record 的记录草稿存入 DynamoDB。公共草稿按版本号自动保存；版本冲突时拒绝覆盖。记录树支持分支，保存时仅保留主分支。完成现场对弈自动保存。所有保存均经幂等 API 写入 S3 棋谱库，再发送 SQS 分析消息；保存重试复用原棋局。/game 显示分页棋谱库，/game/编号 提供复盘及 AI。','Live play at /play and the recording draft at /record use DynamoDB. Draft edits auto-save with revision checks that reject conflicting overwrites. The editor keeps variations and saves only the main branch. Finished live games save automatically. Both use an idempotent API to write S3 records before sending SQS analysis messages; retried saves reuse their game. /game is the paginated library; /game/ID provides replay and AI.'],
 ['照片识别','Photo recognition','/analysis 可以上传 19 × 19 棋盘照片。照片在浏览器中压缩后发送到爱尔兰的 Lambda，由开源 Moku v4 模型在 CPU 上找出棋盘四角和棋子；程序再摆正棋盘，在整盘和四个重叠局部上寻找棋子，并检查网格位置、大小、颜色和重复，线上通常 7–8 秒返回。照片不会保存。识别仍在试验中：可疑的点会标出，分析前请对照照片检查。详细步骤、测试结果和局限见下方链接。','/analysis accepts a photo of a 19 × 19 board. The browser compresses it and sends it to a Lambda function in Ireland, where the open-source Moku v4 model finds the board corners and stones on CPU. The board is then squared up, stones are found on the whole board and on four overlapping quarters, and candidates are checked for grid position, size, colour and duplicates. Live results usually return in 7–8 seconds, and the photo is not saved. Recognition is experimental: doubtful points are outlined, so check the board against the photo before analysing. The link below explains the steps, test results and limits.',['/photo-recognition','照片识别原理','How photo recognition works']],
 ['AI 分析：费用与许可','AI analysis: cost and licence','/analysis 的每次分析都是一次短暂的云端请求，没有长时间运行的任务；网站设有每日用量上限。局面按中国规则分析（贴 7.5 或 0.5 目），因为照片无法显示之前的提子和打劫。','Each analysis on /analysis is one short cloud request with no long-running jobs, and the site has a daily usage limit. Positions are analysed under Chinese rules (komi 7.5 or 0.5), because a photo cannot show earlier captures or ko history.',null,{id:'quick-analysis',after:()=>{const f=document.createDocumentFragment();f.append(quickAnalysisCost(),quickAnalysisLicence());return f;}}],
 ['费用与安全','Costs and security','费用估算及公开站点安全审查见下方链接。全部访问公开，草稿可由任何人编辑。AI 每日全站额度为 10；另有每天 100 个新棋谱上限与全站每分钟 120 次修改限流。限流不是 AWS 账单的硬上限。','See the linked cost estimate and public-site security review below. Everything is public and anyone can edit the draft. The site-wide AI quota is ten per day. New records are capped at 100 per day and edits at 120 per minute site-wide. Throttling is not a hard AWS billing cap.'],
 ['网页与 API','Website and API','网页文件保存在私有 S3 存储桶，通过 CloudFront 提供。/game/棋局ID 由 CloudFront 路由至复盘页。浏览器通过 Lambda API 上传 SGF、读取棋谱和检查分析状态。上传成功后立即返回固定链接，不等待 AI 完成。','Website files are stored in a private S3 bucket and served through CloudFront. CloudFront routes /game/game-ID to the replay page. A Lambda API accepts SGF uploads, reads records and returns analysis status. Uploads return a permanent link immediately, without waiting for AI.'],
 ['可迁移的 S3 棋谱库','Portable records in S3','每个棋局在 games/日期/序号/（例如 games/20261005/01/） 下保存 original.sgf（原始棋谱）、metadata.json（棋局信息及状态）和 analysis-quick.json（临时快速评估）和 analysis.json（深度逐手评估及引擎配置）。保存时仅保留主分支，主线注释保留。原始上传 API 兼容已有棋谱。棋局 ID 不依赖存储桶名称；迁移时复制棋谱文件，并保留 uploads/ 和 reservations/ 的上传映射及 ID 分配记录，以及 daily-analysis/ 的每日额度记录。','Each game lives under games/date/sequence/ (for example, games/20261005/01/): original.sgf contains the original record, metadata.json contains game details and status, analysis-quick.json contains preliminary quick evaluations, and analysis.json contains the deeper per-position evaluations and engine settings. The editor saves only the main line and preserves its comments; the upload API remains compatible with existing records. IDs are independent of the bucket name. To migrate the library, copy these files and retain uploads/, reservations/ and daily-analysis/ for upload mappings, ID allocation and daily allowances.'],
 ['独立的生产存储','Protected production storage','WeiqiStorage 是独立的 CloudFormation 栈，拥有原始 SGF、棋局信息、快速及深度分析文件的 S3 存储桶，以及直接对弈的 DynamoDB 表。栈启用终止保护；存储资源采用保留策略，并通过栈策略阻止删除或替换。S3 启用版本控制，DynamoDB 启用删除保护和时间点恢复。部署或删除计算栈不会删除棋谱库。','WeiqiStorage is a separate CloudFormation stack owning the S3 record library and the DynamoDB live-game table. Stack termination protection, resource retention and a stack policy guard against deletion or replacement. S3 versioning preserves previous file versions; DynamoDB has deletion protection and point-in-time recovery. Updating or deleting the compute stack does not delete the library.'],
 ['后台 GPU 分析','Background GPU analysis','上传 API 发送 SQS 消息。短时 Lambda 查询评分可靠的最强官方模型并提交一个 GPU Batch 作业，然后立即退出。一个 GPU 实例先执行快速分析，再执行深度分析；每个阶段都从官方来源重新下载模型，不缓存或保存模型文件。结果与配置写入 S3。快速分析每分钟检查，深度分析需刷新页面查看。','The upload API sends an SQS message. A short-lived Lambda selects the strongest confidently-rated official model and submits one GPU Batch job, then returns. One GPU worker runs quick analysis followed by deep analysis; each pass freshly downloads the official model without persisting or caching its weights. Results and configuration are saved to S3. Quick analysis are checked once a minute; deep analysis require a page refresh.'],
 ['模型、GPU 与后备','Model, GPU and fallback','常规配置为 NVIDIA T4（g4dn.xlarge，4 vCPU、16 GB 内存），快速分析每个局面 32 次访问，深度分析最多 5,000 次访问；超长棋局按手数降低访问量；16 个分析线程，神经网络批量大小 32。尚未启动的作业等待 3 分钟后，可在确认取消后转向 T4 / A10G（g4dn.xlarge / g5.xlarge，4 vCPU、16 GB 内存）后备池，使用相同模型与访问次数。首先使用容量优化型 Spot 队列，使用独立的四 vCPU 额度。再等待三分钟仍未启动时，确认取消后转向 A10G 按需队列。该队列排队十五分钟仍未启动时，取消待启动作业并安排稍后重试。不会改用 CPU。每个结果保存实际模型名称、地址、校验值、引擎版本、计算配置与运行时间。只分析 19 路主线；SGF 未注明规则时采用日本规则。','The primary worker is NVIDIA T4 (g4dn.xlarge, 4 vCPUs, 16 GB RAM), using 32 visits per position for quick analysis and up to 5,000 for deep analysis, with fewer visits for unusually long games, 16 analysis threads and NN batch size 32. A job still waiting to start after three minutes can switch to a GPU fallback pool: T4 or A10G (g4dn.xlarge / g5.xlarge, 4 vCPUs and 16 GB RAM) after cancellation is confirmed, using the same model and visit counts. The first fallback uses capacity-optimized Spot with an independent four-vCPU quota. After another three minutes of queueing, confirmed cancellation precedes a switch to A10G On-Demand. If that queue is still unavailable after fifteen minutes, the queued job is cancelled and a later retry is scheduled. CPU fallback is disabled. Results retain the actual model name, URL, checksum, engine version, compute settings and timing. Only 19 × 19 main lines are analysed; omitted rules default to Japanese.'],
 ['失败与自动重试','Failure and automatic retries','分析失败时棋谱与已完成的快速分析保留，复盘页显示错误。最多自动重试两次：首次失败后 5 分钟，再次失败后 15 分钟。重试时间显示日期、时间、时区和剩余等待时间。重试轮换 GPU 容量池，只执行尚未完成的分析阶段。SQS 延迟消息安排重试，不需要常驻服务器；已用完重试次数时会明确告知用户。','On failure, the record and any completed quick analysis remain available, and replay displays an error. At most two automatic retries are scheduled: five minutes after the first failure and fifteen minutes after the next failure. The page shows the retry date, time, time zone and remaining wait. Retries alternate GPU pools and run only unfinished passes. Delayed SQS messages schedule retries without an always-running server. Exhausted retries are shown explicitly.'],
 ['按用量计费与自动停止','Usage billing and automatic shutdown','所有应用计算资源位于爱尔兰，通过 CloudFormation 配置。容器保存结果后退出，GPU 最小容量为零；实例自动释放，没有常驻 AI 服务器、NAT 网关或容量预留。每天前 10 个上传棋谱可启动分析，查看和推荐变化不触发新作业。计算、启动、等待自动释放、存储、网络、API、队列和日志按用量计费。每盘快速加深度分析费用目标低于 1 美元；排队、云端容量、棋谱长度、重试和模型大小会影响时间及费用，性能目标不是容量保证。另有两小时的作业故障保护。','Application compute runs in Ireland and is provisioned through CloudFormation. Containers save results and exit; GPU minimum capacity is zero and instances retire automatically. There is no always-running AI server, NAT gateway or capacity reservation. The first 10 uploads each day can start analysis; viewing a record or recommended line starts no extra job. Compute, startup, time until automatic retirement, storage, network, API, queues and logs are billed by usage. The paired-analysis cost target is below US$1 per game. Capacity, queueing, game length, retries and model size affect time and cost; response targets are not capacity guarantees. A separate two-hour job safety timeout handles stuck workers.'],
 ["直接对弈与性能记录", "Live play and performance records", "当前现场棋局与公共记录草稿保存在按需计费的 DynamoDB 中，结束或保存后写入 S3 棋谱库。工作程序记录下载、引擎分析和保存的分段时间；AWS Batch 记录排队和容器启动时间。基准实验页面显示已完成实验和正在运行的实验，包括以前的 CPU 配置及 GPU 比较。失败或已停止的实验不显示。总时间包含排队、等待容量和准备；另列不含排队的处理时间。", "The live game and public recording draft use on-demand DynamoDB; finished or saved games enter the S3 library. Workers record download, engine and saving times; AWS Batch records queue and container startup times. The benchmark page lists completed and ongoing experiments, including earlier CPU configurations and GPU comparisons. Failed or stopped experiments are omitted. Total time includes queueing, capacity waits and setup; processing time excluding queueing is listed separately."]
];
function render(){
 document.title=t('关于 · DL','About · DL');document.getElementById('about-title').textContent=t('技术架构','Technical architecture');
 const fragment=document.createDocumentFragment(),links=document.createElement('nav');links.className='page-links';
 for(const [href,zh,en]of [['/benchmarks','CPU / GPU 基准实验','CPU / GPU benchmarks'],['/cost','费用估算','Cost estimate'],['/security','安全审查','Security review'],['/photo-recognition','照片识别原理','How photo recognition works']]){const a=document.createElement('a');a.href=href;a.textContent=t(zh,en);links.append(a);}
 fragment.append(links,stats([[t('0 台','0'),t('空闲时运行的服务器','servers running when idle'),'power'],[t('≈ 5 分钟','≈ 5 min'),t('快速 AI 复盘','quick AI review'),'clock'],[t('≈ 1 小时','≈ 1 h'),t('深度 AI 复盘','deep AI review'),'gpu'],[t('≈ 3 秒','≈ 3 s'),t('分析一个局面','AI for one position'),'katago']]),systemMap(),deepFlow(),positionFlow(),gpuFallback(),spendingGuard());
 const cost=document.createElement('article'),h=document.createElement('h2');cost.id='quick-analysis';h.textContent=t('AI 分析：费用与许可','AI analysis: cost and licence');cost.append(h,quickAnalysisCost(),quickAnalysisLicence());fragment.append(cost);
 const detail=document.createDocumentFragment();
 for(const [zh,en,bodyZh,bodyEn,more,options] of sections){if(options?.id==='quick-analysis')continue;const article=document.createElement('article'),title=document.createElement('h2'),p=document.createElement('p');title.textContent=t(zh,en);p.textContent=t(bodyZh,bodyEn);article.append(title,p);if(more){const p=document.createElement('p'),a=document.createElement('a');a.href=more[0];a.textContent=t(more[1],more[2])+' →';p.append(a);article.append(p);}detail.append(article);}
 fragment.append(details(t('更多技术细节（文字）','More technical details (text)'),detail));
 document.getElementById('about-content').replaceChildren(fragment);
}
window.addEventListener('site-language-change',render);render();

function quickAnalysisLicence(){
 const p=document.createElement('p'),link=(href,text)=>{const a=document.createElement('a');a.href=href;a.textContent=text;return a;};
 p.className='licence-line';
 p.append(t('AI 分析 © 2026 DL。','AI analysis © 2026 DL. '),link('/photo-assets/LICENSE.txt','AGPL-3.0'),t('；无担保。','; no warranty. '),link('/photo-assets/photo-source.tar.gz',t('下载源码','Download source')),' · ',link('/photo-assets/NOTICES.txt',t('第三方许可','Third-party notices')),' · ',link('https://huggingface.co/kaya-go/moku-v4',t('识别模型及源码','Recognition model and source')));
 return p;
}

function systemMap(){
 return tiers({title:t('系统总览','System map'),rows:[
  {badge:t('用户','Users'),label:t('浏览器','Browser'),nodes:[{icon:'browser',title:t('手机或电脑','Phone or computer'),text:t('无须登录','No sign-in')}]},
  {link:'HTTPS',badge:t('边缘','Edge'),label:'CloudFront',tone:'edge',nodes:[{icon:'cloudfront',title:'Amazon CloudFront',text:t('CDN · HTTPS · 安全头','CDN · HTTPS · security headers')}]},
  {link:t('页面 / API','Pages / API'),badge:t('应用','App'),label:t('按次运行','Runs per request'),tone:'app',nodes:[{icon:'s3',title:t('网站文件','Website files'),text:'S3 · HTML / JS / CSS'},{icon:'lambda',title:t('棋局 API','Game API'),text:t('对弈 · 记录 · 棋谱库','Play · record · library')},{icon:'camera',title:t('照片识别','Photo detection'),text:'Lambda · Moku v4'},{icon:'katago',title:t('快速 AI 分析','Quick AI analysis'),text:'Lambda · KataGo CPU'}]},
  {link:t('读写','Read / write'),badge:t('数据','Data'),label:t('私有存储','Private storage'),tone:'private',nodes:[{icon:'dynamodb',title:'DynamoDB',text:t('现场棋局 · 草稿 · 限额','Live game · draft · limits')},{icon:'s3',title:t('棋谱库','Record library'),text:t('S3 · SGF · AI 结果 · 报告','S3 · SGF · AI results · reports')}]},
  {link:t('记录后','After Record'),badge:t('后台','Background'),label:t('只在有任务时运行','Runs only when needed'),nodes:[{icon:'sqs',title:'Amazon SQS',text:t('分析队列','Analysis queue')},{icon:'gpu',title:'AWS Batch GPU',text:'KataGo · T4 / A10G'},{icon:'report',title:t('报告 Lambda','Report Lambda'),text:'Chromium → HTML / PDF'}]}
 ],note:t('全部资源由 AWS CDK / CloudFormation 部署在爱尔兰（eu-west-1）；CloudFront 是全球服务。','Everything is deployed with AWS CDK / CloudFormation in Ireland (eu-west-1); CloudFront is global.')});
}
function deepFlow(){
 return flow({title:t('记录棋局 → 深度 AI 报告','Record game → deep AI report'),numbered:true,steps:[
  {icon:'record',title:t('记录棋局','Record game'),text:t('浏览器','Browser')},
  {icon:'library',title:t('存入棋谱库','Save'),text:'Lambda → S3'},
  {icon:'sqs',title:t('排队','Queue'),text:'SQS'},
  {icon:'gpu',title:t('GPU 分析','GPU analysis'),text:t('快速 ≈ 5 分钟 · 深度 ≈ 1 小时','Quick ≈ 5 min · deep ≈ 1 h')},
  {icon:'report',title:t('AI 报告','AI report'),text:'HTML + PDF'},
  {icon:'power',title:t('GPU 关闭','GPU stops'),text:t('空闲时不运行','Nothing runs when idle')}
 ],note:t('快速 32 次访问，深度 5,000 次访问。失败后 5 分钟、15 分钟自动重试。','Quick: 32 visits. Deep: 5,000 visits. Failures retry after 5 and 15 minutes.')});
}
function positionFlow(){
 return flow({title:t('AI 分析一个局面','AI analysis of one position'),numbered:true,steps:[
  {icon:'phone',title:t('照片 / SGF / 摆子','Photo / SGF / set up'),text:t('照片在浏览器中缩小','Photo resized in browser')},
  {icon:'camera',title:t('照片识别','Photo detection'),text:'Moku v4 · ≈ 8 s'},
  {icon:'flag',title:t('检查棋子','Check stones'),text:t('琥珀色框需检查','Amber boxes need a check')},
  {icon:'katago',title:t('快速 AI 分析','Quick AI analysis'),text:'KataGo CPU · ≈ 3 s'},
  {icon:'chart',title:t('推荐着法','Suggested moves'),text:t('胜率与目差','Win rate and score')}
 ],note:t('不保存照片和局面。全站每天约 1,000 次。','Photos and positions are not stored. About 1,000 requests a day site-wide.')});
}
function gpuFallback(){
 return flow({title:t('GPU 容量不足时','When GPU capacity is short'),steps:[
  {icon:'gpu',title:'T4 On-Demand',text:t('首选','First choice')},
  {icon:'gpu',title:'T4 / A10G Spot',text:t('等待 3 分钟后','After 3 min waiting')},
  {icon:'gpu',title:'A10G On-Demand',text:t('再等 3 分钟后','After 3 more min')},
  {icon:'retry',title:t('稍后重试','Retry later'),text:t('15 分钟仍无容量','Still no capacity after 15 min'),tone:'warn'}
 ]});
}
function spendingGuard(){
 return flow({title:t('费用保护','Spending guard'),steps:[
  {icon:'budget',title:'AWS Budgets',text:t('每天 $15 · 每月 $50','$15 / day · $50 / month')},
  {icon:'lambda',title:t('保护程序','Guard Lambda'),text:t('超额时运行','Runs when exceeded')},
  {icon:'shield',title:t('暂停 AI','Pause AI'),text:t('停止 GPU 队列与任务','Stops GPU queue and jobs'),tone:'bad'},
  {icon:'check',title:t('仍可复盘','Replay still works'),text:t('棋谱与报告保留','Games and reports stay'),tone:'good'}
 ]});
}
// Measured 1–8 October 2026 from Lambda REPORT logs (billed time includes cold starts); x86 in eu-west-1 at US$0.0000166667 per GB-second plus US$0.20 per million requests.
function quickAnalysisCost(){
 const table=document.createElement('table'),cell=(tag,text)=>{const c=document.createElement(tag);c.textContent=text;return c;};
 table.className='cost-table';
 const head=document.createElement('tr');head.append(cell('th',''),cell('th',t('每次','Each')),cell('th',t('每 1000 次','Per 1,000')),cell('th',t('内存 × 平均时间','Memory × average time')));
 table.append(head);
 for(const [zh,en,each,thousand,use] of [['照片识别','Photo recognition','US$0.00013','US$0.13','1.8 GB × 4.6 s'],['AI 分析','AI analysis','US$0.00015','US$0.15','3 GB × 3.0 s']]){const row=document.createElement('tr');row.append(cell('th',t(zh,en)),cell('td',each),cell('td',thousand),cell('td',use));table.append(row);}
 const note=document.createElement('p');note.className='licence-line';note.textContent=t('AWS Lambda（爱尔兰）实测，含冷启动；CloudFront 和日志另有极少费用。','Measured on AWS Lambda in Ireland, including cold starts; CloudFront and logs add a tiny amount.');
 const f=document.createDocumentFragment();f.append(table,note);return f;
}
