import './site-shell.js';import {t} from './i18n.js';import {tiers,stats,callout,more} from './flow-diagram.js';
const costFlows=[
 {href:'/game',name:['棋谱库','Game library'],path:['保存棋谱 → GPU 逐手 AI 复盘 → 报告','Save a game → GPU AI review of every move → report'],
  cost:[[['深度分析与报告','Deep analysis and report'],['US$0.50–0.75 / 局','US$0.50–0.75 / game']],[['只有快速分析','Quick analysis only'],['约 US$0.05 / 局','about US$0.05 / game']]],
  limits:[[['深度分析与报告','Deep analysis and report'],['10 局 / 天','10 games / day']],[['快速分析','Quick analysis'],['每局新棋谱','Every new game']],[['新棋谱','New games'],['100 局 / 天','100 / day']],[['修改','Edits'],['120 次 / 分钟；每个连接 60 次','120 / min; 60 per connection']],[['失败重试','Retries'],['最多 2 次','Up to 2']],[['任务超时','Job timeout'],['2 小时','2 hours']]],
  note:['全站共用；每日额度按伦敦时间零点重置。超过深度额度的棋谱仍有快速分析，但没有报告。','Site-wide; daily limits reset at midnight London time. Games over the deep limit still get quick analysis, but no report.']},
 {href:'/analysis',name:['AI 分析','AI analysis'],path:['照片 → 识别棋子 → AI 分析一个局面（CPU）','Photo → recognise stones → AI analyses one position (CPU)'],
  cost:[[['照片识别','Photo recognition'],['US$0.0004 / 次','US$0.0004 each']],[['AI 分析','AI analysis'],['US$0.00015 / 次','US$0.00015 each']]],
  limits:[[['每日额度','Daily allowance'],['2,000 次（US$3）','2,000 requests (US$3)']],[['每个连接','Per connection'],['500 次 / 天','500 / day']],[['照片','Photo'],['< 50 MB，≤ 7,000 万像素','< 50 MB, ≤ 70 MP']],[['时间上限','Time limit'],['识别 20 秒，AI 20 秒','Recognition 20 s, AI 20 s']]],
  note:['全站共用；每次请求按 US$0.0015 计入，UTC 零点重置。','Site-wide; each request counts as US$0.0015; resets at 00:00 UTC.']}
];
const costGroups=[
 ['1 棋谱库：细节','1 Game library: details',[
  ['实测完整棋局','Measured full game','321 手、同一模型：快速 32 次访问，从入队到结果约 3 分 29 秒；深度 3,000 次访问约 45 分 35 秒，其中深度引擎约 42 分 3 秒。深度完成时累计计算、IP 与磁盘估算约 $0.45；该次快速和深度共用一台实例，不能把两个阶段的累计费用相加；现在快速分析单独使用一台 T4，每局约多 $0.05。加上自动释放前的启动 / 空闲尾段及报告，规划预算约 $0.50–$0.75 / 局。样本不保证未来模型或排队速度。','For a measured 321-move game on the same model, quick analysis at 32 visits took about 3m 29s from queue entry to results. Deep at 3,000 visits took about 45m 35s, including about 42m 3s in the engine. Cumulative compute/IP/disk estimate at deep completion was about $0.45. In that run both phases shared one machine, so do not add their cumulative estimates. Quick analysis now uses its own T4 machine, adding about $0.05 per game. Allowing startup/idle time through retirement and report preparation, plan roughly $0.50–$0.75 per game. This sample does not guarantee future model or queue performance.'],
  ['GPU 价格与后备 GPU','GPU prices and fallback GPU','2026-10-06 查询 AWS 官方爱尔兰 Linux 按需报价：T4 g4dn.xlarge 为 $0.587 / 小时，A10G g5.xlarge 为 $1.123 / 小时。公共 IPv4 为 $0.005 / 小时；磁盘暂按 $0.02 / 实例小时预留，须以实际大小和保留时间结算。250 手的棋局深度 3,000 次访问：首选 A10G 约 15 分钟，约 $0.29；后备 T4 约 36 分钟，约 $0.37（实测：304 手的棋局在 T4 上引擎用时 40 分钟），尚未加小额服务费。因此低于 $1 是正常成功流程的目标，不是每次后备或重试的承诺。','Official AWS Ireland Linux On-Demand prices checked on 6 October 2026: T4 g4dn.xlarge $0.587/hour; A10G g5.xlarge $1.123/hour. Public IPv4 is $0.005/hour. Reserve $0.02 per instance-hour for disk; actual size and retention determine the bill. For a 250-move game at 3,000 deep visits, the first-choice A10G takes about 15 minutes (about $0.29) and the T4 backup about 36 minutes (about $0.37; measured: a 304-move game used 40 minutes of T4 engine time), before small service charges. Below $1 is a target for normal successful operation, not a promise for every fallback or retry.'],
  ['GPU 以外','Beyond GPU','Lambda API、报告 Lambda、DynamoDB 请求、SQS、S3 读写、CloudFront、日志、容器仓库和外网传输均按各自用量计费。报告生成通常约几秒至几十秒，2 GB Lambda 每运行 30 秒约为 60 GB·秒；按约 $0.0000167 / GB·秒预留约 $0.001，再加请求。文件大小、浏览次数和草稿编辑次数影响其他费用。大草稿每次自动保存会按 DynamoDB 的 KB 写入单位收费，建议避免长时间密集修改。保守预留每局额外 $0.01–$0.05，实际浏览量很大时另算传输费用。','API and report Lambda, DynamoDB requests, SQS, S3 operations, CloudFront, logs, the container registry and outbound traffic are usage-billed. A report normally takes seconds to tens of seconds: a 2 GB Lambda running for 30 seconds uses 60 GB-seconds, about $0.001 at an indicative $0.0000167/GB-second, plus requests. File sizes, visits and draft edits determine other costs. Large draft autosaves are charged by DynamoDB’s KB write units. Allow another $0.01–$0.05 per game conservatively; substantial viewing traffic requires a separate transfer estimate.'],
  ['月度示例','Monthly examples','按每局深度分析 $0.50–$0.75：每月 10 局约 $5–$7.50，100 局约 $50–$75。每日上限用满时（10 局深度 + 90 局只有快速分析）约 $9.50–$12，再加照片与局面分析最多 $3，一天约 $12.50–$15；每天 $15 和每月 $50 的费用保护会先暂停 AI，约 4 天用满月度额度。没有分析时 GPU 费用为零；存储和访问仍有少量费用。','At $0.50–$0.75 per deep game, ten games a month cost about $5–$7.50 and 100 games $50–$75. A day at every limit (10 deep games and 90 quick-only games) costs about $9.50–$12, plus up to $3 for photos and positions: about $12.50–$15 a day. The $15 daily and $50 monthly guards pause AI first; about 4 such days use the monthly amount. With no analyses, GPU cost is zero; storage and visits still cost a little.']]],
 ['2 AI 分析：细节','2 AI analysis: details',[
  ['实测费用','Measured cost','两个步骤都在爱尔兰的 AWS Lambda 上用 CPU 运行，请求之间不运行任何程序。实测（含冷启动）：照片识别平均 3.5 GB × 7.3 秒，约 US$0.0004（普通照片约 5.5 秒）；AI 分析（300 次访问）3 GB × 3.0 秒，约 US$0.00015。各 1,000 次合计约 US$0.57。CloudFront 和日志另有极少费用。','Both steps run on CPU in AWS Lambda in Ireland; nothing runs between requests. Measured including cold starts: photo recognition uses 3.5 GB for 7.3 s on average, about US$0.0004 (normal photos take about 5.5 s); AI analysis (300 visits) uses 3 GB for 3.0 s, about US$0.00015. 1,000 of each cost about US$0.57. CloudFront and logs add a tiny amount.'],
  ['每日额度如何计算','How the daily allowance works','每次识别或分析请求按 US$0.0015 计入全站每天（UTC）US$3 的额度，所以每天 2,000 次；每个连接每天最多 500 次。US$0.0015 高于单次请求的最坏情况（识别运行满 20 秒，约 US$0.0013）。用完后两个步骤都暂停到下一个 UTC 日。云端只保存含哈希、一天后过期的请求记录和每日计数，不保存照片和局面。','Each recognition or analysis request counts as US$0.0015 against a site-wide US$3 per UTC day: 2,000 requests a day, with at most 500 per connection. US$0.0015 is above the worst case for one request (a recognition that runs the full 20 seconds, about US$0.0013). When it runs out, both steps pause until the next UTC day. The cloud keeps only a request record with a hash, which expires after one day, and the daily count; photos and positions are not stored.']]],
 ['两个流程共用','Both flows',[
  ['按用量计费','Usage billing','没有常驻 GPU、NAT 网关或新增固定月费订阅。GPU 最小容量为零，任务完成后自动停止并释放实例。保留的 S3 文件、版本、DynamoDB 数据及时间点恢复仍按存储用量计费，即使当月没人访问。现有域名和 DNS 费用不属于本应用新增费用。金额均为美元估算，未扣免费额度或优惠，也未含税。','There is no always-running GPU, NAT gateway or added fixed monthly subscription. GPU capacity scales from zero and instances retire after jobs. Retained S3 files and versions, DynamoDB data and point-in-time recovery still incur storage usage charges even with no visits. Existing domain/DNS charges are outside this app’s incremental estimate. Figures are USD estimates before free tiers, credits and tax.'],
  ['费用保护','Spending guard','Weiqi 的 CloudFormation 栈与可标记资源使用 Project=Weiqi。AWS Budgets 按实际费用跟踪：每天（UTC）$15，每月 $50。任一超过时，私有保护程序暂停两个流程的新 AI，禁用 GPU 队列并终止待运行和运行中的棋局任务。棋谱仍可保存、复盘，已有报告仍可下载。暂停后须由管理员手动恢复，不会自动恢复。账单数据有延迟，未标记的共享资源可能不计入，因此两者都不是账单硬上限。','Weiqi CloudFormation stacks and supported resources carry Project=Weiqi. AWS Budgets track actual spending against $15 per UTC day and $50 per calendar month. When either is exceeded, a private guard pauses new AI in both flows, disables the GPU queues and stops queued and running game jobs. Saving and replaying games and downloading existing reports keep working. An administrator must resume AI; it does not restart automatically. Billing data is delayed and untagged shared resources may be missed, so neither figure is a hard bill ceiling.'],
  ['费用风险','Spending risk','限额按棋局和请求计数，不是美元上限。重试、后备 GPU、更大的新模型、长时间运行或恶意访问都可能提高账单。两小时任务超时用于处理卡住的任务，不是费用保护。开发调试总预算（$50）另行记录，不按棋局重置。','Limits count games and requests, not dollars. Retries, the fallback GPU, larger future models, long runs or abusive traffic can raise the bill. The two-hour job timeout handles stuck jobs; it is not spending protection. The development and debugging budget ($50 total) is tracked separately and is not reset per game.']]]
];
const security=[
 ['公开源码不等于 AWS 访问权限','Public code does not grant AWS access','公开源码让任何人了解 URL、API、限额和架构，但不会提供 AWS 凭据。浏览器只能调用公开应用 API；私有 S3、DynamoDB 和工作队列由 IAM 控制。检查源码、浏览器资源和部署模板没有发现应放入浏览器的 AWS 密钥；访问身份由服务器 IAM 角色提供。云资源名称及账号编号不是密码。审查截至 2026-10-08，包括自行进行的线上渗透测试；不是安全认证或永久保证。','Public source reveals URLs, APIs, quotas and architecture, but does not grant AWS credentials. Browsers call the public app API; IAM controls private S3, DynamoDB and worker queues. Source, browser assets and deployment templates were reviewed for exposed credentials; server IAM roles supply AWS identity. Resource names and account IDs are not passwords. Review date: 8 October 2026, including a self-run test of the live site. This is not a certification or a permanent guarantee.'],
 ['最主要的设计风险：公开编辑','Main design risk: public editing','任何人可修改或清空当前现场棋局及记录草稿，也可消耗每日分析额度。登录、所有权或邀请权限均未提供，这是本站选择的公开协作模式。棋局链接不是保密链接；序号可猜测，库内棋局可公开浏览。不要上传私人信息。草稿版本冲突会拒绝覆盖，S3 版本和 DynamoDB 时间点恢复帮助管理员恢复数据，但不是用户自己的恢复按钮。已保存棋谱没有公开覆盖或删除 API。','Anyone can edit or clear the live game and recording draft, or consume daily analysis slots. There is no login, ownership or invitation permission: public collaboration is intentional. Game links are not secret; IDs are predictable and library games are publicly browsable. Do not upload private information. Revision checks reject conflicting draft overwrites. S3 versions and DynamoDB point-in-time recovery help administrator recovery; they are not a user undo button. Saved records have no public overwrite or delete API.'],
 ['输入与浏览器保护','Input and browser protections','SGF 只接受 UTF-8、19 路、256 KB 内文件，并限制 2,000 个局面与 100 层变化；检查非法坐标、占用点和棋谱结构。API 限制请求体，检查 JSON 和来源；拒绝其他站点的浏览器修改请求。界面使用文本节点显示名称、注释和错误，不把 SGF 内容作为 HTML 执行。报告由受控工作程序生成，访问只读取已生成文件。HTTPS、HSTS、CSP、禁止嵌入框架、nosniff 与来源策略减少浏览器攻击面；CSP 允许内联样式以支持棋盘及静态报告，不允许内联脚本。','SGFs accept only UTF-8, 19 × 19 files up to 256 KB, bounded to 2,000 positions and 100 variation levels. Structure, illegal coordinates and occupied moves are checked. APIs limit bodies, require JSON and reject mutations from other browser origins. Names, comments and errors use text nodes, not SGF-supplied HTML. A controlled worker creates reports; viewing retrieves prepared artifacts. HTTPS, HSTS, CSP, frame denial, nosniff and referrer controls reduce browser exposure. Inline styles remain allowed for boards/reports; inline scripts are blocked.'],
 ['计算滥用与拒绝服务','Compute abuse and denial of service','原子每日额度限制 10 个深度 AI 棋局，其余棋局只有快速分析；上传 UUID 幂等避免重复保存或重复占用额度。每天 100 个新棋谱上限限制文件增长。修改请求每个连接每分钟 60 次、全站每分钟 120 次；局面分析每个连接每天 500 次（全站额度的 25%）。计数使用自动过期的原子记录，只保存哈希桶编号，不保存 IP。API 使用账户的区域 Lambda 并发额度（当前为 400，与其他函数共享），未单独预留。GPU 从零扩容，无 CPU 后备，失败最多重试两次；查看棋谱、推荐变化或报告不触发分析。但攻击者仍可抢占公共额度、拖慢共享页面、制造大量读请求或传输费用；应用限流不能消除 DDoS 或保证账单硬上限。没有固定月费 WAF 或 CAPTCHA。','Atomic daily reservations allow ten deep AI games; other games get quick analysis only. Upload UUID idempotency prevents duplicate records and repeated quota use. A 100-new-record daily cap bounds file growth. Edits are limited to 60/minute per connection and 120/minute site-wide; position requests to 500/day per connection (25% of the site allowance). Counters are atomic, self-expiring rows that store a hashed bucket, not the IP. API Lambda shares the account’s regional concurrency quota (currently 400) without a separate reservation. GPUs scale from zero, with no CPU fallback and at most two retries. Reading games, suggestions and reports starts no analysis. Attackers can still consume public quotas, slow shared pages, and generate read or transfer charges. App throttling cannot eliminate DDoS or enforce a hard bill cap. No fixed-fee WAF or CAPTCHA is enabled.'],
 ['基础设施与数据保护','Infrastructure and data protection','资源通过 CloudFormation 管理，应用计算在爱尔兰；CloudFront 和其必需的证书是全球服务例外。S3 禁止公共存储桶访问并强制 TLS；网站只经 CloudFront OAC 分发。Lambda URL 使用 AWS IAM，由指定 CloudFront 分配调用。GPU 安全组无公网入站规则；任务使用角色读取指定棋谱与保存结果，不接收用户 shell 命令。模型只从代码规定的官方来源选择，SGF 不控制下载 URL。WeiqiStorage 独立且有终止保护、保留策略和数据库删除保护，本次仅添加项目标签，保留数据保护设置。','CloudFormation manages resources; application compute runs in Ireland. Global CloudFront and its required certificate are exceptions. S3 blocks public bucket access and enforces TLS; CloudFront OAC serves the website. The Lambda URL uses AWS IAM and a designated CloudFront distribution. GPU security groups have no public inbound rules. Workers use roles to read games/save results, not user shell commands. Model selection uses code-defined official sources; SGFs do not control download URLs. Separate WeiqiStorage has termination protection, retention and database deletion protection; this release only adds project tags while retaining its data protections.'],
 ['验证范围与后续建议','Validation scope and follow-up','检查覆盖：棋谱验证、路径穿越、覆盖拒绝、每日并发额度、公共草稿版本冲突、重复保存、跨来源修改、浏览器注入显示、HTTPS 安全头、私有桶、IAM URL 和网络入站配置。并发与滥用测试使用本地隔离数据；2026-10-08 对线上网站做了小规模渗透测试（安全头、方法、路径、来源、输入、直连源站，以及不超过 130 次的短时突发请求），不进行压力攻击。没有测试 AWS 自身隔离，也没有模拟大型分布式攻击。分享给朋友适合当前公开模式；大规模公开推广前建议增加登录或邀请权限、可选 WAF / 人机验证、更严格的流量防护；当前已有 $50 月度分析停止机制。','Checks cover SGF validation, traversal, overwrite rejection, concurrent daily quotas, draft revision conflicts, duplicate saving, cross-origin mutations, displayed injection payloads, HTTPS headers, private buckets, IAM function URL and network ingress. Abuse and concurrency tests use isolated local data. On 8 October 2026 the live site received a small penetration test (headers, methods, paths, origins, input, direct origin access and bursts of up to 130 requests), not a load attack. AWS platform isolation and large distributed attacks were not tested. This suits sharing with friends in the chosen public mode. Before broad promotion, consider sign-in or invitations, optional WAF/human verification, stronger traffic controls; a $50 monthly analysis stop guard is now configured.']
];
const photo=[
 ['上传与隐私','Upload and privacy','照片先在浏览器中缩小：最长边不超过 3,072 像素，以 JPEG（质量 0.88）保存；若仍大于约 1 MB，就缩小到 80% 再试。原文件须小于 50 MB、不超过 7,000 万像素。照片随后发送到爱尔兰（eu-west-1）的 Lambda 函数识别，不会写入 S3 或 DynamoDB；云端只保存一条含请求哈希、一天后过期的请求记录，以及全站每日额度计数。原照片只在你的页面中显示，方便对照。','The browser first shrinks the photo so its longest edge is at most 3,072 pixels and saves it as a JPEG at quality 0.88. If it is still larger than about 1 MB, it shrinks it to 80% and tries again. The original file must be under 50 MB and at most 70 megapixels. The photo is then sent to a Lambda function in Ireland (eu-west-1). It is never written to S3 or DynamoDB: the cloud keeps only a request record with a hash, which expires after a day, and the shared daily allowance count. The original photo is shown only in your page, for comparison.'],
 ['识别模型','The recognition model','识别使用 kaya-go 的开源模型 Moku v4，它由 RT-DETR 目标检测模型针对围棋棋盘照片微调而成。每次运行把图像缩放到 640 × 640，给出棋盘四个角，以及每颗黑子和白子的位置、大小和置信度，最多 300 个对象。模型为约 83 MB 的 ONNX 文件，在 Lambda（Python 3.12、x86_64、1,769 MB 内存）中用 ONNX Runtime 1.20.1 在 CPU 上运行，不需要 GPU。以下各步只使用 Moku 的输出和这张照片自身的像素。','Recognition uses Moku v4, an open-source model from kaya-go: an RT-DETR object detector fine-tuned on Go board photos. Each run scales the image to 640 × 640 and returns the board’s four corners plus the position, size and confidence of each black and white stone, up to 300 objects. The model is an ONNX file of about 83 MB. It runs on CPU with ONNX Runtime 1.20.1 in a Lambda function (Python 3.12, x86_64, 1,769 MB memory); no GPU is needed. Every step below uses only Moku’s output and the photo’s own pixels.'],
 ['第 1 步：找到并摆正棋盘','Step 1: find and square up the board','Moku 先在整张照片上找出四个角。找不到四个清晰的角时，就把照片左右镜像再运行一次，合并两次找到的角点后重试。如果网格仍与棋子对不上（例如低角度拍摄或很小的棋盘），就在棋子最密集处周围最多六个正方形局部（部分经过旋转）上再运行 Moku，选出与棋子最吻合的网格；旋转最小的角点顺序当作棋盘正方向。随后用透视变换把棋盘拉成 800 × 800 像素的正方形，四周留 64 像素边距，相邻交叉点相距约 37 像素。这样无论从哪个角度拍摄，19 × 19 个交叉点都落在固定位置。','Moku first finds the four corners in the whole photo. If it cannot find four clear corners, it runs again on a mirrored copy and retries with the corners from both runs combined. If the grid still does not fit the stones, for example in a low-angle photo or on a small board, Moku runs again on up to six square crops around the densest stones, some of them rotated, and the grid that best fits the stones is chosen. The corner order with the least rotation is taken as upright. A perspective transform then turns the board into an 800 × 800-pixel square with a 64-pixel margin, so neighbouring intersections are about 37 pixels apart. Whatever the camera angle, the 19 × 19 intersections now sit at fixed positions.'],
 ['第 2 步：寻找棋子','Step 2: find the stones','一盘接近终局的棋可能有近 300 颗棋子，而 Moku 每次最多返回 300 个对象，所以整盘只运行一次会漏子。因此除了在整个棋盘上运行一次，还在四个相互重叠的 500 × 500 像素局部上各运行一次。离局部内侧边缘不到 0.7 格的棋子可能被切开，交给其他几次运行处理。整盘置信度至少 3.5% 或局部至少 5% 的点成为候选，两类得分相加后决定颜色。','A board near the end of a game can hold close to 300 stones, and each Moku run returns at most 300 objects, so a single run on the whole board missed stones. Moku therefore runs once on the whole board and once on each of four overlapping 500 × 500-pixel quarters. Stones within 0.7 of a square of a quarter’s inner edge may be cut off, so they are left to the other runs. A point becomes a candidate when the whole-board run gives at least 3.5% confidence or a quarter run at least 5%; the scores from both are added to choose the colour.'],
 ['第 3 步：对齐网格','Step 3: refit the grid','棋子有厚度。斜着拍摄时，棋子中心看起来偏离棋盘表面的交叉点，离镜头越远偏得越多。程序用置信度较高的棋子中心重新拟合网格（最多四轮），再把每个候选归到最近的交叉点；距离超过 0.35 格的候选先不采用。随后遮住棋子，检查棋盘上印的线：线与网格一致时保留网格；两个方向的线和棋盘边缘都清楚但不一致时，改用线的位置；否则报告“棋盘网格不确定”，而不是返回错误的棋盘。','Stones have height. In an angled photo their centres appear shifted from the intersections on the board surface, more so further from the camera. The grid is therefore refitted to the centres of confident stones, in up to four rounds, and each candidate is assigned to its nearest intersection. Candidates more than 0.35 of a square away are not used at first. Then the printed lines are checked, with the stones masked out. If the lines agree, the grid is kept. If both directions and the board edges are clear but disagree, the grid moves to the lines. Otherwise the page reports that the board grid is uncertain, rather than returning a wrong board.'],
 ['第 4 步：排除误检','Step 4: reject false detections','四项检查排除常见错误。一、宽度小于高置信棋子中位宽度 89% 的候选不算棋子，通常是贴纸或标记。二、颜色检查：以附近 8 个可靠黑子、8 个可靠白子和 8 个明显空点的颜色为参照，统计候选中心区域的像素最接近哪一种。黑子需要至少 50% 的像素最接近黑色，白子需要 60%；不足时改试另一种颜色，仍不合格则判为空点。参照都取自同一张照片的附近位置，因此偏色和明暗不均的影响较小。三、斜拍时，较高的棋子可能同时在相邻交叉点被识别；两颗相邻候选的中心相距不到 0.7 格时，只保留置信度较高的一颗。四、离一颗较强棋子不到 0.9 格的较弱候选（常是高棋子的重影或旁边的反光），只有在它自己的交叉点上显示该颜色时才保留。最后，一颗单独、大小正常、离交叉点不到半格的棋子，如果通过颜色检查，也会放到最近的交叉点上。','Four checks remove common errors. First, candidates narrower than 89% of the median width of confident stones are not stones; they are usually stickers or markers. Second, a colour check: the nearest 8 reliable black stones, 8 reliable white stones and 8 clearly empty points provide colour references, and the check counts which reference each pixel in the candidate’s centre is closest to. A black stone needs at least 50% of pixels closest to black, and a white stone 60%. If it falls short, the other colour is tried; if that also fails, the point is left empty. Because the references come from nearby points in the same photo, colour casts and uneven lighting matter less. Third, in an angled photo a tall stone can also be detected on the neighbouring point. When two neighbouring candidates are less than 0.7 of a square apart, only the more confident one is kept. Fourth, a weaker candidate less than 0.9 of a square from a stronger stone, often an echo of a tall stone or glare beside it, is kept only if its own intersection shows that colour. Finally, a single stone of normal size up to half a square from an intersection is placed on the nearest point if it passes the colour check.'],
 ['需要检查的点','Points to check','以下点会标为需要检查：颜色检查推翻了模型的判断；颜色比例只比要求高出不到 20 个百分点；置信度低于 5%；在此删除了重复识别或重影；或棋子是从交叉点外放进来的。识别完成后，这些点在编辑模式下以琥珀色虚线框标出，点击修改后标记消失。红色实线框表示没有气的棋子，实战中不可能出现，通常说明识别有误。最后还有一项安全检查：如果直接识别整张照片得到 15 颗以上棋子，而结果不到其一半，就报告识别不确定，而不是返回近乎空白的棋盘。照片无法还原之前的棋步、提子或劫争。','A point is marked for checking when the colour check overruled the model, the colour share was less than 20 percentage points above its requirement, the confidence was below 5%, a duplicate or echo was removed there, or the stone was placed from off the point. After recognition, these points have an amber dashed outline in edit mode, which disappears when you tap the point. A solid red outline marks stones without liberties, which cannot occur in a real game and usually means a recognition error. A final safeguard reports an uncertain detection, rather than returning a nearly empty board, if a direct read of the whole photo finds more than 15 stones but the result has fewer than half as many. A photo cannot reveal earlier moves, captures or ko.'],
 ['准确率测试','Accuracy tests','测试使用 6 张用户的真实棋盘照片（照片 5 低角度、有棋盒和手；照片 6 是一块较小、倾斜的电子棋盘）和 10 张网上照片。前 6 张的参考局面由另一款独立的付费识别工具读出，并经用户确认；照片 6 右侧有 12 个点看起来错了一列，按照片目视改正，未经独立核实。网上照片的参考局面为人工抄写。参考局面只用于评分，从不参与识别。为检验稳健性，每张照片还做了 11 种合成变化：缩小、两档变暗、提亮、降低对比度、偏暖、偏冷、明暗不均、模糊、旋转 4° 和更强的 JPEG 压缩，共 72 + 120 个样本。这些变化不是新的棋局。上传处理与网页相同；本机时间在 Apple Silicon CPU 上单线程测得，不含上传和 Lambda 启动。','Tests use 6 real board photos from the user and 10 photos from the web. Photo 5 is taken from a low angle, with bowls and hands; photo 6 is a small, tilted electronic board. References for the 6 photos were read by a separate paid recognition tool and confirmed by the user. In photo 6, 12 points on the right looked one column out and were corrected by eye from the photo; this was not checked independently. References for the web photos were typed by hand. References are used only for scoring, never during recognition. To test robustness, each photo was also changed in 11 synthetic ways: smaller size, two darker levels, brighter, lower contrast, warmer, cooler, uneven lighting, blur, a 4° rotation and heavier JPEG compression, making 72 + 120 samples. These changes are not new board positions. Uploads are prepared as on the page; local times were measured single-threaded on an Apple Silicon CPU and exclude upload and Lambda start-up.']
];
const photoAfter=[
 ['局限','Limits','阈值是看着这些照片调出来的，所以它们不是独立的测试；16 张照片也不能证明在其他棋盘、棋子和光线下的准确率。剩下的错误大多是反光处多出的白子：照片 5 原照片多出 2 颗，12 个版本共 35 个错误，提亮时最多 10 个。反光几乎是纯白，和白子很像。我们又试了三种检查（棋子下面是否有线、深色边缘、颜色），都会同时删掉真的白子，所以没有采用；要解决需要新的棋子模型，我们不打算继续做。倾斜照片：把每张照片再倾斜 20°–50° 测试，大多数照片仍只有 0–2 个错误；但本来就斜拍的照片 6 再倾斜 35° 以上、或较小的照片 2 倾斜 50° 时会失败。角度很低时，高高的棋子会挡住后面的点，要解决需要立体处理和新模型，我们也不打算继续做。请尽量从正上方拍摄。分析前请始终对照照片检查。','The thresholds were tuned while looking at these photos, so they are not an independent test, and 16 photos cannot show accuracy for other boards, stones or lighting. Most remaining errors are extra white stones on glare. Photo 5 has 2 on the unchanged photo and 35 errors across its 12 versions, up to 10 when brightened. Glare is almost pure white, like a white stone. We tried three more checks (a line under the stone, a dark rim, colour), but each also removed real white stones, so none is used. Fixing this needs a new stone model, and we do not plan more work on it. Angled photos: each photo was also tilted by 20°–50°. Most photos still had 0–2 errors, but photo 6, which is already angled, fails when tilted 35° or more, and the small board in photo 2 fails at 50°. At a very low angle, tall stones hide the points behind them; fixing this needs 3D handling and a new model, and we do not plan more work on it either. Take the photo from above if you can. Always check the board against the photo before analysing.'],
 ['时间与费用','Time and cost','线上测试中，普通照片的识别往返约 6 秒；难读的照片需要多次寻找棋盘，约 10 秒。函数冷启动时再多约 4 秒。识别函数使用 3.5 GB 内存（2 个 CPU）；用 1.8 GB 时同样的照片需要 10–16 秒。识别 20 秒后超时，页面最多等待 30 秒。每次识别或云端局面分析预留 0.0015 美元，全站每天（UTC）共 3 美元，即 2,000 次，每个连接最多 500 次；用完后当天暂停。项目的费用保护也可能暂停此功能。AI 分析只在点击“分析当前局面”后开始。','In live tests, a normal photo took about 6 seconds round trip. Hard photos, where the board must be searched again, took about 10 seconds. A cold start adds about 4 seconds. The recognition function has 3.5 GB of memory (2 CPUs); with 1.8 GB the same photos took 10–16 seconds. Recognition times out after 20 seconds, and the page waits at most 30 seconds. Each recognition or cloud position analysis reserves US$0.0015 from a site-wide allowance of US$3 per UTC day: 2,000 operations, at most 500 per connection. When it runs out, the feature pauses until the next day. The project’s spending safeguard can also pause it. AI analysis starts only when you click Analyse position.'],
 ['源代码与许可','Source code and licences','Moku v4 采用 AGPL-3.0 许可。本站的照片识别代码同样采用 AGPL-3.0，可在照片分析页或下方链接下载。Moku 项目报告其测试集中约 44% 的照片完全识别正确；本站在其输出之上增加了上述步骤。','Moku v4 is licensed under AGPL-3.0. This site’s photo-recognition code is also AGPL-3.0; download its source from the photo analysis page or the link below. The Moku project reports that about 44% of its test photos are read perfectly; this site adds the steps above on top of its output.']
];
const pages={
 cost:{title:['费用估算','Cost estimate'],intro:costSummary,sections:[],extra:costDetails,links:[['/benchmarks','基准实验','Benchmark experiments'],['https://aws.amazon.com/ec2/pricing/on-demand/','AWS EC2 价格','AWS EC2 pricing'],['https://aws.amazon.com/vpc/pricing/','AWS IPv4 价格','AWS IPv4 pricing'],['https://aws.amazon.com/lambda/pricing/','AWS Lambda 价格','AWS Lambda pricing'],['https://aws.amazon.com/s3/pricing/','AWS S3 价格','AWS S3 pricing'],['https://aws.amazon.com/dynamodb/pricing/','AWS DynamoDB 价格','AWS DynamoDB pricing']]},
 security:{title:['安全审查','Security review'],intro:securityOverview,sections:[],extra:securityExtra,links:[['https://cheatsheetseries.owasp.org/cheatsheets/REST_Security_Cheat_Sheet.html','OWASP API 安全','OWASP REST security'],['https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html','OWASP 输入验证','OWASP input validation'],['https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html','OWASP XSS 防御','OWASP XSS prevention']]},
 photo:{title:['照片识别原理','How photo recognition works'],intro:photoIntro,sections:photo,extra:photoResults,after:photoAfter,sourcesTitle:['参考与源码','Sources and code'],links:[['/analysis','照片分析','Photo analysis'],['https://github.com/kaya-go/moku','Moku 源代码','Moku source code'],['https://huggingface.co/kaya-go/moku-v4','Moku v4 模型','Moku v4 model'],['/photo-assets/photo-source.tar.gz','下载本站识别源码','Download this site’s recognition source'],['https://onnxruntime.ai/','ONNX Runtime','ONNX Runtime']]}
};
function costList(title,rows,className){const f=document.createDocumentFragment(),h=document.createElement('h3'),list=document.createElement('dl');h.textContent=t(...title);list.className='cost-list'+(className?' '+className:'');for(const [label,value]of rows){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=t(...label);dd.textContent=t(...value);list.append(dt,dd);}f.append(h,list);return f;}
function costSummary(f){const lead=document.createElement('p');lead.className='cost-lead';lead.textContent=t('按用量计费，没有固定月费。金额为美元估算，未扣免费额度，未含税。','Pay per use, with no fixed monthly fee. USD estimates before free tiers and tax.');const grid=document.createElement('div');grid.className='cost-flows';costFlows.forEach((flow,i)=>{const card=document.createElement('section'),h=document.createElement('h2'),number=document.createElement('span'),link=document.createElement('a'),path=document.createElement('p'),note=document.createElement('p');card.className='cost-flow';number.className='cost-flow-number';number.textContent=String(i+1);link.href=flow.href;link.textContent=t(...flow.name);h.append(number,link);path.className='cost-flow-path';path.textContent=t(...flow.path);note.className='cost-flow-note';note.textContent=t(...flow.note);card.append(h,path,costList(['费用','Cost'],flow.cost,'cost-price'),costList(['限额','Limits'],flow.limits),note);grid.append(card);});const guard=document.createElement('p'),strong=document.createElement('strong');guard.className='cost-guard';strong.textContent=t('两个流程共用的费用保护','Spending guard for both flows');guard.append(strong,t('项目费用超过每天 US$15 或每月 US$50 时，所有新 AI 暂停，运行中的 GPU 任务停止。保存和复盘不受影响；由管理员恢复。','If project spending passes US$15 in a day or US$50 in a month, all new AI pauses and running GPU jobs stop. Saving and replaying still work; an administrator resumes AI.'));f.append(lead,grid,guard);}
function costDetails(f){for(const [zh,en,sections]of costGroups){const h=document.createElement('h2');h.textContent=t(zh,en);f.append(h);for(const [szh,sen,bzh,ben]of sections){const s=document.createElement('section'),h3=document.createElement('h3'),p=document.createElement('p');s.className='cost-detail';h3.textContent=t(szh,sen);p.textContent=t(bzh,ben);s.append(h3,p);f.append(s);}}}
function addSections(f,sections){for(const [zh,en,bzh,ben]of sections){const s=document.createElement('section'),h=document.createElement('h2'),p=document.createElement('p');h.textContent=t(zh,en);p.textContent=t(bzh,ben);s.append(h,p);f.append(s);}}
function table(headers,rows){const wrapper=document.createElement('div');wrapper.className='document-table';const table=document.createElement('table'),head=document.createElement('tr');for(const [zh,en]of headers){const th=document.createElement('th');th.textContent=t(zh,en);head.append(th);}table.append(head);for(const row of rows){const tr=document.createElement('tr');for(const [zh,en]of row){const td=document.createElement('td');td.textContent=t(zh,en);tr.append(td);}table.append(tr);}wrapper.append(table);return wrapper;}
function securityOverview(f){
 f.append(callout('shield',t('2026 年 10 月 8 日审查，并测试了线上网站。这是公开网站：在设定限额内被滥用，是可接受的设计选择。','Reviewed and tested on the live site on 8 October 2026. This is a public site: abuse within the set limits is an accepted design choice.')));
 f.append(tiers({title:t('信任边界','Trust boundaries'),rows:[
  {badge:t('不可信','Untrusted'),label:t('互联网','Internet'),tone:'untrusted',nodes:[{icon:'user',title:t('访客','Visitors'),text:t('无须登录','No sign-in')},{icon:'bot',title:t('机器人 / 攻击者','Bots / attackers'),text:t('同样的公开权限','Same public access')}]},
  {link:'HTTPS',badge:t('边缘','Edge'),label:'CloudFront',tone:'edge',nodes:[{icon:'cloudfront',title:'CloudFront',text:t('仅 HTTPS · HSTS · CSP','HTTPS only · HSTS · CSP')},{icon:'filter',title:'ApiViewer',text:t('标记连接网络，不保存 IP','Tags the network; IP not stored')},{icon:'lock',title:'OAC',text:t('签名访问源站','Signs requests to origins')}]},
  {link:t('只有 CloudFront 能调用','Only CloudFront can call'),badge:'API',label:t('检查与限额','Checks and limits'),tone:'app',nodes:[{icon:'lambda',title:'Lambda API',text:t('来源 · JSON · 大小 · SGF','Origin · JSON · size · SGF')},{icon:'gauge',title:t('限额','Limits'),text:t('每个连接 + 全站','Per connection + site-wide')},{icon:'budget',title:t('费用保护','Spending guard'),text:t('每天 $15 · 每月 $50','$15 / day · $50 / month')}]},
  {link:'IAM',badge:t('私有','Private'),label:t('数据与计算','Data and compute'),tone:'private',nodes:[{icon:'dynamodb',title:'DynamoDB',text:t('条件写入 · 时间点恢复','Conditional writes · PITR')},{icon:'s3',title:'S3',text:t('禁止公开访问 · 版本','No public access · versions')},{icon:'gpu',title:'Batch GPU',text:t('没有入站端口','No inbound ports')},{icon:'report',title:t('报告渲染','Report renderer'),text:t('阻止外部网络请求','Blocks outside requests')}]}
 ],note:t('公开源码不含 AWS 密钥；所有 AWS 权限来自服务器 IAM 角色。','Public code holds no AWS keys; all AWS access comes from server IAM roles.')}));
 const h=document.createElement('h2');h.textContent=t('公开限额','Public limits');f.append(h);
 f.append(stats([[t('60 次 / 分钟','60 / min'),t('每个连接的修改','edits per connection'),'gauge'],[t('120 次 / 分钟','120 / min'),t('全站修改','edits, site-wide'),'gauge'],[t('500 次 / 天','500 / day'),t('每个连接的 AI 分析','AI analyses per connection'),'katago'],[t('2,000 次 / 天','2,000 / day'),t('全站 AI 分析','AI analyses, site-wide'),'katago'],[t('10 局 / 天','10 / day'),t('深度 AI 棋局','deep AI games'),'gpu'],[t('100 局 / 天','100 / day'),t('新棋谱','new records'),'library']]));
 const p=document.createElement('p');p.className='dg-note';p.textContent=t('“连接”指一个 IPv4 地址或一个 IPv6 /64 网络；只保存哈希桶编号，不保存 IP。','A “connection” is one IPv4 address or one IPv6 /64 network. Only a hashed bucket number is stored, never the IP.');f.append(p);
}
function securityExtra(f){
 const heading=(zh,en)=>{const h=document.createElement('h2');h.textContent=t(zh,en);f.append(h);};
 const pass=['✓ 通过','✓ Pass'],fixed=['✓ 已修复','✓ Fixed'];
 heading('线上渗透测试','Live penetration test');
 f.append(table([['测试','Test'],['结果','Result'],['状态','Status']],[
  [['HTTPS 与 TLS','HTTPS and TLS'],['HTTP → HTTPS 301；拒绝 TLS 1.1；HSTS 1 年','HTTP → HTTPS 301; TLS 1.1 refused; HSTS 1 year'],pass],
  [['安全头','Security headers'],['CSP 禁止内联脚本、禁止嵌入、nosniff、来源策略','CSP blocks inline script; framing denied; nosniff; referrer policy'],pass],
  [['隐藏文件','Hidden files'],['/.git、/.env、源码映射、目录列表 → 404','/.git, /.env, source maps, directory listing → 404'],pass],
  [['HTTP 方法','HTTP methods'],['PUT / DELETE / PATCH / TRACE → 405','PUT / DELETE / PATCH / TRACE → 405'],pass],
  [['跨站修改','Cross-site writes'],['其他来源 → 403；text/plain → 415','Foreign origin → 403; text/plain → 415'],pass],
  [['错误输入','Bad input'],['坏 JSON、原型污染、非法局面 → 400，不占用额度','Broken JSON, prototype pollution, bad positions → 400, no quota used'],pass],
  [['路径技巧','Path tricks'],['路径穿越 → 404；空字节 → 400','Path traversal → 404; null byte → 400'],pass],
  [['绕过 CloudFront','Bypass CloudFront'],['直接访问 Lambda URL 和 S3 → 403','Lambda URL and S3 directly → 403'],pass],
  [['伪造客户端头','Spoofed client header'],['CloudFront 覆盖 x-weiqi-viewer','CloudFront overwrites x-weiqi-viewer'],pass],
  [['重放局面请求','Replayed position request'],['→ 429','→ 429'],pass],
  [['一个客户端突发 70 次修改','One client sends 70 edits'],['之前：全站修改暂停。现在：60 次后只限制该连接','Before: paused edits for everyone. Now: only that connection is limited after 60'],fixed],
  [['并行修改','Parallel edits'],['之前：误报“网站繁忙”。现在：原子计数','Before: false “busy” errors. Now: atomic counter'],fixed],
  [['错误的棋谱库翻页参数','Bad library page cursor'],['之前：500。现在：400','Before: 500. Now: 400'],fixed],
  [['依赖','Dependencies'],['线上运行 0 个告警；CDK 构建工具 1 个（不在线上运行）','0 runtime advisories; 1 in the CDK build tool (not run live)'],pass]
 ]));
 heading('威胁模型','Threat model');
 f.append(table([['场景','Scenario'],['剩余风险','Residual risk'],['防护 / 限制','Controls / limits']],[
  [['访客清空共享草稿','Visitor clears shared draft'],['高 · 设计允许','High · allowed by design'],['公开协作、版本冲突检查、S3 版本；没有个人所有权','Public collaboration, revision checks, S3 versions; no ownership']],
  [['多 IP 机器人用完公开额度','Many-IP bot uses up public limits'],['高 · 接受','High · accepted'],['全站每日上限、费用保护；读取与流量费用仍可能增加','Site-wide daily caps, spending guard; read and transfer charges remain']],
  [['一个客户端刷修改或 AI','One client floods edits or AI'],['低 · 本次已修复','Low · fixed in this review'],['每个连接：修改 60 次 / 分钟，AI 分析 500 次 / 天','Per connection: 60 edits / min, 500 AI analyses / day']],
  [['SGF 名称或注释注入脚本','SGF name/comment script injection'],['较低 · 已测试','Lower · tested'],['文本节点、输入限额、CSP 禁止内联脚本','Text nodes, bounded input, CSP blocks inline script']],
  [['绕过网站访问私有资源','Bypass site to reach private AWS'],['较低 · 测试中被拒绝','Lower · denied in tests'],['私有 S3、IAM Lambda URL、OAC、GPU 无入站','Private S3, IAM function URL, OAC, no GPU inbound']],
  [['报告渲染访问外部网址','Report renderer fetches outside URLs'],['较低 · 已测试','Lower · tested'],['拦截所有外部请求，只读取本地文件','All outside requests blocked; local files only']],
  [['并发覆盖 / 重复保存','Concurrent overwrite / duplicate save'],['较低 · 已测试','Lower · tested'],['条件写入、上传 UUID 幂等、已保存棋谱不可公开覆盖','Conditional writes, UUID idempotency, immutable saved records']]
 ]));
 heading('接受的剩余风险','Accepted residual risks');
 const list=document.createElement('ul');
 for(const [zh,en]of [['多 IP 分布式滥用仍可用完全站额度；AI 暂停到第二天。','Distributed abuse from many IPs can still use up site-wide limits; AI then pauses until the next day.'],['任何人都可以修改或清空现场棋局和草稿。','Anyone can change or clear the live game and draft.'],['读取与流量费用没有硬上限；没有 WAF 或验证码。','No hard cap on read and transfer charges; no WAF or CAPTCHA.'],['小问题：413 错误显示 AWS 文字；没有 security.txt；HSTS 不含子域名（父域名 dliu.com 另有用途）。','Minor: 413 errors show AWS text; no security.txt; HSTS excludes subdomains (the parent dliu.com is used elsewhere).']]){const li=document.createElement('li');li.textContent=t(zh,en);list.append(li);}
 f.append(list);
 const detail=document.createDocumentFragment();addSections(detail,security);f.append(more(t('更多细节（文字）','More details (text)'),detail));
}
function photoIntro(f){const notice=document.createElement('p');notice.className='notice-box';notice.textContent=t('照片识别仍在试验中。它把一张 19 × 19 棋盘照片转成可编辑的局面，只是起点；分析前请对照原照片检查每一颗棋子。','Photo recognition is experimental. It turns a photo of a 19 × 19 board into an editable position as a starting point; check every stone against the photo before analysing.');f.append(notice);const figure=document.createElement('figure');figure.className='architecture-diagram';const caption=document.createElement('figcaption');caption.textContent=t('从照片到局面','From photo to position');figure.append(caption);const rows=[[[t('浏览器','Browser'),t('缩小并压缩照片：最长边不超过 3,072 像素，约 1 MB 以内','Shrinks and compresses the photo: longest edge up to 3,072 pixels, about 1 MB or less')],[t('找到棋盘','Find the board'),t('Moku v4 找出四个角；不确定时用镜像照片和局部放大重试','Moku v4 finds the four corners; if unsure, it retries with a mirrored copy and zoomed crops')],[t('摆正棋盘','Square up the board'),t('透视校正为 800 × 800 像素的正方形','Perspective-corrects the board to an 800 × 800-pixel square')]],[[t('寻找棋子','Find the stones'),t('整盘运行一次，再在四个重叠局部各运行一次','One run on the whole board, plus one on each of four overlapping quarters')],[t('检查候选','Check candidates'),t('对齐网格并核对棋盘线，再检查大小、颜色和重影','Refit the grid and check the printed lines, then check size, colour and echoes')],[t('返回局面','Return the position'),t('返回棋盘和需要检查的点；照片不保存','Returns the board and points to check; the photo is not saved')]]];for(let i=0;i<rows.length;i++){const row=document.createElement('div');row.className='architecture-flow';for(const [title,body]of rows[i]){const box=document.createElement('div');box.className='architecture-node';const h=document.createElement('strong'),p=document.createElement('p');h.textContent=title;p.textContent=body;box.append(h,p);row.append(box);}figure.append(row);if(i<rows.length-1){const down=document.createElement('div');down.className='architecture-down';down.setAttribute('aria-hidden','true');down.textContent='↓';figure.append(down);}}const note=document.createElement('p');note.className='architecture-note';note.textContent=t('除浏览器压缩外，全部步骤在爱尔兰的一个 Lambda 函数中用 CPU 完成，线上通常 7–8 秒返回。','Apart from compression in the browser, every step runs on CPU in one Lambda function in Ireland; live results usually return in 7–8 seconds.');figure.append(note);f.append(figure);}
function photoResults(f){const title=document.createElement('h2');title.textContent=t('测试结果：旧版与当前版本','Test results: previous and current versions');f.append(title);const row=(zh,en,a,b)=>[[zh,en],Array.isArray(a)?a:[a,a],Array.isArray(b)?b:[b,b]];f.append(table([['指标','Measure'],['旧版','Previous'],['当前','Current']],[row('用户照片：原照片完全正确','User photos: exact boards, unchanged','4 / 6','5 / 6'),row('用户照片：原照片错误点数','User photos: wrong points, unchanged',['89，另 1 张失败','89, plus 1 failure'],'2'),row('用户照片：72 个样本完全正确','User photos: exact boards, all 72','43','53'),row('用户照片：识别失败','User photos: detection failures','13','0'),row('用户照片：漏掉 / 多出 / 颜色错误','User photos: missed / extra / wrong colour','954 / 52 / 15','9 / 39 / 1'),row('用户照片：被标为需要检查的错误','User photos: errors marked for checking',['1,021 个中的 34 个','34 of 1,021'],['49 个中的 12 个','12 of 49']),row('网上照片：原照片完全正确','Web photos: exact boards, unchanged','7 / 10','9 / 10'),row('网上照片：120 个样本完全正确','Web photos: exact boards, all 120','83','99'),row('网上照片：识别失败','Web photos: detection failures','24','5'),row('网上照片：错误点数','Web photos: wrong points','113','17'),row('本机识别时间','Local recognition time',['中位 2.2 秒，最长 2.9 秒','Median 2.2 s, up to 2.9 s'],['中位 2.3 秒，最长 5.5 秒','Median 2.3 s, up to 5.5 s'])]));}
function render(){const kind=document.body.dataset.document,page=pages[kind],title=t(...page.title);document.title=title+' · DL Weiqi';document.getElementById('document-title').textContent=title;const f=document.createDocumentFragment();page.intro?.(f);addSections(f,page.sections);page.extra?.(f);if(page.after)addSections(f,page.after);const h=document.createElement('h2');h.textContent=t(...(page.sourcesTitle??['参考与实测','Sources and measurements']));f.append(h);const nav=document.createElement('nav');nav.className='page-links';for(const [href,zh,en]of page.links){const a=document.createElement('a');a.href=href;a.textContent=t(zh,en);nav.append(a);}const back=document.createElement('a');back.href='/about';back.textContent=t('返回关于','Back to About');nav.append(back);f.append(nav);document.getElementById('document-content').replaceChildren(f);}
window.addEventListener('site-language-change',render);render();
