import './site-shell.js';
import {t,language,translateError} from './i18n.js';
import {BoardView} from './board-view.js';
import {recordingTree,recordingSgf,newRecordingSgf,addRecordingMove,promoteRecordingBranch,deleteRecordingBranch,RecordingNavigation,recordingNodeIndex} from './recording-tree.js';
import {MAX_SGF_BYTES} from './sgf.js';
import {libraryRequest} from './library-api.js';
import {RecordingTreeView} from './recording-tree-view.js';
import {localTimestamp} from './site-time.js';
const $=id=>document.getElementById(id);let record=null,selected=0,draft=null,dirty=false,writing=false,conflict=false,publishing=false,saveId=null,saveTimer,confirmation;
const treeView=new RecordingTreeView($('editor-tree'),select);let navigation=new RecordingNavigation();
const board=new BoardView($('board'),{onPoint:place,horizontalArrows:false});
function warn(message){$('editor-notice').textContent=message;}
function confirm(title,message,run){confirmation=run;$('editor-confirm-title').textContent=title;$('editor-confirm-text').textContent=message;$('editor-confirm').showModal();}
$('editor-cancel').onclick=()=>$('editor-confirm').close();$('editor-accept').onclick=()=>{$('editor-confirm').close();confirmation?.();};
function changed(){navigation.remember(record,selected);dirty=true;saveId=null;try{localStorage.setItem('weiqi.record.unsaved',JSON.stringify({sgf:recordingSgf(record),selected:recordingNodeIndex(record,selected),expectedRevision:draft.revision}));}catch{}render();clearTimeout(saveTimer);saveTimer=setTimeout(flush,300);}
async function flush(){
 if(writing||!dirty||conflict||publishing)return false;writing=true;const source=recordingSgf(record),position=selected;render(false);
 try{const response=await libraryRequest('/api/draft',{action:'update',expectedRevision:draft.revision,sgf:source,selected:recordingNodeIndex(record,position)});draft=response.draft;if(recordingSgf(record)===source&&selected===position){dirty=false;try{localStorage.removeItem('weiqi.record.unsaved');}catch{}}else{try{localStorage.setItem('weiqi.record.unsaved',JSON.stringify({sgf:recordingSgf(record),selected:recordingNodeIndex(record,selected),expectedRevision:draft.revision}));}catch{}}warn('');}
 catch(e){conflict=e.statusCode===409;warn(conflict?t('其他设备已修改公共草稿。请先下载当前草稿作为备份，然后重新载入。','Another device changed the public draft. Download your draft as a backup, then reload.'):t('尚未保存到云端。当前修改已在此浏览器暂存；请重试。','Not saved to the cloud. Changes are backed up in this browser; please retry.'));}
 finally{writing=false;render(false);if(dirty&&!conflict){clearTimeout(saveTimer);saveTimer=setTimeout(flush,1500);}}return !dirty&&!conflict;
}
function adopt(value){draft=value;record=recordingTree(value.sgf);selected=Math.min(value.selected||0,record.nodes.length-1);navigation=new RecordingNavigation();navigation.remember(record,selected);dirty=false;conflict=false;fillDetails();render();}
async function load(){try{const response=await libraryRequest('/api/draft');adopt(response.draft);const backup=JSON.parse(localStorage.getItem('weiqi.record.unsaved')||'null');if(backup){record=recordingTree(backup.sgf);selected=Math.min(backup.selected||0,record.nodes.length-1);navigation.remember(record,selected);dirty=true;conflict=backup.expectedRevision!==draft.revision;fillDetails();warn(t('已恢复此浏览器中未上传的修改。','Recovered changes not yet uploaded from this browser.'));render();if(!conflict)void flush();}}catch{warn(t('无法载入公共草稿。请刷新重试。','Unable to load the public draft. Refresh to retry.'));}}
function select(id){if(!record||!record.nodes[id])return;selected=id;changed();}
function step(count){if(record)select(navigation.step(record,selected,count));}
function place(index){if(!record||conflict||publishing||draft.publication?.status==='pending')return;try{const mode=$('editor-tool').value;if(mode==='move')selected=addRecordingMove(record,selected,index);else{if(record.nodes.length!==1||selected!==0)throw Error(t('摆子工具仅用于落子前的初始局面。','Setup tools are available only before recording moves.'));const b=record.nodes[0].board.split('');b[index]=mode==='black'?'B':mode==='white'?'W':'.';record.nodes[0].board=b.join('');}warn('');changed();}catch(e){warn(translateError(e.message)==='The request failed. Please sync and try again.'?e.message:translateError(e.message));}}
function fillDetails(){const f=$('editor-details');for(const [key,value]of Object.entries({name:record.name,black:record.players.black,white:record.players.white,date:record.date,komi:record.komi}))f.elements[key].value=value;f.elements.rules.value=['Japanese','Chinese','Korean','AGA'].includes(record.rules)?record.rules:'Other';f.elements.result.value=['0','B+','W+','B+R','W+R'].includes(record.result)?record.result:'original';}
function render(refreshTree=true){
 document.title=t('记录棋局','Record game')+' · Dewei Weiqi';
 const labels={'editor-title':['记录棋局','Record game'],'editor-pass':['停一手','Pass'],'editor-delete':['删除此手及后续分支','Delete move & continuation'],'editor-mainline':['设为主分支','Make main branch'],'editor-reset':['新草稿','New draft'],'editor-upload-label':['打开 SGF','Open SGF'],'editor-download':['下载草稿 SGF','Download draft SGF'],'editor-save':[publishing?'正在保存…':'保存棋局',publishing?'Saving…':'Save game'],'draft-reload':['重新载入公共草稿','Reload public draft'],'editor-tool-label':['落子工具','Board tool'],'editor-turn-label':['初始行棋方','Initial player'],'details-summary':['棋局信息（可在落子前填写）','Game details (optional before starting)'],'label-title':['棋局名称','Game title'],'label-black':['黑方棋手','Black player'],'label-white':['白方棋手','White player'],'label-date':['日期','Date'],'label-rules':['规则','Rules'],'label-komi':['贴目','Komi'],'label-result':['结果（未完成按和棋保存）','Result (unfinished saves as Draw)'],'editor-tree-title':['棋谱树','Game tree'],'editor-cancel':['取消','Cancel'],'editor-accept':['确认','Confirm']};for(const [id,[zh,en]]of Object.entries(labels))$(id).textContent=t(zh,en);
 const tools=[['正常交替落子','Alternating moves'],['摆黑子','Place Black setup stone'],['摆白子','Place White setup stone'],['移除摆子','Remove setup stone']];[...$('editor-tool').options].forEach((o,i)=>o.textContent=t(...tools[i]));$('editor-turn').options[0].textContent=t('黑方','Black');$('editor-turn').options[1].textContent=t('白方','White');
 const f=$('editor-details');[...f.elements.rules.options].forEach(o=>o.textContent=({Japanese:t('日本规则','Japanese'),Chinese:t('中国规则','Chinese'),Korean:t('韩国规则','Korean'),AGA:'AGA',Other:t('原始 SGF 规则','Original SGF rules')})[o.value]);[...f.elements.result.options].forEach(o=>o.textContent=({'0':t('和棋 / 未完成','Draw / unfinished'),'B+':t('黑方获胜','Black wins'),'W+':t('白方获胜','White wins'),'B+R':t('黑方胜（白方认输）','Black wins by resignation'),'W+R':t('白方胜（黑方认输）','White wins by resignation'),original:t('保留 SGF 原结果','Keep original SGF result')})[o.value]);
 $('setup-help').textContent=t('摆子与选择初始行棋方仅在第一手前可用。普通落子会自动提子，并保留分支。','Setup stones and initial-player selection are available before the first move. Normal moves capture stones and preserve branches.');
 $('draft-status').textContent=conflict?t('草稿冲突 · 等待重新载入','Draft conflict · reload required'):publishing?t('正在保存主分支到棋谱库…','Saving the main branch to the library…'):writing||dirty?t('正在自动保存公共草稿…','Auto-saving public draft…'):draft?t('公共草稿 · ','Public draft · ')+(draft.updatedAt?localTimestamp(draft.updatedAt,language):t('尚无修改','No edits yet')):'';
 $('draft-reload').hidden=!conflict;$('editor-save').classList.toggle('is-loading',publishing);$('editor-save').disabled=!record||conflict||publishing;$('editor-file').disabled=publishing||conflict;$('editor-delete').disabled=!selected||publishing||conflict;$('editor-mainline').disabled=!selected||publishing||conflict;
 if(!record)return;const node=record.nodes[selected];board.render(node.board,{last:node.move?.index,turn:node.turn,interactive:!publishing&&!conflict});$('editor-move').textContent=t('第 '+node.depth+' 手','Move '+node.depth);$('editor-turn').value=record.initialPlayer;$('editor-turn').disabled=record.nodes.length!==1;$('editor-tool').disabled=publishing||conflict;for(const o of [...$('editor-tool').options].slice(1))o.disabled=record.nodes.length!==1;if(record.nodes.length>1&&$('editor-tool').value!=='move')$('editor-tool').value='move';
 if(!refreshTree)return;
 $('editor-tree').setAttribute('aria-label',t('棋谱树','Game tree'));
 $('editor-tree-help').textContent=t('蓝色横线连续显示当前变化，其他变化在下方展开。★ 标示主分支。点击棋子切换局面。','The blue row follows your selected sequence; alternatives branch below. ★ marks the main branch. Click a stone to switch positions.');
 treeView.render(record,selected,t,navigation.continuations);
}
$('editor-first').onclick=()=>select(0);$('editor-prev').onclick=()=>step(-1);$('editor-next').onclick=()=>step(1);$('editor-back-ten').onclick=()=>step(-10);$('editor-forward-ten').onclick=()=>step(10);$('editor-last').onclick=()=>{let n=selected;while(navigation.next(record,n)!==undefined)n=navigation.next(record,n);select(n);};
$('editor-pass').onclick=()=>{if(!record||conflict||publishing)return;selected=addRecordingMove(record,selected,null);changed();};
$('editor-mainline').onclick=()=>{promoteRecordingBranch(record,selected);changed();};
$('editor-delete').onclick=()=>confirm(t('删除棋步？','Delete this move?'),t('此手及其后续分支将从公共草稿删除。已保存棋谱不受影响。','This move and its continuations will be removed from the public draft. Saved library games are unaffected.'),()=>{const next=deleteRecordingBranch(record,selected);record=next.record;selected=next.selected;navigation=new RecordingNavigation();changed();});
$('editor-reset').onclick=()=>confirm(t('新建公共草稿？','Start a new public draft?'),t('当前草稿将被清空，所有设备都会更新。已保存棋谱不受影响。','The current public draft will be cleared on all devices. Saved library games are unaffected.'),()=>{record=recordingTree(newRecordingSgf());selected=0;navigation=new RecordingNavigation();fillDetails();changed();});
$('editor-turn').onchange=()=>{if(record.nodes.length===1){record.initialPlayer=$('editor-turn').value;record.nodes[0].turn=record.initialPlayer;changed();}};
$('editor-details').onchange=()=>{const f=$('editor-details');if(!f.reportValidity())return;record.name=f.elements.name.value.trim()||'Recorded game';record.players={black:f.elements.black.value.trim(),white:f.elements.white.value.trim()};record.date=f.elements.date.value;record.komi=Number(f.elements.komi.value);if(f.elements.rules.value!=='Other')record.rules=f.elements.rules.value;if(f.elements.result.value!=='original')record.result=f.elements.result.value;changed();};
$('editor-details').oninput=$('editor-details').onchange;
$('editor-file').onchange=async()=>{const file=$('editor-file').files[0];if(!file)return;try{if(file.size>MAX_SGF_BYTES)throw Error(t('文件不能超过 256 KB。','Files must be no larger than 256 KB.'));const source=new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer()),imported=recordingTree(source);confirm(t('用 SGF 替换当前草稿？','Replace the draft with this SGF?'),t('当前棋盘与所有分支将被清空，并以此文件替换。所有设备都会更新。','The current board and all draft branches will be replaced by this file on every device.'),()=>{record=imported;selected=0;navigation=new RecordingNavigation();fillDetails();changed();});}catch(e){warn(e.message);}$('editor-file').value='';};
$('editor-download').onclick=()=>{if(!record)return;const url=URL.createObjectURL(new Blob([recordingSgf(record)],{type:'application/x-go-sgf;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='weiqi-draft.sgf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
async function publish(){while(writing)await new Promise(resolve=>setTimeout(resolve,100));if(dirty&&!(await flush()))return;publishing=true;saveId=draft.publication?.status==='pending'?draft.publication.id:saveId||crypto.randomUUID();render(false);try{const response=await libraryRequest('/api/draft',{action:'save',expectedRevision:draft.revision,id:saveId});try{localStorage.removeItem('weiqi.record.unsaved');}catch{}location.assign('/game/'+response.id);}catch(e){warn(e.statusCode===409?t('公共草稿已更新，请重新载入后保存。','The public draft changed. Reload before saving.'):t('保存未完成。请重试“保存棋局”；重试不会创建重复棋谱。','Save did not finish. Retry Save game; retries reuse the same game.'));}finally{publishing=false;render(false);}}
$('editor-save').onclick=()=>{if(!record||!$('editor-details').reportValidity())return;confirm(t('保存主分支？','Save the main branch?'),t('仅保存带 ★ 的主分支；其他所有分支将从公共草稿删除。未完成棋局按和棋保存。保存后开始 AI 分析。','Only the main branch marked ★ will be saved. Every other branch will be deleted from the public draft. Unfinished games save as Draw. AI analysis starts after saving.'),publish);};
$('draft-reload').onclick=()=>confirm(t('重新载入公共草稿？','Reload the public draft?'),t('此浏览器尚未同步的修改将被替换。请先下载备份。','Unsynced changes in this browser will be replaced. Download a backup first.'),async()=>{try{localStorage.removeItem('weiqi.record.unsaved');}catch{}await load();});
document.addEventListener('keydown',e=>{if(e.target.closest('input,select,textarea,dialog')||!record)return;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();step(e.key==='ArrowLeft'?-1:1);}});
window.addEventListener('site-language-change',()=>render());
setInterval(async()=>{if(document.hidden||dirty||writing||publishing||conflict||!draft||$('editor-confirm').open||document.activeElement?.closest('form'))return;try{const response=await libraryRequest('/api/draft');if(response.draft.revision>draft.revision||JSON.stringify(response.draft.publication)!==JSON.stringify(draft.publication))adopt(response.draft);}catch{}},5000);
render();void load();
