import {t,setLanguage} from './i18n.js';
const sections=[
 ['1. 上传棋谱','1. Upload a game','打开棋谱库，选择一个 UTF-8 编码的 19 路 SGF 文件，再点击上传。文件不能超过 256 KB。上传时会显示加载图标，保存成功后自动进入棋谱页面。','Open the Record library, choose a UTF-8 SGF file for a 19 × 19 game, then select Upload. Files must be no larger than 256 KB. A spinner appears while uploading, then the game page opens automatically once saved.'],
 ['2. 分享固定链接','2. Share the game link','上传后棋局会获得固定链接，例如 /record/2026100501。直接复制浏览器地址栏中的地址即可分享；收到链接的人可以打开棋谱，无须登录。','Each uploaded game receives a permanent link, such as /record/2026100501. Copy the address from your browser’s address bar to share it. Anyone with the link can open the record without signing in.'],
 ['3. 逐手复盘','3. Replay the moves','棋盘会立即显示，无须等待 AI。键盘或按钮的 ← 和 → 向前或向后移动一手；−10 和 +10 跳转十手；|← 返回初始局面，→| 到达最后一手。▶ 自动播放，Ⅱ 暂停。棋谱有分支时，可以在下拉菜单中选择。','The board appears immediately, while AI analysis runs separately. Use the keyboard’s ← and → keys, or the on-screen buttons, to step backward or forward; −10 and +10 skip ten moves; |← returns to the start and →| goes to the final position. ▶ starts autoplay and Ⅱ pauses it. A variation selector appears when the record contains branches.'],
 ['4. 查看 AI 评估','4. Read the AI evaluation','等待时会显示加载图标、预计剩余时间，以及包含时区的预计完成日期和时间。排队时显示最早完成估计，排队时间另计。快速分析完成后自动显示临时结果；深度分析等待期间继续显示加载图标。快速分析每 15 秒检查一次；显示快速结果后停止自动检查。刷新页面以查看深度分析，已完成时会替换快速结果，并保留当前选择的棋步。Score 显示领先点数：正数为黑方领先，负数为白方领先。Win % 显示黑方胜率，50% 为均势。深色区域表示黑方领先，白色区域表示白方领先；点击或轻触图表即可跳到对应棋步；按住并左右拖动可连续浏览棋步。','While analysis is pending, a loading indicator shows estimated time remaining and the expected completion date and time with your time zone. Queued jobs show an earliest completion estimate; queue time is extra. Quick results appear automatically while a spinner shows that deeper analysis is still pending. Quick results are checked every 15 seconds. Automatic checks stop once quick results appear. Refresh the page to check for deeper results; completed deeper results replace the quick display while keeping your selected move. Score shows the point lead: positive means Black leads and negative means White leads. Win % shows Black’s winning probability, with 50% representing an even game. Dark areas indicate Black ahead; white areas indicate White ahead. Click or tap the graph to jump to a move, or hold and drag left or right to scrub through the game.'],
 ['棋步点评与推荐变化','Move review and recommended lines','“棋步点评与 AI 推荐”默认开启，可关闭并记住选择。最佳着法表示 KataGo 首选；好棋、不精确、失误及严重失误按估计损失点数评级（≤0.5、≤2、≤5、>5 点）。点击“最佳”或“也可”可查看未选择的好棋，并从落子前的局面回放编号变化。使用左右按钮或方向键逐手浏览，点击“返回棋谱”回到原棋步。快速分析的点评仅为初步估计，深度结果更可靠。推荐变化不会改动 SGF，也不会启动付费分析；旧分析没有保存变化时会显示说明。','Move review & AI suggestions is on by default, and remembers your choice. Best means KataGo’s top choice. Good, Inaccuracy, Mistake and Blunder use estimated point loss (≤0.5, ≤2, ≤5 and >5 points). Select Best or Also good to replay a missed alternative as a numbered line, starting before the played move. Use the arrow buttons or keys to step through it, then Return to record to restore your selected move. Quick ratings are preliminary; deeper results are more reliable. These previews do not change the SGF or start paid analysis. Older analyses without saved variations show an explanation.'],
 ['分析失败与重试','Analysis failures and retries','如果分析失败，棋谱和已有快速结果仍可查看。系统最多自动重试两次，分别在失败后 5 分钟和 15 分钟。界面显示预计重试日期、时间、时区以及剩余时间；深度分析仍需刷新页面检查。两次重试用完后会显示说明。','If analysis fails, your game and any quick results remain available. The system schedules at most two retries, five minutes and then fifteen minutes after failure. Replay shows the retry date, time, time zone and remaining wait. Refresh the page to check deep-analysis retries. A clear message appears when both retries are exhausted.'],
 ['5. 试下与下载','5. Try moves and download','在复盘棋盘的空点上落子可以试下。使用“撤回试下”或“返回棋谱”恢复原局面。试下不会保存或触发 AI 分析。点击“下载 SGF”可保存原始文件，其中的注释和分支会保留。','Click an empty intersection on the replay board to try a continuation. Use Undo preview or Return to record to restore the recorded position. Preview moves are not saved or analysed. Download SGF saves the original file, including its comments and variations.'],
 ['分析范围与每日限额','Analysis coverage and daily limit','AI 分析主线的初始局面和每一手后的局面，不分析分支或试下。两个阶段均使用最新官方模型。快速分析搜索深度较低，目标为 3–5 分钟内完成；深度分析搜索更多局面，目标为一小时内完成。目标包含排队与容量等待，耗时会随棋谱长度和最新模型大小改变。每天前 20 个上传棋谱可启动 AI 分析；达到限额后，棋谱仍会保存并可复盘。SGF 指定的规则和贴目会用于分析，未注明规则时采用日本规则。','AI evaluates the initial position and every main-line move, excluding variations and preview moves. Both passes use the latest official model. Quick analysis uses a shallower search and targets 3–5 minutes; deep analysis searches more positions and targets an hour. Targets include queueing and capacity waiting; timings vary with game length and the latest model size. The first 20 uploads each day can start analysis; later uploads are still saved and available for replay. Analysis uses the SGF’s rules and komi, defaulting to Japanese rules when rules are omitted.'],
 ['直接对弈','Play a shared game','主页提供一盘全站共用的 19 路棋局。访问者可以操作黑白双方；落子会保存并同步到其他设备。可以停一手、悔棋、认输并下载 SGF。开始新局会把之前的棋局移入历史棋局。主页对弈采用中国数子法，白贴 7.5 点。','The home page offers one shared 19 × 19 game. Visitors can play either side, with moves saved and synced across devices. You can pass, undo, resign and download SGF. Starting a new game archives the previous game in Game history. Live play uses Chinese area scoring with 7.5 points komi.']
];
function render(){document.title=t('使用指南 · DL','How to use · DL');document.getElementById('guide-title').textContent=t('使用指南','How to use');const fragment=document.createDocumentFragment(),actions=document.createElement('nav');actions.className='guide-actions';for(const [href,zh,en] of [['library.html','上传 SGF / 棋谱库','Upload SGF / Record library'],['./','直接对弈','Play a shared game']]){const a=document.createElement('a');a.href=href;a.textContent=t(zh,en);actions.append(a);}fragment.append(actions);for(const [zh,en,bodyZh,bodyEn] of sections){const article=document.createElement('article'),h=document.createElement('h2'),p=document.createElement('p');h.textContent=t(zh,en);p.textContent=t(bodyZh,bodyEn);article.append(h,p);fragment.append(article);}document.getElementById('guide-content').replaceChildren(fragment);}
document.querySelectorAll('[data-language]').forEach(b=>b.onclick=()=>{setLanguage(b.dataset.language);render();});render();
