import './site-shell.js';
import {t} from './i18n.js';
import {flow,lanes,stats,callout,svg,more as details} from './flow-diagram.js';
const sections=[
 ['全站公开','A public shared site','所有棋谱、现场棋局和记录草稿都公开，无须登录。任何访问者都能修改当前现场棋局或公共草稿。请勿填写私人信息。已保存的棋谱不会随草稿修改。','Games, live play and the recording draft are public, with no sign-in. Anyone can edit the current live game or shared draft. Do not enter private information. Editing the draft does not change games already saved in the library.'],
 ['1. 现场对弈 /play','1. Live play /play','全站同时只有一盘 19 路现场棋局。可在同一设备操作双方，或在不同设备打开同一页面。可在开始前或途中填写棋手、名称、日期、规则及贴目。选择规则时自动设置贴目：中国规则 7.5 目，日本规则 6.5 目，之后仍可修改。段级位选填；现场计时显示已用时间。支持停一手；悔棋会永久删除最近一手。点击“新一局”、“认输”或“确认死子”，在同一个窗口选择结果：黑 / 白胜若干目（默认为自动数子结果，可修改）、黑 / 白中盘胜或未完成。50–400 手的棋局自动保存到棋谱库；不足 50 手不保存。每局最多 400 手（含停一手）；达到上限后不能再落子或停一手，请点击“新一局”选择结果，该局不保存。点击“新一局”后留在现场页面，棋盘清空并开始新一局；通过“认输”或双方停一手后确认结果，则打开已保存的棋谱。其他打开现场页面的设备会弹窗提示哪方认输，并可打开该棋谱。','There is one shared 19 × 19 live game. Play both sides on one device, or open the same page on different devices. Game details can be set before starting or edited during play. Choosing rules sets komi: 7.5 for Chinese, 6.5 for Japanese; you can still change it. Player ranks are optional. The live clock shows elapsed time. Pass is available. Undo permanently removes the last move. New game, a resign button or Confirm dead stones opens one result window: Black or White wins by a number of points (the automatic count is selected and can be changed), wins by resignation, or Unfinished. Games of 50–400 moves save to the library; shorter games are not saved. A game can have at most 400 moves, counting passes. At the limit, moves and passes stop; select New game to choose the result. The game is not saved. New game keeps you on the live page with a fresh board. Resigning, or confirming the result after both players pass, opens the saved game. Other devices on the live page see who resigned, with a link to the game.'],
 ['2. 记录棋局 /record','2. Record a game /record','点击棋盘交替记录黑白着法，自动提子。每次落子、编辑或打开 SGF 都自动保存到同一个公共草稿；关闭页面后可从任何设备继续。棋局信息会自动补全；贴目默认日本 / 韩国规则 6.5 目，中国 / AGA 规则 7.5 目，让子棋 0.5 目。改变让子数会重新设置贴目；之后仍可手动调整。导入时保留 SGF 已有贴目。黑白棋手默认使用“Unnamed black player”和“Unnamed white player”。原有棋局信息均为必填，默认已补全。先选择黑方获胜、白方获胜或未完成；获胜原因可留空，或选择超时、认输、按目数。按目数时须填写胜出目数。地点 / 场馆为选填，并写入 SGF 的 PC 属性。第一手前可设置整数 0–9 的让子数；让 1 子时棋盘留空，黑方自由落第一手；只把贴目调整为 0.5 目。2–9 子预摆让子，白方先行。停一手按钮记录虚着。每个分支最多 400 手（含停一手）；超过 400 手的 SGF 不能打开。SGF 须为 UTF-8、19 路且不超过 256 KB；打开文件前会确认替换当前棋盘和所有分支。“旋转棋盘”可切换四个视角；棋谱仍使用标准坐标，保存后按正常方向显示。现场对弈和记录棋局的落子都有声音，可调节音量，调到 0 即静音；此设备会记住音量。记录阶段不运行 AI。若另一设备先修改草稿，界面会提示冲突；你仍可在本设备继续操作，但修改不会同步，点击“重新载入公共草稿”获取最新版本。','Click the board to record alternating moves and automatic captures. Moves, edits and SGF imports auto-save to one public draft, which can be resumed from another device. Game details are filled automatically. Default komi is 6.5 for Japanese/Korean rules, 7.5 for Chinese/AGA rules and 0.5 for handicap games. Changing handicap resets komi; you can adjust it afterwards. Import keeps an SGF’s existing komi. Player defaults include Unnamed black player and Unnamed white player. Existing game-detail fields are required and filled by default. Choose Black wins, White wins or Unfinished. Leave the reason blank or choose timeout, resignation or points. A win by points requires a winning margin. Location / venue is optional and saved in the SGF PC property. Before the first move, choose an integer handicap from 0–9; With handicap 1, the board stays empty and Black freely plays the first move; komi changes to 0.5. For handicap 2–9, setup stones are placed and White moves first. Pass records a passing move. Each branch can have at most 400 moves, counting passes; SGF files with more cannot be opened. SGFs must be UTF-8, 19 × 19 and at most 256 KB. Import asks before replacing the board and every draft branch. Rotate board cycles through four viewing angles. Stored coordinates stay unchanged, so the saved game opens in the usual orientation. Live play and recording use a stone-placement sound. Adjust its volume, or set it to zero to mute; the device remembers your setting. Recording runs no AI. If another device changes the draft first, you can keep working on this device, but those changes will not sync; click Reload public draft to get the latest version.'],
 ['分支与保存','Branches and saving','返回早先局面再落另一手，会保留原着法并创建分支。右侧棋谱树以横向棋子显示着法，变化从分歧处向下展开；当前变化沿蓝色横线连续显示，其他变化在下方展开；★ 标示主分支。点击棋子切换局面，左右方向键沿所选变化前后移动。选中的变化自动成为主分支。“删除单手”仅移除所选的一手并保留后续棋步；“插入单手”在当前局面后添加一手并保留后续棋步。这些操作会自动打开本地编辑模式，不会立即上传。云端要求每一分支黑白交替，检查失败时原草稿保持不变。若漏记或多记了黑白一对棋步，请使用“编辑棋谱”，连续插入或删除，后续着法和分支会保留。批量编辑仅存在于此页面内存，刷新或取消会丢弃，不会暂存到浏览器或上传。点击“应用修改”后，云端检查所有分支；合法后才一次性保存。云端拒绝时，原草稿保持不变，可继续修正。“调整落点”可修改所选棋步的位置并保留后续棋步。“清空棋盘”清除棋步、分支与让子，保留棋局信息。“保存棋局”会确认仅保存当前选中的完整分支，其他变化将删除。保存成功后公共草稿清空，包括棋步、分支及棋局信息。随后自动打开 /game/棋局编号，开始 AI 分析。','Return to an earlier position and play a different move to create a branch while keeping the original. The game tree uses numbered stones along horizontal paths, with alternatives splitting below at the changed move. The selected variation continues along the blue row, with other paths below; ★ marks the saved main line. Click a stone to switch positions; Left and Right follow the selected variation. The selected variation becomes the main branch automatically. Delete move removes one move and retains later moves. Insert move adds one move after the selected position and retains the continuation. These controls open the local Edit sequence workspace rather than uploading immediately. The cloud requires alternating Black/White turns in every variation before saving. To correct a missing or extra Black/White pair, use Edit sequence and insert or delete moves together while retaining later moves and variations. Sequence edits exist only in page memory: refresh or Cancel discards them, with no browser backup or upload. Apply edits sends every variation to the cloud for validation and one atomic save. If rejected, the original draft stays unchanged and you can keep correcting. Reposition move changes the selected move’s location while keeping later moves. Clear board removes moves, variations and handicap stones while keeping game details. Save game confirms that only the complete selected branch is saved and other variations are removed. Once saved, the public draft resets, including moves, branches and game details. The saved /game/game-number page opens automatically and AI analysis begins.'],
 ['3. 棋谱库与复盘 /game','3. Library and replay /game','棋谱库每页显示最新 5 局，并显示总页数；上一页 / 下一页加载其他棋谱。复制棋局页面地址即可分享。棋盘立即显示，无须等待 AI；左右方向键或导航按钮逐手复盘。点击或按住拖动 AI 图表可跳到对应棋步。Score 的正数表示黑方领先，负数表示白方领先；Win % 显示黑方胜率。颜色区分双方。桌面右侧独立滚动，切换棋步保留滚动位置。','The library loads five games per page and shows the number of pages; Previous / Next loads other pages. Share a game by copying its page address. Replay appears immediately, before AI is ready. Use arrow keys or navigation buttons to step through moves. Click or hold and drag the AI graph to choose a move. Positive Score means Black leads; negative means White leads. Win % shows Black’s winning probability. Colours distinguish the sides. On desktop, the right panel scrolls independently and keeps its position when stepping.'],
 ['AI 等待、限额与重试','AI waiting, limits and retries','每个保存的棋局都有快速分析；每天前 10 局（全站共享额度）还有深度分析和报告，其余只有快速分析。快速分析目标为 5 分钟内，深度分析目标为 1 小时，最多等待预期为 2 小时；包含排队与准备，云端容量不能保证。快速分析每分钟检查；出现快速分析后停止检查，请刷新页面查看深度分析。界面显示等待总时间、预计完成日期、UTC 时区和剩余时间；无法可靠预测容量时明确提示。失败最多重试两次，分别等待 5 分钟及 15 分钟，页面显示原因和重试时间。','Every saved game gets quick analysis. The first ten each day, shared across the site, also get deep analysis and a report; later games get quick analysis only. Quick analysis targets five minutes; deep targets one hour with a two-hour maximum wait expectation, including queue and setup. Cloud capacity is not guaranteed. Quick analysis are checked once a minute; checks stop when quick analysis appear. Refresh for deep analysis. The page shows total waiting time, estimated completion with UTC offset and remaining time, or explains when capacity cannot be predicted. Failures retry at most twice, after five and then fifteen minutes, with the reason and retry time shown.'],
 ['推荐着法与试下','Suggested moves and exploration','默认显示 AI 推荐，可关闭。字母表示当前局面的下一手候选；蓝色为首选，绿色为其他好棋。三角形标示下一手实战：绿色为好棋，黄色为不精确，橙色为失误，红色为严重失误，灰色为未评定。点击推荐表格的一行，棋盘显示完整的编号变化；再次点击同一行恢复原棋盘。桌面鼠标悬停时临时预览，离开后恢复原棋盘或已选中的变化。表格保留并标示选中行；评估属于原局面。领先目数用领先方的黑白底色显示，胜率并列显示黑方和白方；≈ 表示估计。点击棋盘推荐点或“逐手试下”，从第一手开始，之后可继续点击已保存的后续推荐点；编号接续已落棋步，例如第六手后显示 7。并非每个选点都有后续变化；没有时会提示。左右键在变化中逐手前后移动；“实战”按钮前往实战着法，“返回原局面”恢复原局面，退回变化起点也会自动返回主棋谱。试下不改动已保存棋谱，也不启动新计算。好棋、不精确、失误和严重失误按估计损失目数使用 0.5、2、5 目阈值；这些是本站点评规则，并非棋手等级。','AI suggestions are on by default and can be toggled. Letters mark candidates for the next move from the displayed position: blue for the first choice and green for other good moves. A triangle marks the next actual move: green for good, yellow for inaccuracy, orange for mistake, red for blunder and grey for unrated. Click a table row to pin its full numbered continuation; click the same row again to restore the original board. On desktop, hovering previews temporarily and leaving restores the previous board or pinned line. The table keeps its position and highlights the previewed row. Evaluations belong to the original position. Lead badges use the leading side’s colour; winning percentages show Black and White side by side. ≈ marks estimates. Click a board suggestion or Explore line to start at the first move, then click available saved follow-up points. Their numbers continue the sequence, such as 7 after six moves. Some choices have no saved continuation; the page says when none is available. Arrows step within the line. Played opens the recorded move; Return to original position restores the original position, as does stepping back to the line’s origin. Exploration changes no saved game and starts no computation. Good, Inaccuracy, Mistake and Blunder use estimated point-loss thresholds of 0.5, 2 and 5 points. These are site review labels, not player ranks.'],
 ['AI 报告与下载','AI reports and downloads','深度分析完成后，系统自动准备中英文报告及 PDF。“查看 AI 报告”打开报告，语言菜单切换中英文，“保存 PDF”下载已经生成的文件，不启动新计算。报告先展示带手数的总谱，再展示全局目差与胜率，再展示着法质量、典型损失、棋局阶段和关键失误。双方各五手失误列在表格，前三手详细复盘。报告时间使用服务器 UTC；其他页面使用设备本地时间并标明 UTC 偏移。下载 SGF 可保存棋谱。','After deep analysis, both language reports and PDFs are prepared automatically. View AI report opens the report, the language menu switches languages, and Save PDF downloads an existing file without new computation. Reports begin with the numbered full game record, then game-wide point advantage and winning chances, then move quality, typical losses, game phases and key mistakes. Each side’s five worst moves appear in a table, with three reviewed in detail. Report timestamps use server UTC; other pages use your device’s local time with a UTC offset. Download SGF saves the record.']
];
function el(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!=null)node.textContent=text;return node;}
function figure(title,...children){const f=el('figure','dg');f.append(el('figcaption','',title),...children);return f;}
function startLanes(){
 return lanes({title:t('从这里开始','Where to start'),lanes:[
  {icon:'play',href:'/play',title:t('对弈','Play game'),steps:[{icon:'play',title:t('双方轮流落子','Play both sides'),text:t('一台或多台设备','One or more devices')},{icon:'flag',title:t('停一手两次或认输','Pass twice or resign')},{icon:'check',title:t('确认结果','Confirm the result'),text:t('数子估计供参考','Count estimate helps')},{icon:'library',title:t('自动存入棋谱库','Recorded to the library'),tone:'good'}]},
  {icon:'record',href:'/record',title:t('记录棋局','Record game'),steps:[{icon:'record',title:t('点击记录着法','Click to add moves'),text:t('或打开 SGF','Or open an SGF')},{icon:'retry',title:t('草稿自动保存','Draft saves itself'),text:t('可在任何设备继续','Continue on any device')},{icon:'branch',title:t('分支与编辑','Branches and edits')},{icon:'gpu',title:t('记录 → 深度 AI 分析','Record → deep AI analysis'),tone:'good'}]},
  {icon:'katago',href:'/analysis',title:t('AI 分析','AI analysis'),steps:[{icon:'camera',title:t('照片 / SGF / 摆子','Photo / SGF / set up')},{icon:'eye',title:t('照片识别','Photo detection'),text:t('约 8 秒','About 8 s')},{icon:'flag',title:t('检查琥珀色框','Check amber boxes'),text:t('点击修改棋子','Tap to fix a stone')},{icon:'chart',title:t('快速 AI 分析','Quick AI analysis'),text:t('推荐着法','Suggested moves'),tone:'good'}]}
 ]});
}
function afterRecord(){
 return flow({title:t('记录之后','After you record'),numbered:true,steps:[
  {icon:'library',title:t('记录','Record'),text:t('存入棋谱库','Into the library')},
  {icon:'eye',title:t('立即复盘','Replay now'),text:t('棋局页面','Game page')},
  {icon:'clock',title:t('快速 AI','Quick AI'),text:t('≈ 5 分钟','≈ 5 min')},
  {icon:'gpu',title:t('深度 AI','Deep AI'),text:t('≈ 1 小时，最多 2 小时','≈ 1 h, up to 2 h')},
  {icon:'report',title:t('AI 报告','AI report'),text:t('中英文 · PDF','EN / 中文 · PDF'),tone:'good'}
 ],note:t('每局都有快速分析；每天前 10 局还有深度分析和报告。失败后 5 分钟、15 分钟自动重试。快速分析出现后，刷新页面查看深度分析。','Every game gets quick AI; the first 10 each day also get deep AI and a report. Failures retry after 5 and 15 minutes. After quick AI appears, refresh to see deep AI.')});
}
function gameLayout(){
 const block=(text,kind)=>el('div','dg-block'+(kind?' '+kind:''),text),labels=()=>({meta:t('棋局信息','Game details'),volume:t('音量','Volume'),chart:t('胜率图','Win-rate chart'),board:t('棋盘','Board'),nav:t('◀ ▶ 按钮','◀ ▶ buttons'),table:t('推荐表格','Suggestions table')});
 const l=labels(),wrap=el('div','dg-layouts');
 const phone=el('div','dg-device'),phoneScreen=el('div','dg-screen phone');phoneScreen.append(block(l.meta),block(l.volume),block(l.chart,'chart'),block(l.board,'board'),block(l.nav),block(l.table,'table'));phone.append(phoneScreen,el('span','',t('手机','Phone')));
 const desk=el('div','dg-device'),deskScreen=el('div','dg-screen desktop'),left=el('div','dg-col'),right=el('div','dg-col');left.append(block(l.board,'board'),block(l.nav));right.append(block(l.meta),block(l.volume),block(l.chart,'chart'),block(l.table,'table'));deskScreen.append(left,right);desk.append(deskScreen,el('span','',t('电脑','Desktop')));
 wrap.append(phone,desk);
 const f=figure(t('棋局页面','Game page'),wrap);f.append(el('p','dg-note',t('点击或拖动胜率图可跳到该手。点击推荐表格的一行，在棋盘上显示变化；再点一次恢复。','Tap or drag the chart to jump to a move. Tap a table row to show its line on the board; tap again to go back.')));return f;
}
function boardSymbols(){
 const list=el('ul','dg-legend');
 const add=(mark,text)=>{const li=el('li');li.append(mark,el('span','',text));list.append(li);};
 const circle=(letter,colour)=>{const s=el('span','dg-symbol',letter);s.style.background=colour;return s;};
 const triangle=colour=>svg({viewBox:'0 0 100 100',class:'dg-tri','aria-hidden':'true'},[['polygon',{points:'50,8 92,88 8,88',fill:colour,stroke:'#fff','stroke-width':6,'stroke-linejoin':'round'}]]);
 add(circle('A','#2978ce'),t('AI 首选','AI best move'));add(circle('B','#327e53'),t('其他好棋','Other good move'));
 for(const [colour,zh,en]of [['#27834c','实战：好棋','Played: good'],['#d7ad20','实战：不精确','Played: inaccuracy'],['#df7a19','实战：失误','Played: mistake'],['#d33c36','实战：严重失误','Played: blunder'],['#64748b','实战：未评定','Played: unrated']])add(triangle(colour),t(zh,en));
 const keys=el('span','dg-keys');keys.append(el('kbd','','←'),el('kbd','','→'));add(keys,t('上一手 / 下一手','Previous / next move'));
 const f=figure(t('棋盘符号','Board symbols'),list);f.append(el('p','dg-note',t('△ 是棋谱中的下一手，颜色表示 AI 对它的评价。','△ marks the next recorded move; its colour is the AI rating.')));return f;
}
function branchTree(){
 const black='#28323a',white='#fff',main='#147cab',side='#8c9ba4',stone=(x,y,n,colour,star)=>[['circle',{cx:x,cy:y,r:16,fill:colour,stroke:'#74818a','stroke-width':1.5}],['text',{x,y:y+4.5,'text-anchor':'middle','font-size':13,'font-weight':650,fill:colour===black?'#fff':'#28323a','font-family':'system-ui'},String(n)],...(star?[['text',{x:x+14,y:y-12,'font-size':12,fill:'#8c651e','font-family':'system-ui'},'★']]:[])];
 const parts=[['path',{d:'M30 40H330',stroke:main,'stroke-width':3,fill:'none'}],['path',{d:'M150 40C180 40 180 105 210 105H270',stroke:side,'stroke-width':2.5,fill:'none'}],['circle',{cx:30,cy:40,r:16,fill:'#e6ebed',stroke:'#52636c','stroke-dasharray':'3 3'}],...stone(90,40,1,black,true),...stone(150,40,2,white,true),...stone(210,40,3,black,true),...stone(270,40,4,white,true),...stone(330,40,5,black,true),...stone(210,105,3,black),...stone(270,105,4,white),['text',{x:362,y:44,'font-size':13,fill:'#35434b','font-family':'system-ui'},t('主分支','Main line')],['text',{x:302,y:109,'font-size':13,fill:'#52636c','font-family':'system-ui'},t('分支','Branch')]];
 const tree=svg({viewBox:'0 0 440 135',class:'dg-tree',role:'img','aria-label':t('棋谱树示例','Example game tree')},parts);
 const f=figure(t('分支','Branches'),tree);f.append(el('p','dg-note',t('回到早先一手再下另一手，就会生成分支。点击棋子跳到该手。★ 为主分支；记录时只保存所选分支。','Go back and play a different move to make a branch. Tap a stone to jump to it. ★ marks the main line; Record keeps only the selected branch.')));return f;
}
function render(){
 document.title=t('使用指南','User guide')+' · DL Weiqi';document.getElementById('guide-title').textContent=t('使用指南','User guide');
 const fragment=document.createDocumentFragment();
 fragment.append(callout('users',t('全站公开，无须登录：任何人都能修改现场棋局和记录草稿。请勿填写私人信息。','Public site, no sign-in: anyone can edit the live game and the record draft. Do not enter private information.')),startLanes(),afterRecord(),stats([['10',t('每天有 AI 分析的棋局','games with AI each day'),'gpu'],['100',t('每天新棋谱','new records a day'),'library'],['≈ 1,000',t('每天局面分析（全站）','position analyses a day'),'katago'],['2',t('失败自动重试','automatic retries'),'retry']]),gameLayout(),boardSymbols(),branchTree());
 const detail=document.createDocumentFragment();
 for(const [zh,en,bodyZh,bodyEn]of sections){const article=el('article'),h=el('h2','',t(zh,en)),p=el('p','',t(bodyZh,bodyEn));article.append(h,p);detail.append(article);}
 fragment.append(details(t('完整文字说明','Full text guide'),detail));
 document.getElementById('guide-content').replaceChildren(fragment);
}
window.addEventListener('site-language-change',render);render();
