import './site-shell.js';
import {t,language} from './i18n.js';
import {libraryRequest} from './library-api.js';
import {localTimestamp,analysisQuotaDate} from './site-time.js';
import {gameResult} from './game-result.js';
const $=id=>document.getElementById(id);let records=[],cursor=null,page=0,pageCursors=[null],loading=false;
function render(){document.title=t('棋谱库','Game library')+' · DL Weiqi';$('library-title').textContent=t('棋谱库','Game library');$('library-previous').textContent=t('上一页','Previous');$('library-next').textContent=t('下一页','Next');$('library-page').textContent=t('第 '+(page+1)+' 页 · 每页 10 局','Page '+(page+1)+' · 10 games per page');$('library-previous').disabled=loading||page===0;$('library-next').disabled=loading||!cursor;
 const fragment=document.createDocumentFragment();for(const r of records){const a=document.createElement('a');a.className='game-entry';a.href='/game/'+encodeURIComponent(r.id);const name=document.createElement('strong');name.textContent=r.name;const detail=document.createElement('small'),result=gameResult(r.result);detail.textContent=['black','white'].map(side=>(r.players[side]|| (side==='black'?t('黑方','Black'):t('白方','White')))+(r.playerRanks?.[side]?' ('+r.playerRanks[side]+')':'')).join(' / ')+(r.date?' · '+r.date:'')+(result?' · '+t(result.zh,result.en):'')+' · '+r.moves+t(' 手',' moves');const saved=document.createElement('small');saved.textContent=t('保存于：','Saved: ')+localTimestamp(r.uploadedAt,language);const status=document.createElement('span');status.className='library-analysis-status';status.textContent=r.analysis.status==='paused'?t('棋谱已保存 · AI 分析已暂停','Game saved · AI analysis paused'):r.analysis.status==='limited'?t('已保存 · '+analysisQuotaDate(r)+' 的 AI 限额已满','Saved · daily AI limit reached for '+analysisQuotaDate(r)):r.analysis.status==='ready'?t('AI 分析可用','AI analysis available'):r.analysis.status==='failed'?t('AI 分析失败 · 查看详情','AI analysis failed · view details'):t('AI 分析处理中','AI analysis pending');a.append(name,detail,saved,status);fragment.append(a);}$('records').replaceChildren(fragment);}
async function load(target=0){if(loading)return;loading=true;render();$('library-status').textContent=t('正在载入…','Loading…');try{const data=await libraryRequest('/api/library'+(pageCursors[target]?'?cursor='+encodeURIComponent(pageCursors[target]):''));records=data.games;page=target;cursor=data.cursor;pageCursors[page+1]=cursor;$('library-status').textContent=records.length?'':t('尚无已保存棋局。','No saved games yet.');}catch{$('library-status').textContent=t('加载失败。刷新页面重试。','Could not load games. Refresh to retry.');}finally{loading=false;render();}}
$('library-previous').onclick=()=>load(page-1);$('library-next').onclick=()=>load(page+1);window.addEventListener('site-language-change',render);render();void load();
