import {t,setLanguage,language} from './i18n.js';
import {readSgf,MAX_SGF_BYTES} from './sgf.js';
import {libraryRequest} from './library-api.js';
const $=id=>document.getElementById(id);let records=[],cursor=null,page=0,pageCursors=[null],loading=false,uploading=false,uploadId=null,selectedFile=null;
function render(){document.title=t('棋谱库 · DL','Record library · DL');$('library-title').textContent=t('棋谱库','Record library');$('upload-label').textContent=t('上传 SGF','Upload SGF');$('upload-help').textContent=t('仅支持 19 路 · UTF-8 · 最大 256 KB。保存后立即获得链接，AI 分析在后台运行。','19 × 19 only · UTF-8 · Up to 256 KB. Get a link immediately; AI analysis runs separately.');$('upload-button').textContent=uploading?t('正在上传…','Uploading…'):t('上传','Upload');$('upload-button').disabled=uploading;$('sgf-file').disabled=uploading;$('upload-wait').classList.toggle('is-loading',uploading);$('upload-form').setAttribute('aria-busy',String(uploading));$('library-previous').textContent=t('上一页','Previous');$('library-next').textContent=t('下一页','Next');$('library-page').textContent=t('第 '+(page+1)+' 页','Page '+(page+1));$('library-previous').disabled=loading||page===0;$('library-next').disabled=loading||!cursor;
 const fragment=document.createDocumentFragment();for(const r of [...records].sort((a,b)=>b.uploadedAt.localeCompare(a.uploadedAt))){const a=document.createElement('a');a.className='game-entry';a.href='/record/'+encodeURIComponent(r.id);const name=document.createElement('strong');name.textContent=r.name;const detail=document.createElement('small');detail.textContent=[r.players.black || t('黑方','Black'),r.players.white || t('白方','White')].join(' / ')+(r.date?' · '+r.date:'')+(r.result?' · '+r.result:'')+' · '+r.moves+t(' 手',' moves')+' · '+new Date(r.uploadedAt).toLocaleString(language==='zh'?'zh-CN':'en-GB');a.append(name,detail);fragment.append(a);}$('records').replaceChildren(fragment);}
async function load(target=0){if(loading)return;loading=true;render();$('library-status').textContent=t('正在载入…','Loading…');try{const data=await libraryRequest('/api/library'+(pageCursors[target]?'?cursor='+encodeURIComponent(pageCursors[target]):''));records=data.games;page=target;cursor=data.cursor;pageCursors[page+1]=cursor;$('library-status').textContent=records.length?'':t('尚无上传棋谱。','No uploaded records yet.');}catch(e){$('library-status').textContent=t('加载失败。刷新页面重试。','Could not load records. Refresh to retry.');}finally{loading=false;render();}}
$('sgf-file').onchange=()=>{uploadId=null;selectedFile=$('sgf-file').files[0];$('record-link').hidden=true;$('upload-status').textContent='';};
$('upload-form').onsubmit=async event=>{event.preventDefault();if(uploading)return;const file=selectedFile || $('sgf-file').files[0];if(!file)return;uploading=true;render();try{if(file.size>MAX_SGF_BYTES)throw Error(t('文件不能超过 256 KB。','Files must be no larger than 256 KB.'));let source;try{source=new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(await file.arrayBuffer());}catch{throw Error(t('请上传 UTF-8 编码的 SGF。','Please upload a UTF-8 SGF.'));}readSgf(source);uploadId ||= crypto.randomUUID();$('upload-status').textContent=t('正在保存…','Saving…');const data=await libraryRequest('/api/library',{id:uploadId,filename:file.name,sgf:source});$('upload-status').textContent=t('已保存，正在打开棋谱…','Saved. Opening game…');location.assign('/record/'+encodeURIComponent(data.id));}catch(e){$('upload-status').textContent=e.message;}finally{uploading=false;render();}};
$('library-previous').onclick=()=>load(page-1);$('library-next').onclick=()=>load(page+1);document.querySelectorAll('[data-language]').forEach(b=>b.onclick=()=>{setLanguage(b.dataset.language);render();});render();load();
